// help-data.js — Curated syntax + description for every builtin, shown by
// the `help` function. Kept as plain data (not generated from the
// registry) so descriptions can be genuinely useful rather than just
// echoing a function name back.

export const HELP_DATA = new Map(Object.entries({
  // ---- constants ----
  pi: { syntax: 'pi', desc: 'Ratio of a circle\'s circumference to its diameter, 3.14159...' },
  e: { syntax: 'e', desc: 'Euler\'s number, 2.71828...' },
  Inf: { syntax: 'Inf', desc: 'Positive infinity.' },
  NaN: { syntax: 'NaN', desc: 'Not-a-Number, the result of undefined operations like 0/0.' },
  eps: { syntax: 'eps', desc: 'Floating-point relative accuracy (smallest distinguishable gap near 1).' },
  i: { syntax: 'i', desc: 'Imaginary unit, sqrt(-1). (also: j)' },
  j: { syntax: 'j', desc: 'Imaginary unit, sqrt(-1). (also: i)' },

  // ---- elementwise math ----
  sin: { syntax: 'y = sin(x)', desc: 'Sine of x (radians), elementwise.' },
  cos: { syntax: 'y = cos(x)', desc: 'Cosine of x (radians), elementwise.' },
  tan: { syntax: 'y = tan(x)', desc: 'Tangent of x (radians), elementwise.' },
  asin: { syntax: 'y = asin(x)', desc: 'Inverse sine (radians). Complex result for |x| > 1.' },
  acos: { syntax: 'y = acos(x)', desc: 'Inverse cosine (radians). Complex result for |x| > 1.' },
  atan: { syntax: 'y = atan(x)', desc: 'Inverse tangent (radians).' },
  atan2: { syntax: 'theta = atan2(y, x)', desc: 'Four-quadrant inverse tangent of y/x (radians).' },
  sinh: { syntax: 'y = sinh(x)', desc: 'Hyperbolic sine, elementwise.' },
  cosh: { syntax: 'y = cosh(x)', desc: 'Hyperbolic cosine, elementwise.' },
  tanh: { syntax: 'y = tanh(x)', desc: 'Hyperbolic tangent, elementwise.' },
  exp: { syntax: 'y = exp(x)', desc: 'e^x, elementwise.' },
  log: { syntax: 'y = log(x)', desc: 'Natural logarithm. Complex result for negative real x.' },
  log10: { syntax: 'y = log10(x)', desc: 'Base-10 logarithm. Complex result for negative real x.' },
  log2: { syntax: 'y = log2(x)', desc: 'Base-2 logarithm. Complex result for negative real x.' },
  sqrt: { syntax: 'y = sqrt(x)', desc: 'Square root. Complex result for negative real x.' },
  abs: { syntax: 'y = abs(x)', desc: 'Absolute value (or magnitude, for complex x).' },
  angle: { syntax: 'theta = angle(z)', desc: 'Phase angle of complex z, in radians. (also: arg)' },
  arg: { syntax: 'theta = arg(z)', desc: 'Phase angle of complex z, in radians. (also: angle)' },
  real: { syntax: 'r = real(z)', desc: 'Real part of z.' },
  imag: { syntax: 'i = imag(z)', desc: 'Imaginary part of z.' },
  conj: { syntax: 'w = conj(z)', desc: 'Complex conjugate.' },
  sign: { syntax: 's = sign(x)', desc: 'Sign of x (-1, 0, or 1); for complex x, x./abs(x).' },
  floor: { syntax: 'y = floor(x)', desc: 'Round toward negative infinity.' },
  ceil: { syntax: 'y = ceil(x)', desc: 'Round toward positive infinity.' },
  round: { syntax: 'y = round(x)', desc: 'Round to nearest integer.' },
  fix: { syntax: 'y = fix(x)', desc: 'Round toward zero.' },
  mod: { syntax: 'r = mod(a, b)', desc: 'Modulus after division; result has the same sign as b.' },
  rem: { syntax: 'r = rem(a, b)', desc: 'Remainder after division; result has the same sign as a.' },
  power: { syntax: 'z = power(x, y)', desc: 'Elementwise x.^y (function form of the .^ operator).' },
  hypot: { syntax: 'c = hypot(a, b)', desc: 'sqrt(a.^2 + b.^2), computed to avoid overflow.' },

  // ---- reductions / statistics ----
  sum: { syntax: 'y = sum(X)  |  y = sum(X, dim)', desc: 'Sum of elements along the first non-singleton dimension (or dim).' },
  prod: { syntax: 'y = prod(X)  |  y = prod(X, dim)', desc: 'Product of elements along a dimension.' },
  mean: { syntax: 'y = mean(X)  |  y = mean(X, dim)', desc: 'Average of elements along a dimension.' },
  median: { syntax: 'y = median(X)', desc: 'Median of elements along a dimension.' },
  std: { syntax: 's = std(X)', desc: 'Sample standard deviation (N-1 denominator) along a dimension.' },
  var: { syntax: 'v = var(X)', desc: 'Sample variance (N-1 denominator) along a dimension.' },
  min: { syntax: 'm = min(X)  |  [m,idx] = min(X)  |  m = min(A,B)', desc: 'Smallest value (with index), or elementwise minimum of two arrays.' },
  max: { syntax: 'm = max(X)  |  [m,idx] = max(X)  |  m = max(A,B)', desc: 'Largest value (with index), or elementwise maximum of two arrays.' },
  range: { syntax: 'r = range(X)', desc: 'max(X) - min(X) along a dimension.' },
  cumsum: { syntax: 'y = cumsum(X)', desc: 'Running (cumulative) sum along a dimension.' },
  cumprod: { syntax: 'y = cumprod(X)', desc: 'Running (cumulative) product along a dimension.' },

  // ---- array ops ----
  find: { syntax: "idx = find(X)  |  idx = find(X,n)  |  idx = find(X,n,'first'|'last')  |  [r,c] = find(X)  |  [r,c,v] = find(X)", desc: 'Indices (or subscripts) of nonzero elements.' },
  any: { syntax: 'tf = any(X)', desc: 'True if any element along a dimension is nonzero.' },
  all: { syntax: 'tf = all(X)', desc: 'True if every element along a dimension is nonzero.' },
  isnan: { syntax: 'tf = isnan(X)', desc: 'Elementwise test for NaN.' },
  isinf: { syntax: 'tf = isinf(X)', desc: 'Elementwise test for +/-Inf.' },
  isfinite: { syntax: 'tf = isfinite(X)', desc: 'Elementwise test for finite (not NaN or Inf) values.' },
  fliplr: { syntax: 'B = fliplr(A)', desc: 'Flip a matrix left to right (reverse column order).' },
  flipud: { syntax: 'B = flipud(A)', desc: 'Flip a matrix up to down (reverse row order).' },
  flip: { syntax: 'B = flip(A)  |  B = flip(A, dim)', desc: 'Flip along a dimension (default: first non-singleton).' },
  sort: { syntax: "B = sort(A)  |  [B,idx] = sort(A)  |  B = sort(A, 'descend')", desc: 'Sort elements along a dimension, ascending by default.' },
  unique: { syntax: 'B = unique(A)', desc: 'Sorted unique values, as a column vector.' },
  repmat: { syntax: 'B = repmat(A, m, n)', desc: 'Tile A into an m-by-n grid of copies.' },
  cat: { syntax: 'C = cat(dim, A, B, ...)', desc: 'Concatenate arrays along dimension 1 (rows) or 2 (columns).' },
  horzcat: { syntax: 'C = horzcat(A, B, ...)', desc: 'Concatenate arrays horizontally (function form of [A B]).' },
  vertcat: { syntax: 'C = vertcat(A, B, ...)', desc: 'Concatenate arrays vertically (function form of [A; B]).' },

  // ---- shape / linear algebra ----
  size: { syntax: 's = size(A)  |  [r,c] = size(A)  |  n = size(A, dim)', desc: 'Size of A along each dimension.' },
  length: { syntax: 'n = length(A)', desc: 'Length of the longest dimension (0 for an empty array).' },
  numel: { syntax: 'n = numel(A)', desc: 'Total number of elements.' },
  ndims: { syntax: 'n = ndims(A)', desc: 'Number of dimensions. Always 2 in this app (N-D arrays are not supported).' },
  isrow: { syntax: 'tf = isrow(A)', desc: 'True if A is a 1xN row vector.' },
  iscolumn: { syntax: 'tf = iscolumn(A)', desc: 'True if A is an Nx1 column vector.' },
  isvector: { syntax: 'tf = isvector(A)', desc: 'True if A is a row or column vector.' },
  isscalar: { syntax: 'tf = isscalar(A)', desc: 'True if A is 1x1.' },
  ismatrix: { syntax: 'tf = ismatrix(A)', desc: 'Always true in this app (everything is 2-D).' },
  isempty: { syntax: 'tf = isempty(A)', desc: 'True if A has zero elements.' },
  reshape: { syntax: 'B = reshape(A, r, c)  |  B = reshape(A, [r c])', desc: 'Reshape A (same elements, column-major order) to r-by-c.' },
  diag: { syntax: 'D = diag(v)  |  v = diag(A)', desc: 'Construct a diagonal matrix from a vector, or extract the diagonal of a matrix.' },
  triu: { syntax: 'U = triu(A)  |  U = triu(A, k)', desc: 'Upper triangular part of A (above diagonal k).' },
  tril: { syntax: 'L = tril(A)  |  L = tril(A, k)', desc: 'Lower triangular part of A (below diagonal k).' },
  transpose: { syntax: "B = transpose(A)", desc: "Non-conjugate transpose (function form of A.')" },
  ctranspose: { syntax: 'B = ctranspose(A)', desc: "Complex-conjugate transpose (function form of A')" },
  det: { syntax: 'd = det(A)', desc: 'Determinant of a square matrix.' },
  trace: { syntax: 't = trace(A)', desc: 'Sum of the diagonal elements of a square matrix.' },
  rank: { syntax: 'r = rank(A)', desc: 'Numerical rank (real matrices only; custom Gaussian-elimination implementation — see README).' },
  inv: { syntax: 'B = inv(A)', desc: 'Matrix inverse of a square matrix.' },
  pinv: { syntax: 'B = pinv(A)', desc: 'Moore-Penrose pseudoinverse.' },
  dot: { syntax: 'd = dot(a, b)', desc: 'Dot product; conjugates the first vector for complex inputs.' },
  cross: { syntax: 'c = cross(a, b)', desc: 'Cross product of two 3-element vectors.' },
  norm: { syntax: "n = norm(x)  |  n = norm(x, p)  |  n = norm(A, 'fro')", desc: 'Vector p-norm (default 2) or matrix norm (1, Inf, Frobenius, or default largest-singular-value).' },
  eig: { syntax: 'e = eig(A)  |  [V,D] = eig(A)', desc: 'Eigenvalues (and eigenvectors) of a square matrix.' },
  svd: { syntax: 's = svd(A)  |  [U,S,V] = svd(A)', desc: 'Singular value decomposition (real matrices only; custom Jacobi-rotation implementation — see README).' },
  lu: { syntax: '[L,U] = lu(A)  |  [L,U,P] = lu(A)', desc: 'LU decomposition of a square matrix.' },
  qr: { syntax: '[Q,R] = qr(A)', desc: 'QR decomposition.' },
  fft: { syntax: 'X = fft(x)', desc: 'Discrete Fourier transform of a vector (any length, not just powers of 2).' },
  ifft: { syntax: 'x = ifft(X)', desc: 'Inverse discrete Fourier transform of a vector.' },
  polyfit: { syntax: 'p = polyfit(x, y, n)', desc: 'Least-squares fit of an n-th degree polynomial (coefficients, highest degree first).' },
  polyval: { syntax: 'y = polyval(p, x)', desc: 'Evaluate a polynomial (coefficients from polyfit) at x.' },
  interp1: { syntax: 'yi = interp1(x, y, xi)', desc: 'Linear interpolation of (x,y) samples at query points xi (NaN outside the range).' },

  // ---- constructors ----
  zeros: { syntax: 'A = zeros(n)  |  A = zeros(r, c)', desc: 'Matrix of zeros.' },
  ones: { syntax: 'A = ones(n)  |  A = ones(r, c)', desc: 'Matrix of ones.' },
  eye: { syntax: 'A = eye(n)  |  A = eye(r, c)', desc: 'Identity matrix (1s on the main diagonal).' },
  rand: { syntax: 'A = rand(n)  |  A = rand(r, c)', desc: 'Uniform random values in [0,1).' },
  randn: { syntax: 'A = randn(n)  |  A = randn(r, c)', desc: 'Standard normal (Gaussian) random values.' },
  randi: { syntax: 'A = randi(imax, r, c)  |  A = randi([lo hi], r, c)', desc: 'Uniform random integers.' },
  linspace: { syntax: 'v = linspace(a, b, n)', desc: 'n linearly spaced points from a to b (default n=100).' },
  logspace: { syntax: 'v = logspace(a, b, n)', desc: 'n logarithmically spaced points from 10^a to 10^b (default n=50).' },
  colon: { syntax: 'v = colon(a, b)  |  v = colon(a, step, b)', desc: 'Function form of the a:b / a:step:b range operator.' },

  // ---- type predicates / conversions ----
  class: { syntax: 's = class(x)', desc: "Class name as a string: 'double', 'char', 'logical', or 'function_handle'." },
  isa: { syntax: 'tf = isa(x, classname)', desc: 'True if x is of the given class.' },
  isnumeric: { syntax: 'tf = isnumeric(x)', desc: 'True unless x is char or logical.' },
  ischar: { syntax: 'tf = ischar(x)', desc: 'True if x is a char array (string).' },
  islogical: { syntax: 'tf = islogical(x)', desc: 'True if x is a logical array.' },
  isreal: { syntax: 'tf = isreal(x)', desc: 'True if x has no complex storage.' },
  iscomplex: { syntax: 'tf = iscomplex(x)', desc: 'True if x has complex storage.' },
  is_function_handle: { syntax: 'tf = is_function_handle(x)', desc: 'True if x is a function handle.' },
  double: { syntax: 'y = double(x)', desc: 'Convert to plain double (strips char/logical tags; char keeps its codes as numbers).' },
  logical: { syntax: 'y = logical(x)', desc: 'Convert to logical (nonzero -> true, zero -> false).' },
  char: { syntax: 's = char(x)', desc: 'Convert numeric codes to a char array (string).' },

  // ---- printing / string formatting ----
  disp: { syntax: 'disp(x)  |  disp hello', desc: 'Display a value without an "x =" header (command syntax works for bareword text: disp hello).' },
  fprintf: { syntax: 'fprintf(fmt, ...)', desc: 'Formatted print to the Command Window (supports \\n, \\t escapes and %d/%f/%s/etc.).' },
  sprintf: { syntax: 's = sprintf(fmt, ...)', desc: 'Formatted print into a string, instead of to the console.' },
  num2str: { syntax: 's = num2str(x)  |  s = num2str(x, precision)', desc: 'Convert a number (or matrix) to text.' },
  mat2str: { syntax: 's = mat2str(A)', desc: "Convert a matrix to a string usable as a MATLAB literal, e.g. '[1 2;3 4]'." },
  strcmp: { syntax: 'tf = strcmp(s1, s2)', desc: 'True if two char arrays are identical.' },
  strcmpi: { syntax: 'tf = strcmpi(s1, s2)', desc: 'Case-insensitive strcmp.' },
  upper: { syntax: 's2 = upper(s)', desc: 'Convert to uppercase.' },
  lower: { syntax: 's2 = lower(s)', desc: 'Convert to lowercase.' },
  strtrim: { syntax: 's2 = strtrim(s)', desc: 'Remove leading/trailing whitespace.' },
  strrep: { syntax: 's2 = strrep(s, old, new)', desc: 'Replace all occurrences of old with new.' },
  strsplit: { syntax: 'strsplit(s, delim)', desc: "Not implemented — its natural result is a cell array, which this app doesn't support. See README." },
  str2double: { syntax: 'x = str2double(s)', desc: "Parse a string as a number (NaN if it doesn't parse)." },
  str2num: { syntax: 'x = str2num(s)', desc: "Evaluate a string as a MATLAB expression (e.g. str2num('[1 2 3]*2'))." },

  // ---- workspace management ----
  who: { syntax: 'who', desc: 'List variable names in the current workspace.' },
  whos: { syntax: 'whos', desc: 'List variables with size and class.' },
  clear: { syntax: "clear  |  clear('x', 'y')  |  clear x y", desc: 'Remove all variables, or specific named ones (command syntax works too: clear x y).' },
  clc: { syntax: 'clc', desc: "Clear the Command Window's output." },
  exist: { syntax: "code = exist('name')", desc: '1 if a variable, 2 if a user function, 5 if a builtin, 0 if not found.' },
  feval: { syntax: "y = feval(fh, ...)  |  y = feval('name', ...)", desc: 'Call a function by handle or by name.' },
  arrayfun: { syntax: 'B = arrayfun(fh, A)', desc: 'Apply a function elementwise to an array (scalar-output form only; no cell/UniformOutput=false).' },
  deal: { syntax: '[a,b,c] = deal(x)  |  [a,b] = deal(x,y)', desc: 'Distribute one value to all outputs, or pass multiple values through positionally.' },

  // ---- plotting ----
  figure: { syntax: 'figure  |  figure(n)', desc: 'Create or switch to a numbered figure.' },
  hold: { syntax: "hold('on')  |  hold('off')  |  hold  |  hold on  |  hold off", desc: 'Keep (or stop keeping) existing plots when adding new ones.' },
  plot: { syntax: "plot(x, y)  |  plot(x, y, 'r--')  |  plot(y)", desc: "Line/marker plot. Inline linespec strings only (e.g. 'r--', 'b-o') — no Name-Value options." },
  scatter: { syntax: 'scatter(x, y)', desc: 'Scatter (markers-only) plot.' },
  bar: { syntax: 'bar(y)  |  bar(x, y)', desc: 'Bar chart.' },
  histogram: { syntax: 'histogram(x)  |  histogram(x, nbins)', desc: 'Histogram with Plotly-native binning.' },
  hist: { syntax: 'hist(y)  |  hist(y, nbins)  |  [n,x] = hist(y)', desc: 'Classic MATLAB histogram: plots with no output args, or returns [counts, centers].' },
  xlabel: { syntax: "xlabel('text')", desc: 'Label the x-axis of the current figure.' },
  ylabel: { syntax: "ylabel('text')", desc: 'Label the y-axis of the current figure.' },
  title: { syntax: "title('text')", desc: 'Title the current figure.' },
  legend: { syntax: "legend('a', 'b', ...)", desc: 'Label existing traces, in the order they were added.' },
  grid: { syntax: "grid('on')  |  grid('off')  |  grid  |  grid on  |  grid off", desc: 'Toggle the axes grid.' },
  xlim: { syntax: 'xlim([xmin xmax])', desc: 'Set the x-axis range.' },
  ylim: { syntax: 'ylim([ymin ymax])', desc: 'Set the y-axis range.' },
  axis: { syntax: "axis('equal')  |  axis('tight')  |  axis([xmin xmax ymin ymax])  |  axis equal  |  axis tight", desc: 'Adjust axis scaling/limits.' },

  // ---- file I/O ----
  readmatrix: { syntax: "A = readmatrix('file.csv')", desc: 'Read a numeric matrix from CSV (basic parser: no quoted fields).' },
  writematrix: { syntax: "writematrix(A, 'file.csv')", desc: 'Write a numeric matrix to CSV and offer it for download.' },
  save: { syntax: "save('name.mat')  |  save('name.mat', 'x', 'y')", desc: 'Write workspace variables to a real (rudimentary) MAT5 .mat file — see README.' },
  load: { syntax: "load('name.mat')", desc: 'Read variables from a MAT5 .mat file into the current workspace.' },
  run: { syntax: "run('script.m')", desc: "Execute a script from the app's open-file list, sharing the caller's workspace." },
}));
