// help-data.js — Curated syntax + description for every builtin, shown by
// the `help` function. Kept as plain data (not generated from the
// registry) so descriptions can be genuinely useful rather than just
// echoing a function name back.

export const HELP_DATA = new Map(Object.entries({
  // ---- constants ----
  pi: { syntax: 'pi', desc: 'Ratio of a circle\'s circumference to its diameter, 3.14159...' },
  e: { syntax: 'e', desc: 'Euler\'s number, 2.71828...' },
  Inf: { syntax: 'Inf', desc: 'Positive infinity.' },
  NaN: { syntax: 'NaN', desc: 'Not-a-Number, the result of undefined operations like 0/0.' },
  eps: { syntax: 'eps', desc: 'Floating-point relative accuracy (smallest distinguishable gap near 1).' },
  i: { syntax: 'i', desc: 'Imaginary unit, sqrt(-1). (also: j)' },
  j: { syntax: 'j', desc: 'Imaginary unit, sqrt(-1). (also: i)' },

  // ---- elementwise math ----
  sin: { syntax: 'y = sin(x)', desc: 'Sine of x (radians), elementwise.' },
  cos: { syntax: 'y = cos(x)', desc: 'Cosine of x (radians), elementwise.' },
  tan: { syntax: 'y = tan(x)', desc: 'Tangent of x (radians), elementwise.' },
  asin: { syntax: 'y = asin(x)', desc: 'Inverse sine (radians). Complex result for |x| > 1.' },
  acos: { syntax: 'y = acos(x)', desc: 'Inverse cosine (radians). Complex result for |x| > 1.' },
  atan: { syntax: 'y = atan(x)', desc: 'Inverse tangent (radians).' },
  atan2: { syntax: 'theta = atan2(y, x)', desc: 'Four-quadrant inverse tangent of y/x (radians).' },
  sinh: { syntax: 'y = sinh(x)', desc: 'Hyperbolic sine, elementwise.' },
  cosh: { syntax: 'y = cosh(x)', desc: 'Hyperbolic cosine, elementwise.' },
  tanh: { syntax: 'y = tanh(x)', desc: 'Hyperbolic tangent, elementwise.' },
  exp: { syntax: 'y = exp(x)', desc: 'e^x, elementwise.' },
  log: { syntax: 'y = log(x)', desc: 'Natural logarithm. Complex result for negative real x.' },
  log10: { syntax: 'y = log10(x)', desc: 'Base-10 logarithm. Complex result for negative real x.' },
  log2: { syntax: 'y = log2(x)', desc: 'Base-2 logarithm. Complex result for negative real x.' },
  sqrt: { syntax: 'y = sqrt(x)', desc: 'Square root. Complex result for negative real x.' },
  abs: { syntax: 'y = abs(x)', desc: 'Absolute value (or magnitude, for complex x).' },
  angle: { syntax: 'theta = angle(z)', desc: 'Phase angle of complex z, in radians. (also: arg)' },
  arg: { syntax: 'theta = arg(z)', desc: 'Phase angle of complex z, in radians. (also: angle)' },
  real: { syntax: 'r = real(z)', desc: 'Real part of z.' },
  imag: { syntax: 'i = imag(z)', desc: 'Imaginary part of z.' },
  conj: { syntax: 'w = conj(z)', desc: 'Complex conjugate.' },
  sign: { syntax: 's = sign(x)', desc: 'Sign of x (-1, 0, or 1); for complex x, x./abs(x).' },
  floor: { syntax: 'y = floor(x)', desc: 'Round toward negative infinity.' },
  ceil: { syntax: 'y = ceil(x)', desc: 'Round toward positive infinity.' },
  round: { syntax: 'y = round(x)', desc: 'Round to nearest integer; halves round away from zero (round(-2.5) is -3).' },
  fix: { syntax: 'y = fix(x)', desc: 'Round toward zero.' },
  mod: { syntax: 'r = mod(a, b)', desc: 'Modulus after division; result has the same sign as b.' },
  rem: { syntax: 'r = rem(a, b)', desc: 'Remainder after division; result has the same sign as a.' },
  power: { syntax: 'z = power(x, y)', desc: 'Elementwise x.^y (function form of the .^ operator).' },
  hypot: { syntax: 'c = hypot(a, b)', desc: 'sqrt(a.^2 + b.^2), computed to avoid overflow.' },

  // ---- reductions / statistics ----
  sum: { syntax: "y = sum(X)  |  sum(X, dim)  |  sum(X, 'all')  |  sum(..., 'omitnan')", desc: "Sum of elements along the first non-singleton dimension (or dim, or over all elements). 'omitnan' skips NaNs. mean, prod, median, std, var, max and min take the same options." },
  prod: { syntax: 'y = prod(X)  |  y = prod(X, dim)', desc: 'Product of elements along a dimension.' },
  mean: { syntax: 'y = mean(X)  |  y = mean(X, dim)', desc: 'Average of elements along a dimension.' },
  median: { syntax: 'y = median(X)', desc: 'Median of elements along a dimension.' },
  std: { syntax: 's = std(X)  |  std(X, w)  |  std(X, w, dim)', desc: 'Standard deviation along a dimension. w = 0 (default) normalizes by N-1, w = 1 by N.' },
  var: { syntax: 'v = var(X)  |  var(X, w)  |  var(X, w, dim)', desc: 'Variance along a dimension. w = 0 (default) normalizes by N-1, w = 1 by N.' },
  min: { syntax: 'm = min(X)  |  [m,idx] = min(X)  |  min(X, [], dim)  |  m = min(A,B)', desc: 'Smallest value (with index), or elementwise minimum of two arrays. NaNs are ignored; complex values compare by magnitude.' },
  max: { syntax: "m = max(X)  |  [m,idx] = max(X)  |  max(X, [], dim|'all')  |  m = max(A,B)", desc: "Largest value (with index), or elementwise maximum of two arrays. NaNs are ignored unless 'includenan' is given; complex values compare by magnitude." },
  range: { syntax: 'r = range(X)', desc: 'max(X) - min(X) along a dimension.' },
  cumsum: { syntax: "y = cumsum(X)  |  cumsum(X, dim)  |  cumsum(..., 'omitnan')", desc: "Running (cumulative) sum along a dimension; 'omitnan' leaves the total unchanged at NaNs." },
  cumprod: { syntax: 'y = cumprod(X)', desc: 'Running (cumulative) product along a dimension.' },

  // ---- array ops ----
  find: { syntax: "idx = find(X)  |  idx = find(X,n)  |  idx = find(X,n,'first'|'last')  |  [r,c] = find(X)  |  [r,c,v] = find(X)", desc: 'Indices (or subscripts) of nonzero elements.' },
  any: { syntax: 'tf = any(X)', desc: 'True if any element along a dimension is nonzero.' },
  all: { syntax: 'tf = all(X)', desc: 'True if every element along a dimension is nonzero.' },
  isnan: { syntax: 'tf = isnan(X)', desc: 'Elementwise test for NaN.' },
  isinf: { syntax: 'tf = isinf(X)', desc: 'Elementwise test for +/-Inf.' },
  isfinite: { syntax: 'tf = isfinite(X)', desc: 'Elementwise test for finite (not NaN or Inf) values.' },
  fliplr: { syntax: 'B = fliplr(A)', desc: 'Flip a matrix left to right (reverse column order).' },
  flipud: { syntax: 'B = flipud(A)', desc: 'Flip a matrix up to down (reverse row order).' },
  flip: { syntax: 'B = flip(A)  |  B = flip(A, dim)', desc: 'Flip along a dimension (default: first non-singleton).' },
  sort: { syntax: "B = sort(A)  |  [B,idx] = sort(A)  |  B = sort(A, 'descend')", desc: 'Sort elements along a dimension, ascending by default.' },
  unique: { syntax: 'C = unique(A)  |  [C, ia, ic] = unique(A)  |  unique(A, \'stable\')', desc: 'Unique values, sorted (or in first-appearance order with \'stable\'). Row vector in, row vector out; otherwise a column. C = A(ia) and A = C(ic).' },
  repmat: { syntax: 'B = repmat(A, m, n)', desc: 'Tile A into an m-by-n grid of copies.' },
  cat: { syntax: 'C = cat(dim, A, B, ...)', desc: 'Concatenate arrays along dimension 1 (rows) or 2 (columns).' },
  horzcat: { syntax: 'C = horzcat(A, B, ...)', desc: 'Concatenate arrays horizontally (function form of [A B]).' },
  vertcat: { syntax: 'C = vertcat(A, B, ...)', desc: 'Concatenate arrays vertically (function form of [A; B]).' },

  // ---- shape / linear algebra ----
  size: { syntax: 's = size(A)  |  [r,c] = size(A)  |  n = size(A, dim)', desc: 'Size of A along each dimension.' },
  length: { syntax: 'n = length(A)', desc: 'Length of the longest dimension (0 for an empty array).' },
  numel: { syntax: 'n = numel(A)', desc: 'Total number of elements.' },
  ndims: { syntax: 'n = ndims(A)', desc: 'Number of dimensions. Always 2 in this app (N-D arrays are not supported).' },
  isrow: { syntax: 'tf = isrow(A)', desc: 'True if A is a 1xN row vector.' },
  iscolumn: { syntax: 'tf = iscolumn(A)', desc: 'True if A is an Nx1 column vector.' },
  isvector: { syntax: 'tf = isvector(A)', desc: 'True if A is a row or column vector.' },
  isscalar: { syntax: 'tf = isscalar(A)', desc: 'True if A is 1x1.' },
  ismatrix: { syntax: 'tf = ismatrix(A)', desc: 'Always true in this app (everything is 2-D).' },
  isempty: { syntax: 'tf = isempty(A)', desc: 'True if A has zero elements.' },
  reshape: { syntax: 'B = reshape(A, r, c)  |  B = reshape(A, [r c])', desc: 'Reshape A (same elements, column-major order) to r-by-c.' },
  diag: { syntax: 'D = diag(v)  |  v = diag(A)', desc: 'Construct a diagonal matrix from a vector, or extract the diagonal of a matrix.' },
  triu: { syntax: 'U = triu(A)  |  U = triu(A, k)', desc: 'Upper triangular part of A (above diagonal k).' },
  tril: { syntax: 'L = tril(A)  |  L = tril(A, k)', desc: 'Lower triangular part of A (below diagonal k).' },
  transpose: { syntax: "B = transpose(A)", desc: "Non-conjugate transpose (function form of A.')" },
  ctranspose: { syntax: 'B = ctranspose(A)', desc: "Complex-conjugate transpose (function form of A')" },
  det: { syntax: 'd = det(A)', desc: 'Determinant of a square matrix.' },
  trace: { syntax: 't = trace(A)', desc: 'Sum of the diagonal elements of a square matrix.' },
  rank: { syntax: 'r = rank(A)', desc: 'Numerical rank (real matrices only; custom Gaussian-elimination implementation — see README).' },
  inv: { syntax: 'B = inv(A)', desc: 'Matrix inverse of a square matrix.' },
  pinv: { syntax: 'B = pinv(A)', desc: 'Moore-Penrose pseudoinverse.' },
  dot: { syntax: 'd = dot(a, b)', desc: 'Dot product; conjugates the first vector for complex inputs.' },
  cross: { syntax: 'c = cross(a, b)', desc: 'Cross product of two 3-element vectors.' },
  norm: { syntax: "n = norm(x)  |  n = norm(x, p)  |  n = norm(A, 'fro')", desc: 'Vector p-norm (default 2) or matrix norm (1, Inf, Frobenius, or default largest-singular-value).' },
  eig: { syntax: 'e = eig(A)  |  [V,D] = eig(A)', desc: 'Eigenvalues (and eigenvectors) of a square matrix.' },
  svd: { syntax: 's = svd(A)  |  [U,S,V] = svd(A)', desc: 'Singular value decomposition (real matrices only; custom Jacobi-rotation implementation — see README).' },
  lu: { syntax: '[L,U] = lu(A)  |  [L,U,P] = lu(A)', desc: 'LU decomposition of a square matrix.' },
  qr: { syntax: '[Q,R] = qr(A)', desc: 'QR decomposition.' },
  fft: { syntax: 'Y = fft(X)  |  fft(X, n)  |  fft(X, n, dim)', desc: 'Discrete Fourier transform of a vector, or of each column of a matrix (any length). n zero-pads or truncates first.' },
  ifft: { syntax: 'X = ifft(Y)  |  ifft(Y, n)  |  ifft(Y, n, dim)', desc: 'Inverse discrete Fourier transform; same arguments as fft.' },
  polyfit: { syntax: 'p = polyfit(x, y, n)', desc: 'Least-squares fit of an n-th degree polynomial (coefficients, highest degree first).' },
  polyval: { syntax: 'y = polyval(p, x)', desc: 'Evaluate a polynomial (coefficients from polyfit) at x.' },
  interp1: { syntax: 'yi = interp1(x, y, xi)', desc: 'Linear interpolation of (x,y) samples at query points xi (NaN outside the range).' },

  // ---- constructors ----
  true: { syntax: 'true  |  true(n)  |  true(m, n)', desc: 'Logical 1 (true), or an array of them.' },
  false: { syntax: 'false  |  false(n)  |  false(m, n)', desc: 'Logical 0 (false), or an array of them.' },
  zeros: { syntax: 'A = zeros(n)  |  A = zeros(r, c)', desc: 'Matrix of zeros.' },
  ones: { syntax: 'A = ones(n)  |  A = ones(r, c)', desc: 'Matrix of ones.' },
  eye: { syntax: 'A = eye(n)  |  A = eye(r, c)', desc: 'Identity matrix (1s on the main diagonal).' },
  rand: { syntax: 'A = rand(n)  |  A = rand(r, c)', desc: 'Uniform random values in [0,1).' },
  randn: { syntax: 'A = randn(n)  |  A = randn(r, c)', desc: 'Standard normal (Gaussian) random values.' },
  randi: { syntax: 'A = randi(imax, r, c)  |  A = randi([lo hi], r, c)', desc: 'Uniform random integers.' },
  linspace: { syntax: 'v = linspace(a, b, n)', desc: 'n linearly spaced points from a to b (default n=100).' },
  logspace: { syntax: 'v = logspace(a, b, n)', desc: 'n logarithmically spaced points from 10^a to 10^b (default n=50).' },
  colon: { syntax: 'v = colon(a, b)  |  v = colon(a, step, b)', desc: 'Function form of the a:b / a:step:b range operator.' },

  // ---- type predicates / conversions ----
  class: { syntax: 's = class(x)', desc: "Class name as a string: 'double', 'char', 'logical', or 'function_handle'." },
  isa: { syntax: 'tf = isa(x, classname)', desc: 'True if x is of the given class.' },
  isnumeric: { syntax: 'tf = isnumeric(x)', desc: 'True unless x is char or logical.' },
  ischar: { syntax: 'tf = ischar(x)', desc: 'True if x is a char array (string).' },
  islogical: { syntax: 'tf = islogical(x)', desc: 'True if x is a logical array.' },
  isreal: { syntax: 'tf = isreal(x)', desc: 'True if x has no complex storage.' },
  iscomplex: { syntax: 'tf = iscomplex(x)', desc: 'True if x has complex storage.' },
  is_function_handle: { syntax: 'tf = is_function_handle(x)', desc: 'True if x is a function handle.' },
  double: { syntax: 'y = double(x)', desc: 'Convert to plain double (strips char/logical tags; char keeps its codes as numbers).' },
  logical: { syntax: 'y = logical(x)', desc: 'Convert to logical (nonzero -> true, zero -> false).' },
  char: { syntax: 's = char(x)', desc: 'Convert numeric codes to a char array (string).' },

  // ---- printing / string formatting ----
  disp: { syntax: 'disp(x)  |  disp hello', desc: 'Display a value without an "x =" header (command syntax works for bareword text: disp hello).' },
  fprintf: { syntax: 'fprintf(fmt, ...)', desc: 'Formatted print to the Command Window (supports \\n, \\t escapes and %d/%f/%s/etc.).' },
  sprintf: { syntax: 's = sprintf(fmt, ...)', desc: 'Formatted print into a string, instead of to the console.' },
  num2str: { syntax: 's = num2str(x)  |  num2str(x, precision)  |  num2str(x, format)', desc: 'Convert a number (or matrix) to text, optionally with a sprintf format applied to each row.' },
  int2str: { syntax: 's = int2str(x)', desc: 'Round to integers and convert to text.' },
  mat2str: { syntax: 's = mat2str(A)', desc: "Convert a matrix to a string usable as a MATLAB literal, e.g. '[1 2;3 4]'." },
  strcmp: { syntax: 'tf = strcmp(s1, s2)', desc: 'True if two char arrays are identical.' },
  strcmpi: { syntax: 'tf = strcmpi(s1, s2)', desc: 'Case-insensitive strcmp.' },
  upper: { syntax: 's2 = upper(s)', desc: 'Convert to uppercase.' },
  lower: { syntax: 's2 = lower(s)', desc: 'Convert to lowercase.' },
  strtrim: { syntax: 's2 = strtrim(s)', desc: 'Remove leading/trailing whitespace.' },
  strrep: { syntax: 's2 = strrep(s, old, new)', desc: 'Replace all occurrences of old with new.' },
  strsplit: { syntax: "C = strsplit(s)  |  strsplit(s, delim)  |  strsplit(s, {d1, d2})", desc: "Split text at a delimiter (default: whitespace) into a 1xN cell array. Consecutive delimiters count as one unless 'CollapseDelimiters' is false." },
  strjoin: { syntax: "s = strjoin(C)  |  strjoin(C, delim)", desc: 'Join a cell array of character vectors with a delimiter (default: a space).' },
  str2double: { syntax: 'x = str2double(s)', desc: "Parse a string as a number (NaN if it doesn't parse)." },
  str2num: { syntax: 'x = str2num(s)', desc: "Evaluate a string as a MATLAB expression (e.g. str2num('[1 2 3]*2'))." },

  // ---- workspace management ----
  who: { syntax: 'who', desc: 'List variable names in the current workspace.' },
  whos: { syntax: 'whos', desc: 'List variables with size and class.' },
  clear: { syntax: "clear  |  clear all  |  clear('x', 'y')  |  clear x y", desc: 'Remove all variables, or specific named ones (command syntax works too: clear x y).' },
  clc: { syntax: 'clc', desc: "Clear the Command Window's output." },
  exist: { syntax: "code = exist('name')", desc: '1 if a variable, 2 if a user function, 5 if a builtin, 0 if not found.' },
  feval: { syntax: "y = feval(fh, ...)  |  y = feval('name', ...)", desc: 'Call a function by handle or by name.' },
  arrayfun: { syntax: "B = arrayfun(fh, A, ...)  |  arrayfun(..., 'UniformOutput', false)", desc: 'Apply a function to each element of one or more same-size arrays. Results must be scalars unless UniformOutput is false, which collects them in a cell array.' },
  cellfun: { syntax: "B = cellfun(fh, C, ...)  |  cellfun(..., 'UniformOutput', false)", desc: "Apply a function (handle or name, e.g. 'isempty') to the contents of each cell. Results must be scalars unless UniformOutput is false." },
  cell: { syntax: 'C = cell(n)  |  cell(m, n)  |  cell([m n])', desc: 'Cell array of empty matrices.' },
  iscell: { syntax: 'tf = iscell(x)', desc: 'True for a cell array.' },
  iscellstr: { syntax: 'tf = iscellstr(x)', desc: 'True for a cell array whose elements are all character vectors.' },
  num2cell: { syntax: 'C = num2cell(A)', desc: 'Put each element of an array in its own cell.' },
  cell2mat: { syntax: 'A = cell2mat(C)', desc: 'Concatenate the contents of a cell array into one matrix.' },
  cellstr: { syntax: 'C = cellstr(chars)', desc: 'Cell column of the rows of a char matrix (trailing blanks removed).' },
  struct: { syntax: "s = struct('f1', v1, 'f2', v2, ...)  |  struct()  |  struct([])", desc: 'Create a struct. A cell-array value with N elements makes an N-element struct array.' },
  fieldnames: { syntax: 'names = fieldnames(s)', desc: 'Field names of a struct, as a cell column.' },
  isfield: { syntax: "tf = isfield(s, 'name')  |  isfield(s, {'a', 'b'})", desc: 'True where s is a struct with the named field(s).' },
  rmfield: { syntax: "s = rmfield(s, 'name')  |  rmfield(s, {'a', 'b'})", desc: 'Remove fields from a struct.' },
  isstruct: { syntax: 'tf = isstruct(x)', desc: 'True for a struct.' },
  getfield: { syntax: "v = getfield(s, 'name')", desc: 'Value of a field (same as s.name).' },
  setfield: { syntax: "s = setfield(s, 'name', v)", desc: 'Copy of s with a field set (same as s.name = v).' },
  struct2cell: { syntax: 'C = struct2cell(s)', desc: 'Field values of a struct as a cell array (one row per field).' },
  numfields: { syntax: 'n = numfields(s)', desc: 'Number of fields in a struct.' },
  error: { syntax: "error(msg)  |  error(fmt, a1, ...)  |  error(id, fmt, a1, ...)  |  error(ME)", desc: 'Throw an error. Caught by try/catch as an MException with .message and .identifier.' },
  warning: { syntax: "warning(msg)  |  warning(id, fmt, ...)  |  warning('off', id)  |  warning('on', id)", desc: 'Print a warning, or turn warnings (all, or one identifier) off and on.' },
  assert: { syntax: "assert(cond)  |  assert(cond, fmt, a1, ...)  |  assert(cond, id, fmt, ...)", desc: "Throw an error unless cond is true (nonzero everywhere)." },
  MException: { syntax: "ME = MException(id, fmt, a1, ...)", desc: 'Create an exception object; throw it with throw(ME).' },
  throw: { syntax: 'throw(ME)', desc: 'Throw an MException.' },
  rethrow: { syntax: 'rethrow(ME)', desc: 'Re-throw a caught MException.' },
  getReport: { syntax: 'msg = getReport(ME)', desc: 'Error message text of an MException.' },
  func2str: { syntax: 's = func2str(fh)', desc: 'Text of a function handle, e.g. \'@(x)x+1\' or \'sin\'.' },
  deal: { syntax: '[a,b,c] = deal(x)  |  [a,b] = deal(x,y)', desc: 'Distribute one value to all outputs, or pass multiple values through positionally.' },

  // ---- plotting ----
  figure: { syntax: "figure  |  figure(n)  |  h = figure('Name', title)", desc: 'Create a figure (lowest unused number) or make figure n current. Returns the figure number.' },
  gcf: { syntax: 'h = gcf', desc: 'Number of the current figure (creates one if none exists).' },
  gca: { syntax: 'ax = gca', desc: 'Handle of the current axes (creates one if none exists).' },
  clf: { syntax: 'clf', desc: 'Clear the current figure (removes all axes).' },
  close: { syntax: 'close  |  close(n)  |  close all', desc: 'Close the current figure, figure n, or every figure.' },
  subplot: { syntax: 'subplot(m, n, p)  |  subplot(mnp)  |  ax = subplot(...)', desc: 'Make (or return to) the axes in cell p of an m-by-n grid; p may list several cells to span them.' },
  sgtitle: { syntax: "sgtitle('text')", desc: 'Title over all the subplots of the current figure.' },
  hold: { syntax: 'hold on  |  hold off  |  hold', desc: 'Keep (or stop keeping) existing plots in the current axes when adding new ones; new lines continue the color order.' },
  ishold: { syntax: 'tf = ishold', desc: 'True if hold is on for the current axes.' },
  plot: { syntax: "h = plot(y)  |  plot(x, y)  |  plot(x, y, 'r--o')  |  plot(x1, y1, x2, y2, ...)  |  plot(..., 'LineWidth', 2)", desc: "Line plot. A matrix gives one line per column. Line specs ('r--o') and Name,Value options: Color, LineWidth, LineStyle, Marker, MarkerSize, MarkerFaceColor, MarkerEdgeColor, DisplayName." },
  semilogx: { syntax: 'semilogx(x, y, ...)', desc: 'Like plot, with a logarithmic x axis.' },
  semilogy: { syntax: 'semilogy(x, y, ...)', desc: 'Like plot, with a logarithmic y axis.' },
  loglog: { syntax: 'loglog(x, y, ...)', desc: 'Like plot, with logarithmic x and y axes.' },
  stairs: { syntax: 'stairs(x, y, ...)', desc: 'Staircase plot.' },
  stem: { syntax: "stem(x, y)  |  stem(..., 'filled')", desc: 'Stem plot: a line from zero to each point, with a marker.' },
  errorbar: { syntax: 'errorbar(y, err)  |  errorbar(x, y, err)  |  errorbar(x, y, neg, pos)', desc: 'Line plot with vertical error bars.' },
  polarplot: { syntax: "polarplot(theta, rho, ...)", desc: 'Line plot in polar coordinates (theta in radians).' },
  scatter: { syntax: "scatter(x, y)  |  scatter(x, y, sz, c)  |  scatter(..., 'filled')", desc: 'Scatter plot; sz is marker area in points^2, c a color or one value per point.' },
  bar: { syntax: "bar(y)  |  bar(x, y)  |  bar(Y, 'stacked')  |  bar(..., width)", desc: 'Bar chart; a matrix gives grouped (or stacked) bars. Options: FaceColor, EdgeColor, BarWidth, DisplayName.' },
  barh: { syntax: 'barh(y)  |  barh(x, y)', desc: 'Horizontal bar chart.' },
  histogram: { syntax: "histogram(x)  |  histogram(x, nbins)  |  histogram(x, edges)  |  histogram(..., 'Normalization', 'pdf')", desc: "Histogram. Options: NumBins, BinEdges, BinWidth, Normalization ('count', 'probability', 'pdf', 'countdensity', 'cumcount', 'cdf'), FaceColor, FaceAlpha." },
  hist: { syntax: 'hist(y)  |  hist(y, nbins)  |  [n,x] = hist(y)', desc: 'Classic MATLAB histogram: plots with no output args, or returns [counts, centers].' },
  area: { syntax: 'area(y)  |  area(x, Y)', desc: 'Filled area plot; a matrix stacks one area per column.' },
  fill: { syntax: 'fill(x, y, c)', desc: 'Filled polygon with color c.' },
  pie: { syntax: "pie(x)  |  pie(x, labels)", desc: 'Pie chart, optionally with a cell array of slice labels.' },
  text: { syntax: "text(x, y, 'str')  |  text(..., 'FontSize', 12, 'HorizontalAlignment', 'center')", desc: 'Place text at data coordinates in the current axes.' },
  xlabel: { syntax: "xlabel('text')", desc: "Label the x axis of the current axes (TeX such as 'x^2' or '\\alpha' is supported)." },
  ylabel: { syntax: "ylabel('text')", desc: 'Label the y axis of the current axes.' },
  title: { syntax: "title('text')  |  title('text', 'subtitle')", desc: 'Title the current axes.' },
  legend: { syntax: "legend('a', 'b', ...)  |  legend(..., 'Location', 'southwest')  |  legend show|off", desc: 'Show a legend; labels apply to plotted objects in order (DisplayName is used otherwise).' },
  grid: { syntax: 'grid on  |  grid off  |  grid minor  |  grid', desc: 'Show or hide grid lines in the current axes.' },
  box: { syntax: 'box on  |  box off', desc: 'Draw (or not) the axes outline on all four sides.' },
  xlim: { syntax: 'xlim([xmin xmax])  |  xlim auto  |  lim = xlim', desc: 'Set, reset or query the x-axis limits.' },
  ylim: { syntax: 'ylim([ymin ymax])  |  ylim auto  |  lim = ylim', desc: 'Set, reset or query the y-axis limits.' },
  xticks: { syntax: 'xticks(values)  |  xticks auto', desc: 'Positions of the x-axis tick marks.' },
  yticks: { syntax: 'yticks(values)  |  yticks auto', desc: 'Positions of the y-axis tick marks.' },
  xticklabels: { syntax: "xticklabels({'a', 'b', ...})", desc: 'Text of the x-axis tick labels.' },
  yticklabels: { syntax: "yticklabels({'a', 'b', ...})", desc: 'Text of the y-axis tick labels.' },
  set: { syntax: "set(h, 'Name', value, ...)", desc: 'Change graphics properties. Lines: Color, LineWidth, LineStyle, Marker, MarkerSize, MarkerFaceColor, MarkerEdgeColor, DisplayName, XData, YData. Axes: XLim, YLim, XScale, YScale, XGrid, YGrid, Box. Figures: Name.' },
  get: { syntax: "v = get(h, 'Name')  |  s = get(h)", desc: 'Read a graphics property, or all supported properties as a struct.' },
  isgraphics: { syntax: 'tf = isgraphics(h)', desc: 'True for elements that are valid graphics handles.' },
  axis: { syntax: 'axis([xmin xmax ymin ymax])  |  axis equal|image|tight|auto|normal|off|on|ij|xy  |  v = axis', desc: "Set or query axis limits and scaling. ('square' is accepted but has no effect.)" },

  // ---- file I/O ----
  readmatrix: { syntax: "A = readmatrix('file.csv')", desc: 'Read a numeric matrix from CSV (basic parser: no quoted fields).' },
  writematrix: { syntax: "writematrix(A, 'file.csv')", desc: 'Write a numeric matrix to a CSV file in the Files panel (download it from there).' },
  save: { syntax: "save('name.mat')  |  save('name.mat', 'x', 'y')", desc: 'Write numeric/char/logical workspace variables to a real (rudimentary) MAT5 .mat file in the Files panel — see README.' },
  load: { syntax: "load('name.mat')", desc: 'Read variables from a MAT5 .mat file into the current workspace.' },
  run: { syntax: "run('script.m')", desc: "Execute a script from the Files panel in the caller's workspace. For a function file, calls its function with no inputs." },

  // ---- timing & display ----
  tic: { syntax: 'tic  |  t = tic', desc: 'Start a stopwatch timer (optionally returning its id for toc(t)).' },
  toc: { syntax: 'toc  |  s = toc  |  toc(t)', desc: 'Seconds elapsed since tic (or since the tic that returned t); prints them if no output is requested.' },
  format: { syntax: 'format short  |  format long  |  format', desc: 'Choose how numbers display: 4 decimals (short, the default) or about 16 significant digits (long).' },

  // ---- comparison, sets, operator functions ----
  isequal: { syntax: 'tf = isequal(A, B, ...)', desc: "True if all inputs have the same size and values (numeric class is ignored; NaN ~= NaN). Works on cells and structs too." },
  isequaln: { syntax: 'tf = isequaln(A, B, ...)', desc: 'Like isequal, but NaN values compare equal.' },
  ismember: { syntax: '[tf, loc] = ismember(A, S)', desc: 'Which elements of A occur in S, and the lowest index where each does. Works on numbers and on cell arrays of strings.' },
  xor: { syntax: 'c = xor(a, b)', desc: 'Element-wise exclusive OR.' },
  not: { syntax: 'b = not(a)', desc: 'Element-wise logical NOT (same as ~a).' },
  and: { syntax: 'c = and(a, b)', desc: 'Element-wise logical AND (same as a & b).' },
  or: { syntax: 'c = or(a, b)', desc: 'Element-wise logical OR (same as a | b).' },
  plus: { syntax: 'c = plus(a, b)', desc: 'a + b, as a function (handy as @plus).' },
  minus: { syntax: 'c = minus(a, b)', desc: 'a - b, as a function.' },
  times: { syntax: 'c = times(a, b)', desc: 'a .* b, as a function.' },
  rdivide: { syntax: 'c = rdivide(a, b)', desc: 'a ./ b, as a function.' },
  ldivide: { syntax: 'c = ldivide(a, b)', desc: 'a .\\ b, as a function.' },
  mtimes: { syntax: 'c = mtimes(A, B)', desc: 'A * B (matrix product), as a function.' },
  mrdivide: { syntax: 'X = mrdivide(B, A)', desc: 'B / A, as a function.' },
  mldivide: { syntax: 'X = mldivide(A, B)', desc: 'A \\ B, as a function.' },
  mpower: { syntax: 'C = mpower(A, b)', desc: 'A ^ b (matrix power), as a function.' },
  eq: { syntax: 'tf = eq(a, b)', desc: 'a == b, as a function.' },
  ne: { syntax: 'tf = ne(a, b)', desc: 'a ~= b, as a function.' },
  lt: { syntax: 'tf = lt(a, b)', desc: 'a < b, as a function.' },
  gt: { syntax: 'tf = gt(a, b)', desc: 'a > b, as a function.' },
  le: { syntax: 'tf = le(a, b)', desc: 'a <= b, as a function.' },
  ge: { syntax: 'tf = ge(a, b)', desc: 'a >= b, as a function.' },
  uminus: { syntax: 'b = uminus(a)', desc: '-a, as a function.' },
  uplus: { syntax: 'b = uplus(a)', desc: '+a, as a function.' },
  bsxfun: { syntax: 'C = bsxfun(fh, A, B)', desc: 'Apply a two-input element-wise function with implicit expansion (operators already expand, e.g. A - mean(A)).' },

  // ---- more numerics ----
  magic: { syntax: 'M = magic(n)', desc: 'n-by-n magic square (rows, columns and diagonals have equal sums), same layout as MATLAB.' },
  meshgrid: { syntax: '[X, Y] = meshgrid(x, y)  |  meshgrid(x)', desc: 'Grid coordinates: X repeats x along each row, Y repeats y down each column.' },
  ndgrid: { syntax: '[X, Y] = ndgrid(x, y)', desc: 'Like meshgrid, but X varies down the rows and Y across the columns.' },
  diff: { syntax: 'D = diff(X)  |  diff(X, n)  |  diff(X, n, dim)', desc: 'Differences between adjacent elements (n-th order, along dim).' },
  trapz: { syntax: 'Q = trapz(Y)  |  trapz(X, Y)  |  trapz(..., dim)', desc: 'Trapezoidal-rule integral of Y (unit spacing, spacing X, or points X).' },
  cumtrapz: { syntax: 'Q = cumtrapz(Y)  |  cumtrapz(X, Y)  |  cumtrapz(..., dim)', desc: 'Running trapezoidal-rule integral.' },
  circshift: { syntax: 'B = circshift(A, k)  |  circshift(A, [r c])  |  circshift(A, k, dim)', desc: 'Rotate elements circularly by k positions.' },
  kron: { syntax: 'K = kron(A, B)', desc: 'Kronecker tensor product.' },
  nnz: { syntax: 'n = nnz(X)', desc: 'Number of nonzero elements.' },
  sub2ind: { syntax: 'ind = sub2ind([m n], r, c)', desc: 'Convert row/column subscripts to linear indices.' },
  ind2sub: { syntax: '[r, c] = ind2sub([m n], ind)', desc: 'Convert linear indices to row/column subscripts.' },
  mode: { syntax: '[M, F] = mode(X)  |  mode(X, dim)', desc: 'Most frequent value (smallest on ties; NaNs ignored) and how often it occurs.' },
  factorial: { syntax: 'f = factorial(n)', desc: 'n! element-wise (Inf above 170).' },
  nchoosek: { syntax: 'c = nchoosek(n, k)  |  C = nchoosek(v, k)', desc: 'Binomial coefficient, or all k-element combinations of the vector v (one per row).' },
  primes: { syntax: 'p = primes(n)', desc: 'Row vector of the primes up to n.' },
  isprime: { syntax: 'tf = isprime(X)', desc: 'True for elements that are prime.' },
  gcd: { syntax: 'g = gcd(a, b)', desc: 'Greatest common divisor, element-wise.' },
  lcm: { syntax: 'l = lcm(a, b)', desc: 'Least common multiple, element-wise.' },
  roots: { syntax: 'r = roots(p)', desc: 'Roots of the polynomial with coefficients p (highest power first), via companion-matrix eigenvalues.' },
  conv: { syntax: "w = conv(u, v)  |  conv(u, v, 'same'|'valid')", desc: 'Convolution, which is also polynomial multiplication.' },
  deconv: { syntax: '[q, r] = deconv(y, a)', desc: 'Polynomial division: y = conv(a, q) + r.' },
  filter: { syntax: 'y = filter(b, a, x)  |  filter(b, a, x, [], dim)', desc: 'Apply the digital filter b(z)/a(z) to x (FIR when a = 1).' },

  // ---- more strings ----
  strcat: { syntax: 's = strcat(s1, s2, ...)', desc: 'Concatenate text. Trailing blanks of char inputs are removed; with a cell input the result is a cell array.' },
  strfind: { syntax: 'k = strfind(str, pattern)', desc: 'Start indices of every occurrence of pattern (overlaps included).' },
  contains: { syntax: "tf = contains(str, pattern)  |  contains(..., 'IgnoreCase', true)", desc: 'True if str contains pattern (or any of a cell array of patterns). str may be a cell array.' },
  startsWith: { syntax: "tf = startsWith(str, pattern)  |  startsWith(..., 'IgnoreCase', true)", desc: 'True if str starts with pattern.' },
  endsWith: { syntax: "tf = endsWith(str, pattern)  |  endsWith(..., 'IgnoreCase', true)", desc: 'True if str ends with pattern.' },
  regexp: { syntax: "[tok, mat] = regexp(str, expr, 'tokens', 'match')  |  regexp(..., 'once')", desc: "Regular-expression matching. Outputs: 'start', 'end', 'tokenExtents', 'match', 'tokens', 'names', 'split' (in that order by default, or as selected)." },
  regexpi: { syntax: 'regexpi(str, expr, ...)', desc: 'Case-insensitive regexp.' },
  regexprep: { syntax: "s = regexprep(str, expr, replace)  |  regexprep(..., 'once'|'ignorecase')", desc: 'Replace regular-expression matches; $1, $2, ... insert tokens and $0 the whole match.' },
}));
