// help-data.js — Curated syntax + description for every builtin, shown by
// the `help` function. Kept as plain data (not generated from the
// registry) so descriptions can be genuinely useful rather than just
// echoing a function name back.

export const HELP_DATA = new Map(Object.entries({
  // ---- constants ----
  pi: { syntax: 'pi', desc: 'Ratio of a circle\'s circumference to its diameter, 3.14159...' },
  e: { syntax: 'e', desc: 'Euler\'s number, 2.71828...' },
  Inf: { syntax: 'Inf  |  Inf(n)  |  Inf(m, n)', desc: 'Positive infinity, or an array of it.' },
  NaN: { syntax: 'NaN  |  NaN(n)  |  NaN(m, n)', desc: 'Not-a-Number, the result of undefined operations like 0/0; NaN(m, n) is an array of NaNs.' },
  inf: { syntax: 'inf  |  inf(m, n)', desc: 'Same as Inf.' },
  nan: { syntax: 'nan  |  nan(m, n)', desc: 'Same as NaN.' },
  eps: { syntax: 'eps', desc: 'Floating-point relative accuracy (smallest distinguishable gap near 1).' },
  i: { syntax: 'i', desc: 'Imaginary unit, sqrt(-1). (also: j)' },
  j: { syntax: 'j', desc: 'Imaginary unit, sqrt(-1). (also: i)' },

  // ---- elementwise math ----
  sin: { syntax: 'y = sin(x)', desc: 'Sine of x (radians), elementwise.' },
  cos: { syntax: 'y = cos(x)', desc: 'Cosine of x (radians), elementwise.' },
  tan: { syntax: 'y = tan(x)', desc: 'Tangent of x (radians), elementwise.' },
  asin: { syntax: 'y = asin(x)', desc: 'Inverse sine (radians). Complex result for |x| > 1.' },
  acos: { syntax: 'y = acos(x)', desc: 'Inverse cosine (radians). Complex result for |x| > 1.' },
  atan: { syntax: 'y = atan(x)', desc: 'Inverse tangent (radians).' },
  atan2: { syntax: 'theta = atan2(y, x)', desc: 'Four-quadrant inverse tangent of y/x (radians).' },
  sinh: { syntax: 'y = sinh(x)', desc: 'Hyperbolic sine, elementwise.' },
  cosh: { syntax: 'y = cosh(x)', desc: 'Hyperbolic cosine, elementwise.' },
  tanh: { syntax: 'y = tanh(x)', desc: 'Hyperbolic tangent, elementwise.' },
  exp: { syntax: 'y = exp(x)', desc: 'e^x, elementwise.' },
  log: { syntax: 'y = log(x)', desc: 'Natural logarithm. Complex result for negative real x.' },
  log10: { syntax: 'y = log10(x)', desc: 'Base-10 logarithm. Complex result for negative real x.' },
  log2: { syntax: 'y = log2(x)', desc: 'Base-2 logarithm. Complex result for negative real x.' },
  sqrt: { syntax: 'y = sqrt(x)', desc: 'Square root. Complex result for negative real x.' },
  abs: { syntax: 'y = abs(x)', desc: 'Absolute value (or magnitude, for complex x).' },
  angle: { syntax: 'theta = angle(z)', desc: 'Phase angle of complex z, in radians. (also: arg)' },
  arg: { syntax: 'theta = arg(z)', desc: 'Phase angle of complex z, in radians. (also: angle)' },
  real: { syntax: 'r = real(z)', desc: 'Real part of z.' },
  imag: { syntax: 'i = imag(z)', desc: 'Imaginary part of z.' },
  conj: { syntax: 'w = conj(z)', desc: 'Complex conjugate.' },
  sign: { syntax: 's = sign(x)', desc: 'Sign of x (-1, 0, or 1); for complex x, x./abs(x).' },
  floor: { syntax: 'y = floor(x)', desc: 'Round toward negative infinity.' },
  ceil: { syntax: 'y = ceil(x)', desc: 'Round toward positive infinity.' },
  round: { syntax: 'y = round(x)', desc: 'Round to nearest integer; halves round away from zero (round(-2.5) is -3).' },
  fix: { syntax: 'y = fix(x)', desc: 'Round toward zero.' },
  mod: { syntax: 'r = mod(a, b)', desc: 'Modulus after division; result has the same sign as b.' },
  rem: { syntax: 'r = rem(a, b)', desc: 'Remainder after division; result has the same sign as a.' },
  power: { syntax: 'z = power(x, y)', desc: 'Elementwise x.^y (function form of the .^ operator).' },
  hypot: { syntax: 'c = hypot(a, b)', desc: 'sqrt(a.^2 + b.^2), computed to avoid overflow.' },

  // ---- reductions / statistics ----
  sum: { syntax: "y = sum(X)  |  sum(X, dim)  |  sum(X, 'all')  |  sum(..., 'omitnan')", desc: "Sum of elements along the first non-singleton dimension (or dim, or over all elements). 'omitnan' skips NaNs. mean, prod, median, std, var, max and min take the same options." },
  prod: { syntax: 'y = prod(X)  |  y = prod(X, dim)', desc: 'Product of elements along a dimension.' },
  mean: { syntax: 'y = mean(X)  |  y = mean(X, dim)', desc: 'Average of elements along a dimension.' },
  median: { syntax: 'y = median(X)', desc: 'Median of elements along a dimension.' },
  std: { syntax: 's = std(X)  |  std(X, w)  |  std(X, w, dim)', desc: 'Standard deviation along a dimension. w = 0 (default) normalizes by N-1, w = 1 by N.' },
  var: { syntax: 'v = var(X)  |  var(X, w)  |  var(X, w, dim)', desc: 'Variance along a dimension. w = 0 (default) normalizes by N-1, w = 1 by N.' },
  min: { syntax: 'm = min(X)  |  [m,idx] = min(X)  |  min(X, [], dim)  |  m = min(A,B)', desc: 'Smallest value (with index), or elementwise minimum of two arrays. NaNs are ignored; complex values compare by magnitude.' },
  max: { syntax: "m = max(X)  |  [m,idx] = max(X)  |  max(X, [], dim|'all')  |  m = max(A,B)", desc: "Largest value (with index), or elementwise maximum of two arrays. NaNs are ignored unless 'includenan' is given; complex values compare by magnitude." },
  range: { syntax: 'r = range(X)', desc: 'max(X) - min(X) along a dimension.' },
  cumsum: { syntax: "y = cumsum(X)  |  cumsum(X, dim)  |  cumsum(..., 'omitnan')", desc: "Running (cumulative) sum along a dimension; 'omitnan' leaves the total unchanged at NaNs." },
  cumprod: { syntax: 'y = cumprod(X)', desc: 'Running (cumulative) product along a dimension.' },

  // ---- array ops ----
  find: { syntax: "idx = find(X)  |  idx = find(X,n)  |  idx = find(X,n,'first'|'last')  |  [r,c] = find(X)  |  [r,c,v] = find(X)", desc: 'Indices (or subscripts) of nonzero elements.' },
  any: { syntax: "tf = any(X)  |  any(X, dim)  |  any(X, 'all')", desc: 'True if any element along a dimension (default: first non-singleton) is nonzero.' },
  all: { syntax: "tf = all(X)  |  all(X, dim)  |  all(X, 'all')", desc: 'True if every element along a dimension (default: first non-singleton) is nonzero.' },
  isnan: { syntax: 'tf = isnan(X)', desc: 'Elementwise test for NaN.' },
  isinf: { syntax: 'tf = isinf(X)', desc: 'Elementwise test for +/-Inf.' },
  isfinite: { syntax: 'tf = isfinite(X)', desc: 'Elementwise test for finite (not NaN or Inf) values.' },
  fliplr: { syntax: 'B = fliplr(A)', desc: 'Flip a matrix left to right (reverse column order).' },
  flipud: { syntax: 'B = flipud(A)', desc: 'Flip a matrix up to down (reverse row order).' },
  flip: { syntax: 'B = flip(A)  |  B = flip(A, dim)', desc: 'Flip along a dimension (default: first non-singleton).' },
  sort: { syntax: "B = sort(A)  |  [B,idx] = sort(A)  |  B = sort(A, dim)  |  B = sort(A, 'descend')", desc: 'Sort elements along a dimension, ascending by default.' },
  unique: { syntax: 'C = unique(A)  |  [C, ia, ic] = unique(A)  |  unique(A, \'stable\')', desc: 'Unique values, sorted (or in first-appearance order with \'stable\'). Row vector in, row vector out; otherwise a column. C = A(ia) and A = C(ic).' },
  repmat: { syntax: 'B = repmat(A, n)  |  B = repmat(A, m, n)  |  B = repmat(A, [m n])', desc: 'Tile A into an m-by-n grid of copies (n alone means n-by-n).' },
  cat: { syntax: 'C = cat(dim, A, B, ...)', desc: 'Concatenate arrays along dimension 1 (rows) or 2 (columns). Along dimension 3 or more only one non-empty array is allowed, since N-D arrays are not supported.' },
  horzcat: { syntax: 'C = horzcat(A, B, ...)', desc: 'Concatenate arrays horizontally (function form of [A B]).' },
  vertcat: { syntax: 'C = vertcat(A, B, ...)', desc: 'Concatenate arrays vertically (function form of [A; B]).' },

  // ---- shape / linear algebra ----
  size: { syntax: 's = size(A)  |  [r, c, ...] = size(A)  |  n = size(A, dim)  |  s = size(A, [d1 d2])', desc: 'Size of A along each dimension; dimensions past the second have size 1.' },
  length: { syntax: 'n = length(A)', desc: 'Length of the longest dimension (0 for an empty array).' },
  numel: { syntax: 'n = numel(A)', desc: 'Total number of elements.' },
  expm: { syntax: 'E = expm(A)', desc: 'Matrix exponential (Pade approximation with scaling and squaring).' },
  sqrtm: { syntax: 'X = sqrtm(A)', desc: 'Principal matrix square root, X*X = A (complex when A has negative eigenvalues).' },
  chol: { syntax: "R = chol(A)  |  L = chol(A, 'lower')  |  [R, p] = chol(A)", desc: "Cholesky factorization of a symmetric positive definite matrix: R'*R = A (upper triangle of A is used). With two outputs, p > 0 marks failure instead of an error." },
  cond: { syntax: 'c = cond(A)  |  c = cond(A, p)', desc: 'Condition number: ratio of the largest to smallest singular value, or norm(A, p)*norm(inv(A), p) for p = 1, Inf, or fro.' },
  null: { syntax: 'Z = null(A)', desc: 'Orthonormal basis for the null space of A (A*Z is zero). For a null space of more than one dimension the basis may differ from MATLAB\'s by a rotation.' },
  orth: { syntax: 'Q = orth(A)', desc: 'Orthonormal basis for the range of A.' },
  ndims: { syntax: 'n = ndims(A)', desc: 'Number of dimensions. Always 2 in this app (N-D arrays are not supported).' },
  permute: { syntax: 'B = permute(A, order)', desc: 'Rearrange the dimensions of A; permute(A, [2 1]) is a transpose (without conjugation). Dimensions past the second have size 1, and the result must stay 2-D.' },
  ipermute: { syntax: 'A = ipermute(B, order)', desc: 'Inverse of permute: ipermute(permute(A, order), order) is A.' },
  squeeze: { syntax: 'B = squeeze(A)', desc: 'Remove singleton dimensions. Every array here is 2-D, so this returns A unchanged.' },
  isrow: { syntax: 'tf = isrow(A)', desc: 'True if A is a 1xN row vector.' },
  iscolumn: { syntax: 'tf = iscolumn(A)', desc: 'True if A is an Nx1 column vector.' },
  isvector: { syntax: 'tf = isvector(A)', desc: 'True if A is a row or column vector.' },
  isscalar: { syntax: 'tf = isscalar(A)', desc: 'True if A is 1x1.' },
  ismatrix: { syntax: 'tf = ismatrix(A)', desc: 'Always true in this app (everything is 2-D).' },
  isempty: { syntax: 'tf = isempty(A)', desc: 'True if A has zero elements.' },
  reshape: { syntax: 'B = reshape(A, r, c)  |  B = reshape(A, [r c])  |  B = reshape(A, [], c)', desc: 'Reshape A (same elements, column-major order) to r-by-c; one size may be [] to work it out. Sizes past the second must be 1.' },
  diag: { syntax: 'D = diag(v)  |  v = diag(A)', desc: 'Construct a diagonal matrix from a vector, or extract the diagonal of a matrix.' },
  triu: { syntax: 'U = triu(A)  |  U = triu(A, k)', desc: 'Upper triangular part of A (above diagonal k).' },
  tril: { syntax: 'L = tril(A)  |  L = tril(A, k)', desc: 'Lower triangular part of A (below diagonal k).' },
  transpose: { syntax: "B = transpose(A)", desc: "Non-conjugate transpose (function form of A.')" },
  ctranspose: { syntax: 'B = ctranspose(A)', desc: "Complex-conjugate transpose (function form of A')" },
  det: { syntax: 'd = det(A)', desc: 'Determinant of a square matrix.' },
  trace: { syntax: 't = trace(A)', desc: 'Sum of the diagonal elements of a square matrix.' },
  rank: { syntax: 'r = rank(A)', desc: 'Numerical rank (real matrices only; custom Gaussian-elimination implementation — see README).' },
  inv: { syntax: 'B = inv(A)', desc: 'Matrix inverse of a square matrix.' },
  pinv: { syntax: 'B = pinv(A)', desc: 'Moore-Penrose pseudoinverse.' },
  dot: { syntax: 'd = dot(a, b)', desc: 'Dot product; conjugates the first vector for complex inputs.' },
  cross: { syntax: 'c = cross(a, b)', desc: 'Cross product of two 3-element vectors.' },
  norm: { syntax: "n = norm(x)  |  n = norm(x, p)  |  n = norm(A, 'fro')", desc: 'Vector p-norm (default 2) or matrix norm (1, Inf, Frobenius, or default largest-singular-value).' },
  eig: { syntax: 'e = eig(A)  |  [V,D] = eig(A)', desc: 'Eigenvalues (and eigenvectors) of a square matrix.' },
  svd: { syntax: 's = svd(A)  |  [U,S,V] = svd(A)', desc: 'Singular value decomposition (real matrices only; custom Jacobi-rotation implementation — see README).' },
  lu: { syntax: '[L,U] = lu(A)  |  [L,U,P] = lu(A)', desc: 'LU decomposition of a square matrix.' },
  qr: { syntax: '[Q,R] = qr(A)', desc: 'QR decomposition.' },
  fft: { syntax: 'Y = fft(X)  |  fft(X, n)  |  fft(X, n, dim)', desc: 'Discrete Fourier transform of a vector, or of each column of a matrix (any length). n zero-pads or truncates first.' },
  ifft: { syntax: 'X = ifft(Y)  |  ifft(Y, n)  |  ifft(Y, n, dim)', desc: 'Inverse discrete Fourier transform; same arguments as fft.' },
  polyfit: { syntax: 'p = polyfit(x, y, n)', desc: 'Least-squares fit of an n-th degree polynomial (coefficients, highest degree first).' },
  polyval: { syntax: 'y = polyval(p, x)', desc: 'Evaluate a polynomial (coefficients from polyfit) at x.' },
  interp1: { syntax: "vq = interp1(x, v, xq)  |  interp1(v, xq)  |  interp1(..., method)  |  interp1(..., method, 'extrap')  |  interp1(..., method, extrapval)", desc: "1-D interpolation. Methods: 'linear' (default), 'nearest', 'next', 'previous', 'pchip' (or 'cubic'), 'spline'. Outside the data the result is NaN, except for 'pchip' and 'spline', which extrapolate. A matrix v gives one column per series." },
  interp2: { syntax: "Vq = interp2(X, Y, V, Xq, Yq)  |  interp2(V, Xq, Yq)  |  interp2(..., method)  |  interp2(..., method, extrapval)", desc: "2-D interpolation on a grid (X, Y as vectors or meshgrid matrices). Methods: 'linear' (default), 'nearest', 'cubic', 'spline'. A row Xq and a column Yq query a grid. NaN outside the grid unless extrapval is given." },
  spline: { syntax: 'pp = spline(x, y)  |  yq = spline(x, y, xq)', desc: 'Cubic spline with not-a-knot end conditions (or clamped: if y has two more values than x, the first and last are the end slopes). Extrapolates outside x. Rows of a matrix y are separate curves.' },
  pchip: { syntax: 'pp = pchip(x, y)  |  yq = pchip(x, y, xq)', desc: 'Shape-preserving piecewise cubic Hermite interpolation: no overshoot, monotone where the data are.' },
  ppval: { syntax: 'v = ppval(pp, xq)', desc: 'Evaluate a piecewise polynomial (from spline, pchip or mkpp) at xq.' },
  mkpp: { syntax: 'pp = mkpp(breaks, coefs)  |  pp = mkpp(breaks, coefs, d)', desc: 'Make a piecewise polynomial: row i of coefs holds the coefficients (highest power first) of the piece starting at breaks(i).' },
  unmkpp: { syntax: '[breaks, coefs, pieces, order, dim] = unmkpp(pp)', desc: 'The parts of a piecewise polynomial.' },
  polyder: { syntax: 'k = polyder(p)  |  k = polyder(a, b)  |  [q, d] = polyder(b, a)', desc: 'Derivative of a polynomial, of the product a*b, or of the quotient b/a (as q/d).' },
  polyint: { syntax: 'q = polyint(p)  |  q = polyint(p, k)', desc: 'Integral of a polynomial, with constant of integration k (default 0).' },

  // ---- ODEs ----
  ode45: { syntax: '[t, y] = ode45(odefun, tspan, y0)  |  [t, y] = ode45(..., options)  |  sol = ode45(...)  |  ode45(...)', desc: "Solve y' = f(t, y) (non-stiff; Dormand-Prince 4(5), MATLAB's method and step control). odefun(t, y) returns a column vector. With tspan = [t0 tf] each step is refined into 4 output points; with more times, output is at exactly those times. One output gives a solution structure for deval; no outputs plots the solution." },
  ode23: { syntax: '[t, y] = ode23(odefun, tspan, y0)  |  [t, y] = ode23(..., options)  |  sol = ode23(...)', desc: 'Like ode45 with the lower-order Bogacki-Shampine 2(3) method: cheaper per step, better for crude tolerances or mildly stiff problems.' },
  ode23s: { syntax: '[t, y] = ode23s(odefun, tspan, y0)  |  [t, y] = ode23s(..., options)', desc: "Stiff solver: MATLAB's modified Rosenbrock 2(3) method, with a finite-difference Jacobian unless odeset's Jacobian option gives one (a matrix or a function of (t, y))." },
  ode15s: { syntax: '[t, y] = ode15s(odefun, tspan, y0)  |  [t, y] = ode15s(..., options)', desc: "Stiff solver. Uses the same Rosenbrock method as ode23s (not MATLAB's NDF method), so solutions agree within the tolerances but the steps differ from MATLAB's ode15s." },
  odeset: { syntax: "options = odeset('Name', value, ...)  |  odeset(oldopts, 'Name', value, ...)", desc: 'Options for the ODE solvers. Supported: RelTol (default 1e-3), AbsTol (1e-6, scalar or per component), MaxStep, InitialStep, Refine, Stats, Jacobian (ode23s/ode15s). Events, Mass, OutputFcn and NonNegative are not supported.' },
  odeget: { syntax: "v = odeget(options, 'Name')  |  odeget(options, 'Name', default)", desc: 'Read an ODE option.' },
  deval: { syntax: 'y = deval(sol, x)  |  y = deval(sol, x, idx)', desc: "Evaluate a solution structure (sol = ode45(...)) at x with the solver's own interpolant; idx picks components." },

  // ---- roots, minimization, integration ----
  fzero: { syntax: 'x = fzero(fun, x0)  |  x = fzero(fun, [a b])  |  [x, fval, exitflag, output] = fzero(..., options)', desc: "Root of a function of one variable (Brent's method, as in MATLAB). From a point x0 it first searches for an interval where fun changes sign. Options (optimset): TolX, Display." },
  fminbnd: { syntax: '[x, fval, exitflag, output] = fminbnd(fun, x1, x2)  |  fminbnd(..., options)', desc: 'Minimum of a function of one variable on [x1, x2] (golden section search with parabolic interpolation). Options: TolX (default 1e-4), MaxFunEvals, MaxIter, Display.' },
  fminsearch: { syntax: '[x, fval, exitflag, output] = fminsearch(fun, x0)  |  fminsearch(fun, x0, options)', desc: 'Unconstrained minimum of a function of several variables (Nelder-Mead simplex, as in MATLAB). Options: TolX, TolFun (default 1e-4), MaxIter, MaxFunEvals (default 200*numel(x0)), Display.' },
  optimset: { syntax: "options = optimset('Name', value, ...)  |  optimset(oldopts, 'Name', value, ...)", desc: 'Options for fzero, fminbnd and fminsearch: Display, MaxFunEvals, MaxIter, TolFun, TolX (FunValCheck, OutputFcn and PlotFcns are accepted but ignored).' },
  optimget: { syntax: "v = optimget(options, 'Name')  |  optimget(options, 'Name', default)", desc: 'Read an optimization option.' },
  integral: { syntax: "q = integral(fun, a, b)  |  integral(..., 'AbsTol', t, 'RelTol', r, 'ArrayValued', true, 'Waypoints', w)", desc: 'Numerical integral of fun from a to b (either may be Inf) by adaptive Gauss-Kronrod quadrature. fun must accept a vector and return a vector of the same size (use .* ./ .^), unless ArrayValued is true. Defaults: AbsTol 1e-10, RelTol 1e-6.' },
  integral2: { syntax: 'q = integral2(fun, xmin, xmax, ymin, ymax)', desc: 'Double integral of fun(x, y); ymin and ymax may be functions of x. fun must accept arrays (use .* ./ .^).' },
  quad: { syntax: 'q = quad(fun, a, b)  |  q = quad(fun, a, b, tol)  |  [q, fcnt] = quad(...)', desc: 'Numerical integral by adaptive Simpson quadrature (older function; prefer integral). Default tol 1e-6.' },

  // ---- constructors ----
  true: { syntax: 'true  |  true(n)  |  true(m, n)', desc: 'Logical 1 (true), or an array of them.' },
  false: { syntax: 'false  |  false(n)  |  false(m, n)', desc: 'Logical 0 (false), or an array of them.' },
  zeros: { syntax: 'A = zeros(n)  |  A = zeros(r, c)  |  A = zeros([r c])', desc: 'Matrix of zeros. Sizes past the second must be 1 (N-D arrays are not supported).' },
  ones: { syntax: 'A = ones(n)  |  A = ones(r, c)  |  A = ones([r c])', desc: 'Matrix of ones.' },
  eye: { syntax: 'A = eye(n)  |  A = eye(r, c)', desc: 'Identity matrix (1s on the main diagonal).' },
  rand: { syntax: "A = rand  |  rand(n)  |  rand(m, n)  |  rand([m n])  |  rand(..., 'like', p)", desc: 'Uniform random values in the open interval (0, 1), from the seedable Mersenne Twister generator (see rng). Sessions start from the same state, as in MATLAB.' },
  randn: { syntax: 'A = randn  |  randn(n)  |  randn(m, n)  |  randn([m n])', desc: "Standard normal random values (Box-Muller transform of the same generator as rand). Statistically equivalent to MATLAB's randn, but not the same sequence." },
  randi: { syntax: 'A = randi(imax)  |  randi(imax, n)  |  randi(imax, m, n)  |  randi([imin imax], ...)', desc: 'Uniform random integers from 1:imax (or imin:imax).' },
  randperm: { syntax: 'p = randperm(n)  |  p = randperm(n, k)', desc: 'A random permutation of 1:n, or k distinct random integers from 1:n, as a row vector.' },
  rng: { syntax: "rng(seed)  |  rng('default')  |  rng('shuffle')  |  rng(seed, 'twister')  |  s = rng  |  rng(s)  |  old = rng(...)", desc: "Control the random number generator used by rand, randn, randi and randperm. rng(seed) makes results repeatable; rng('default') is seed 0 (the state a session starts in); rng('shuffle') seeds from the clock; s = rng saves the settings (Type, Seed, State) and rng(s) restores them. Only the 'twister' (Mersenne Twister) generator is available. The older rand('seed', s), rand('state', s) and rand('twister', s) forms also work, with a warning." },
  linspace: { syntax: 'v = linspace(a, b, n)', desc: 'n linearly spaced points from a to b (default n=100).' },
  logspace: { syntax: 'v = logspace(a, b, n)', desc: 'n logarithmically spaced points from 10^a to 10^b (default n=50).' },
  colon: { syntax: 'v = colon(a, b)  |  v = colon(a, step, b)', desc: 'Function form of the a:b / a:step:b range operator.' },

  // ---- type predicates / conversions ----
  class: { syntax: 's = class(x)', desc: "Class name as a string: 'double', 'char', 'logical', or 'function_handle'." },
  isa: { syntax: 'tf = isa(x, classname)', desc: 'True if x is of the given class.' },
  isnumeric: { syntax: 'tf = isnumeric(x)', desc: 'True unless x is char or logical.' },
  ischar: { syntax: 'tf = ischar(x)', desc: 'True if x is a char array (string).' },
  islogical: { syntax: 'tf = islogical(x)', desc: 'True if x is a logical array.' },
  isreal: { syntax: 'tf = isreal(x)', desc: 'True if x has no complex storage.' },
  iscomplex: { syntax: 'tf = iscomplex(x)', desc: 'True if x has complex storage.' },
  is_function_handle: { syntax: 'tf = is_function_handle(x)', desc: 'True if x is a function handle.' },
  double: { syntax: 'y = double(x)', desc: 'Convert to plain double (strips char/logical tags; char keeps its codes as numbers).' },
  logical: { syntax: 'y = logical(x)', desc: 'Convert to logical (nonzero -> true, zero -> false).' },
  char: { syntax: 's = char(x)', desc: 'Convert numeric codes to a char array (string).' },

  // ---- printing / string formatting ----
  disp: { syntax: 'disp(x)  |  disp hello', desc: 'Display a value without an "x =" header (command syntax works for bareword text: disp hello).' },
  fprintf: { syntax: 'fprintf(fmt, ...)', desc: 'Formatted print to the Command Window (supports \\n, \\t escapes and %d/%f/%s/etc.).' },
  sprintf: { syntax: 's = sprintf(fmt, ...)', desc: 'Formatted print into a string, instead of to the console.' },
  num2str: { syntax: 's = num2str(x)  |  num2str(x, precision)  |  num2str(x, format)', desc: 'Convert a number (or matrix) to text, optionally with a sprintf format applied to each row.' },
  int2str: { syntax: 's = int2str(x)', desc: 'Round to integers and convert to text.' },
  mat2str: { syntax: 's = mat2str(A)', desc: "Convert a matrix to a string usable as a MATLAB literal, e.g. '[1 2;3 4]'." },
  strcmp: { syntax: 'tf = strcmp(s1, s2)', desc: 'True if two char arrays are identical.' },
  strcmpi: { syntax: 'tf = strcmpi(s1, s2)', desc: 'Case-insensitive strcmp.' },
  upper: { syntax: 's2 = upper(s)', desc: 'Convert to uppercase.' },
  lower: { syntax: 's2 = lower(s)', desc: 'Convert to lowercase.' },
  strtrim: { syntax: 's2 = strtrim(s)', desc: 'Remove leading/trailing whitespace.' },
  strrep: { syntax: 's2 = strrep(s, old, new)', desc: 'Replace all occurrences of old with new.' },
  strsplit: { syntax: "C = strsplit(s)  |  strsplit(s, delim)  |  strsplit(s, {d1, d2})", desc: "Split text at a delimiter (default: whitespace) into a 1xN cell array. Consecutive delimiters count as one unless 'CollapseDelimiters' is false." },
  strjoin: { syntax: "s = strjoin(C)  |  strjoin(C, delim)", desc: 'Join a cell array of character vectors with a delimiter (default: a space).' },
  str2double: { syntax: 'x = str2double(s)', desc: "Parse a string as a number (NaN if it doesn't parse)." },
  str2num: { syntax: 'x = str2num(s)', desc: "Evaluate a string as a MATLAB expression (e.g. str2num('[1 2 3]*2'))." },

  // ---- workspace management ----
  who: { syntax: 'who', desc: 'List variable names in the current workspace.' },
  whos: { syntax: 'whos', desc: 'List variables with size and class.' },
  clear: { syntax: "clear  |  clear all  |  clear('x', 'y')  |  clear x y", desc: 'Remove all variables, or specific named ones (command syntax works too: clear x y).' },
  clc: { syntax: 'clc', desc: "Clear the Command Window's output." },
  exist: { syntax: "code = exist('name')", desc: '1 if a variable, 2 if a user function, 5 if a builtin, 0 if not found.' },
  feval: { syntax: "y = feval(fh, ...)  |  y = feval('name', ...)", desc: 'Call a function by handle or by name.' },
  arrayfun: { syntax: "B = arrayfun(fh, A, ...)  |  arrayfun(..., 'UniformOutput', false)", desc: 'Apply a function to each element of one or more same-size arrays. Results must be scalars unless UniformOutput is false, which collects them in a cell array.' },
  cellfun: { syntax: "B = cellfun(fh, C, ...)  |  cellfun(..., 'UniformOutput', false)", desc: "Apply a function (handle or name, e.g. 'isempty') to the contents of each cell. Results must be scalars unless UniformOutput is false." },
  cell: { syntax: 'C = cell(n)  |  cell(m, n)  |  cell([m n])', desc: 'Cell array of empty matrices.' },
  iscell: { syntax: 'tf = iscell(x)', desc: 'True for a cell array.' },
  iscellstr: { syntax: 'tf = iscellstr(x)', desc: 'True for a cell array whose elements are all character vectors.' },
  num2cell: { syntax: 'C = num2cell(A)', desc: 'Put each element of an array in its own cell.' },
  cell2mat: { syntax: 'A = cell2mat(C)', desc: 'Concatenate the contents of a cell array into one matrix.' },
  cellstr: { syntax: 'C = cellstr(chars)', desc: 'Cell column of the rows of a char matrix (trailing blanks removed).' },
  struct: { syntax: "s = struct('f1', v1, 'f2', v2, ...)  |  struct()  |  struct([])", desc: 'Create a struct. A cell-array value with N elements makes an N-element struct array.' },
  fieldnames: { syntax: 'names = fieldnames(s)', desc: 'Field names of a struct, as a cell column.' },
  isfield: { syntax: "tf = isfield(s, 'name')  |  isfield(s, {'a', 'b'})", desc: 'True where s is a struct with the named field(s).' },
  rmfield: { syntax: "s = rmfield(s, 'name')  |  rmfield(s, {'a', 'b'})", desc: 'Remove fields from a struct.' },
  isstruct: { syntax: 'tf = isstruct(x)', desc: 'True for a struct.' },
  getfield: { syntax: "v = getfield(s, 'name')", desc: 'Value of a field (same as s.name).' },
  setfield: { syntax: "s = setfield(s, 'name', v)", desc: 'Copy of s with a field set (same as s.name = v).' },
  struct2cell: { syntax: 'C = struct2cell(s)', desc: 'Field values of a struct as a cell array (one row per field).' },
  numfields: { syntax: 'n = numfields(s)', desc: 'Number of fields in a struct.' },
  error: { syntax: "error(msg)  |  error(fmt, a1, ...)  |  error(id, fmt, a1, ...)  |  error(ME)", desc: 'Throw an error. Caught by try/catch as an MException with .message and .identifier.' },
  warning: { syntax: "warning(msg)  |  warning(id, fmt, ...)  |  warning('off', id)  |  warning('on', id)", desc: 'Print a warning, or turn warnings (all, or one identifier) off and on.' },
  assert: { syntax: "assert(cond)  |  assert(cond, fmt, a1, ...)  |  assert(cond, id, fmt, ...)", desc: "Throw an error unless cond is true (nonzero everywhere)." },
  MException: { syntax: "ME = MException(id, fmt, a1, ...)", desc: 'Create an exception object; throw it with throw(ME).' },
  throw: { syntax: 'throw(ME)', desc: 'Throw an MException.' },
  rethrow: { syntax: 'rethrow(ME)', desc: 'Re-throw a caught MException.' },
  getReport: { syntax: 'msg = getReport(ME)', desc: 'Error message text of an MException.' },
  func2str: { syntax: 's = func2str(fh)', desc: 'Text of a function handle, e.g. \'@(x)x+1\' or \'sin\'.' },
  deal: { syntax: '[a,b,c] = deal(x)  |  [a,b] = deal(x,y)', desc: 'Distribute one value to all outputs, or pass multiple values through positionally.' },

  // ---- plotting ----
  figure: { syntax: "figure  |  figure(n)  |  h = figure('Name', title)", desc: 'Create a figure (lowest unused number) or make figure n current. Returns the figure number.' },
  gcf: { syntax: 'h = gcf', desc: 'Number of the current figure (creates one if none exists).' },
  gca: { syntax: 'ax = gca', desc: 'Handle of the current axes (creates one if none exists).' },
  clf: { syntax: 'clf', desc: 'Clear the current figure (removes all axes).' },
  close: { syntax: 'close  |  close(n)  |  close all', desc: 'Close the current figure, figure n, or every figure.' },
  subplot: { syntax: 'subplot(m, n, p)  |  subplot(mnp)  |  ax = subplot(...)', desc: 'Make (or return to) the axes in cell p of an m-by-n grid; p may list several cells to span them.' },
  sgtitle: { syntax: "sgtitle('text')", desc: 'Title over all the subplots of the current figure.' },
  hold: { syntax: 'hold on  |  hold off  |  hold', desc: 'Keep (or stop keeping) existing plots in the current axes when adding new ones; new lines continue the color order.' },
  ishold: { syntax: 'tf = ishold', desc: 'True if hold is on for the current axes.' },
  plot: { syntax: "h = plot(y)  |  plot(x, y)  |  plot(x, y, 'r--o')  |  plot(x1, y1, x2, y2, ...)  |  plot(..., 'LineWidth', 2)", desc: "Line plot. A matrix gives one line per column. Line specs ('r--o') and Name,Value options: Color, LineWidth, LineStyle, Marker, MarkerSize, MarkerFaceColor, MarkerEdgeColor, DisplayName." },
  semilogx: { syntax: 'semilogx(x, y, ...)', desc: 'Like plot, with a logarithmic x axis.' },
  semilogy: { syntax: 'semilogy(x, y, ...)', desc: 'Like plot, with a logarithmic y axis.' },
  loglog: { syntax: 'loglog(x, y, ...)', desc: 'Like plot, with logarithmic x and y axes.' },
  stairs: { syntax: 'stairs(x, y, ...)', desc: 'Staircase plot.' },
  stem: { syntax: "stem(x, y)  |  stem(..., 'filled')", desc: 'Stem plot: a line from zero to each point, with a marker.' },
  errorbar: { syntax: 'errorbar(y, err)  |  errorbar(x, y, err)  |  errorbar(x, y, neg, pos)', desc: 'Line plot with vertical error bars.' },
  polarplot: { syntax: "polarplot(theta, rho, ...)", desc: 'Line plot in polar coordinates (theta in radians).' },
  scatter: { syntax: "scatter(x, y)  |  scatter(x, y, sz, c)  |  scatter(..., 'filled')", desc: 'Scatter plot; sz is marker area in points^2, c a color or one value per point.' },
  bar: { syntax: "bar(y)  |  bar(x, y)  |  bar(Y, 'stacked')  |  bar(..., width)", desc: 'Bar chart; a matrix gives grouped (or stacked) bars. Options: FaceColor, EdgeColor, BarWidth, DisplayName.' },
  barh: { syntax: 'barh(y)  |  barh(x, y)', desc: 'Horizontal bar chart.' },
  histogram: { syntax: "histogram(x)  |  histogram(x, nbins)  |  histogram(x, edges)  |  histogram(..., 'Normalization', 'pdf')", desc: "Histogram. Options: NumBins, BinEdges, BinWidth, Normalization ('count', 'probability', 'pdf', 'countdensity', 'cumcount', 'cdf'), FaceColor, FaceAlpha." },
  hist: { syntax: 'hist(y)  |  hist(y, nbins)  |  [n,x] = hist(y)', desc: 'Classic MATLAB histogram: plots with no output args, or returns [counts, centers].' },
  area: { syntax: 'area(y)  |  area(x, Y)', desc: 'Filled area plot; a matrix stacks one area per column.' },
  fill: { syntax: 'fill(x, y, c)', desc: 'Filled polygon with color c.' },
  pie: { syntax: "pie(x)  |  pie(x, labels)", desc: 'Pie chart, optionally with a cell array of slice labels.' },
  text: { syntax: "text(x, y, 'str')  |  text(..., 'FontSize', 12, 'HorizontalAlignment', 'center')", desc: 'Place text at data coordinates in the current axes.' },
  xlabel: { syntax: "xlabel('text')", desc: "Label the x axis of the current axes (TeX such as 'x^2' or '\\alpha' is supported)." },
  ylabel: { syntax: "ylabel('text')", desc: 'Label the y axis of the current axes.' },
  title: { syntax: "title('text')  |  title('text', 'subtitle')", desc: 'Title the current axes.' },
  legend: { syntax: "legend('a', 'b', ...)  |  legend(..., 'Location', 'southwest')  |  legend show|off", desc: 'Show a legend; labels apply to plotted objects in order (DisplayName is used otherwise).' },
  grid: { syntax: 'grid on  |  grid off  |  grid minor  |  grid', desc: 'Show or hide grid lines in the current axes.' },
  box: { syntax: 'box on  |  box off', desc: 'Draw (or not) the axes outline on all four sides.' },
  xlim: { syntax: 'xlim([xmin xmax])  |  xlim auto  |  lim = xlim', desc: 'Set, reset or query the x-axis limits.' },
  ylim: { syntax: 'ylim([ymin ymax])  |  ylim auto  |  lim = ylim', desc: 'Set, reset or query the y-axis limits.' },
  xticks: { syntax: 'xticks(values)  |  xticks auto', desc: 'Positions of the x-axis tick marks.' },
  yticks: { syntax: 'yticks(values)  |  yticks auto', desc: 'Positions of the y-axis tick marks.' },
  xticklabels: { syntax: "xticklabels({'a', 'b', ...})", desc: 'Text of the x-axis tick labels.' },
  yticklabels: { syntax: "yticklabels({'a', 'b', ...})", desc: 'Text of the y-axis tick labels.' },
  set: { syntax: "set(h, 'Name', value, ...)", desc: 'Change graphics properties. Lines: Color, LineWidth, LineStyle, Marker, MarkerSize, MarkerFaceColor, MarkerEdgeColor, DisplayName, XData, YData. Axes: XLim, YLim, ZLim, CLim, View, XScale, YScale, XGrid, YGrid, Box. Surfaces: XData, YData, ZData, CData, FaceColor, EdgeColor, FaceAlpha. Images: CData. Contours: ZData, LevelList, LineColor, LineWidth, ShowText. 3-D lines: ZData. Figures: Name, Colormap.' },
  get: { syntax: "v = get(h, 'Name')  |  s = get(h)", desc: 'Read a graphics property, or all supported properties as a struct.' },
  isgraphics: { syntax: 'tf = isgraphics(h)', desc: 'True for elements that are valid graphics handles.' },
  axis: { syntax: 'axis([xmin xmax ymin ymax])  |  axis([xmin xmax ymin ymax zmin zmax])  |  axis equal|image|tight|auto|normal|off|on|ij|xy  |  v = axis', desc: "Set or query axis limits and scaling. ('square' is accepted but has no effect.)" },

  // ---- 3-D plots, images and color ----
  plot3: { syntax: "h = plot3(x, y, z)  |  plot3(x, y, z, 'r--o')  |  plot3(x1, y1, z1, x2, y2, z2, ...)  |  plot3(..., 'LineWidth', 2)", desc: 'Line plot in 3-D. Matrices give one line per column; same line specs and options as plot.' },
  scatter3: { syntax: "scatter3(x, y, z)  |  scatter3(x, y, z, sz, c)  |  scatter3(..., 'filled')", desc: 'Scatter plot in 3-D; sz is marker area in points^2, c a color or one value per point (mapped through the colormap).' },
  surf: { syntax: "h = surf(Z)  |  surf(X, Y, Z)  |  surf(X, Y, Z, C)  |  surf(..., 'EdgeColor', 'none')", desc: 'Colored surface with black grid lines. X and Y may be vectors or meshgrid matrices; color follows Z (or C) through the colormap. Options: FaceColor, EdgeColor, FaceAlpha, LineStyle, LineWidth, DisplayName.' },
  mesh: { syntax: 'h = mesh(Z)  |  mesh(X, Y, Z)  |  mesh(X, Y, Z, C)', desc: 'Wireframe surface: white faces, grid lines colored by the data.' },
  contour: { syntax: "contour(Z)  |  contour(X, Y, Z)  |  contour(..., n)  |  contour(..., levels)  |  contour(..., 'ShowText', 'on')", desc: 'Contour lines of Z, colored through the colormap; n levels or a vector of levels. Options: LineColor, LineWidth, LevelList, ShowText. Unevenly spaced level vectors are drawn with their smallest step.' },
  contourf: { syntax: 'contourf(Z)  |  contourf(X, Y, Z)  |  contourf(..., n)  |  contourf(..., levels)', desc: 'Filled contour plot (regions colored through the colormap, black contour lines).' },
  imagesc: { syntax: 'imagesc(C)  |  imagesc(x, y, C)  |  imagesc(..., [cmin cmax])', desc: 'Show a matrix as an image whose colors span the whole colormap (or the given color limits). Row 1 is at the top.' },
  image: { syntax: 'image(C)  |  image(x, y, C)', desc: 'Show a matrix as an image whose values index the colormap directly (1 is the first color).' },
  colormap: { syntax: "colormap(name)  |  colormap(map)  |  colormap(ax, ...)  |  colormap default  |  map = colormap", desc: 'Set the colormap of the current figure (or of one axes): a name such as parula, jet, hot, gray, or an N-by-3 matrix of RGB values in [0, 1].' },
  parula: { syntax: 'map = parula  |  map = parula(n)', desc: "MATLAB's default colormap (blue to yellow), n colors (default 256)." },
  turbo: { syntax: 'map = turbo(n)', desc: 'Rainbow-like colormap with perceptually smoother steps than jet.' },
  jet: { syntax: 'map = jet(n)', desc: 'Blue-cyan-yellow-red colormap.' },
  hsv: { syntax: 'map = hsv(n)', desc: 'Colormap cycling through the hues (red-yellow-green-cyan-blue-magenta).' },
  hot: { syntax: 'map = hot(n)', desc: 'Black-red-yellow-white colormap.' },
  cool: { syntax: 'map = cool(n)', desc: 'Cyan to magenta colormap.' },
  spring: { syntax: 'map = spring(n)', desc: 'Magenta to yellow colormap.' },
  summer: { syntax: 'map = summer(n)', desc: 'Green to yellow colormap.' },
  autumn: { syntax: 'map = autumn(n)', desc: 'Red to yellow colormap.' },
  winter: { syntax: 'map = winter(n)', desc: 'Blue to green colormap.' },
  gray: { syntax: 'map = gray(n)', desc: 'Black to white colormap.' },
  bone: { syntax: 'map = bone(n)', desc: 'Grayscale colormap with a blue tint.' },
  copper: { syntax: 'map = copper(n)', desc: 'Black to copper colormap.' },
  pink: { syntax: 'map = pink(n)', desc: 'Pastel pink colormap.' },
  white: { syntax: 'map = white(n)', desc: 'All-white colormap.' },
  lines: { syntax: 'map = lines(n)', desc: 'Colormap of the line color order, repeated.' },
  colorbar: { syntax: 'colorbar  |  colorbar off  |  h = colorbar', desc: 'Show (or hide) a color scale beside the current axes.' },
  clim: { syntax: 'clim([cmin cmax])  |  clim auto  |  lims = clim', desc: 'Color limits of the current axes: data values mapped to the first and last colormap colors.' },
  caxis: { syntax: 'caxis([cmin cmax])  |  caxis auto  |  lims = caxis', desc: 'Older name for clim.' },
  view: { syntax: 'view(az, el)  |  view([az el])  |  view(2)  |  view(3)  |  [az, el] = view', desc: 'Viewpoint of a 3-D axes: azimuth and elevation in degrees. view(2) looks straight down; view(3) is the default (-37.5, 30). The projection is orthographic, as in MATLAB.' },
  zlabel: { syntax: "zlabel('text')", desc: 'Label the z axis of the current axes.' },
  zlim: { syntax: 'zlim([zmin zmax])  |  zlim auto  |  lim = zlim', desc: 'Set, reset or query the z-axis limits.' },
  shading: { syntax: 'shading flat  |  shading interp  |  shading faceted', desc: 'Surface shading in the current axes: faceted (with grid lines, the default), flat (no grid lines) or interp. Flat surfaces are drawn with smoothly interpolated colors.' },
  peaks: { syntax: 'Z = peaks  |  Z = peaks(n)  |  [X, Y, Z] = peaks(n)  |  Z = peaks(X, Y)  |  peaks', desc: 'Sample function of two variables on an n-by-n grid over [-3, 3] (default 49). With no outputs, plots it with surf.' },
  sphere: { syntax: '[X, Y, Z] = sphere  |  [X, Y, Z] = sphere(n)  |  sphere', desc: 'Unit sphere as (n+1)-by-(n+1) matrices for surf (default n = 20). With no outputs, plots it.' },

  // ---- saving figures, animation ----
  saveas: { syntax: "saveas(h, 'file.png')  |  saveas(h, 'name', 'svg')", desc: 'Save figure h (or the figure containing an axes) as a PNG, JPEG or SVG file in the Files panel (browser app only).' },
  exportgraphics: { syntax: "exportgraphics(h, 'file.png')  |  exportgraphics(h, 'file.png', 'Resolution', 300)", desc: 'Save a figure as PNG, JPEG or SVG in the Files panel at the given resolution (dpi). An axes handle exports its whole figure.' },
  print: { syntax: "print('file', '-dpng')  |  print(fig, 'file', '-dsvg', '-r300')  |  print('-f2', 'file.png')", desc: 'Save a figure (the current one by default) to a PNG (-dpng), JPEG (-djpeg) or SVG (-dsvg) file in the Files panel. Printing to a printer is not supported.' },
  drawnow: { syntax: 'drawnow', desc: 'Show the figures as they are now, while the code keeps running (for animations). Updates are limited to about 30 per second.' },
  pause: { syntax: "pause(t)  |  pause off  |  pause on  |  state = pause('query')", desc: 'Show the figures, then wait t seconds (Stop still interrupts). pause off makes later pauses return at once. pause with no argument (wait for a key) just continues.' },

  // ---- file I/O ----
  readmatrix: { syntax: "A = readmatrix('file.csv')", desc: 'Read a numeric matrix from CSV (basic parser: no quoted fields).' },
  writematrix: { syntax: "writematrix(A, 'file.csv')", desc: 'Write a numeric matrix to a CSV file in the Files panel (download it from there).' },
  save: { syntax: "save('name.mat')  |  save('name.mat', 'x', 'y')", desc: 'Write numeric/char/logical workspace variables to a real (rudimentary) MAT5 .mat file in the Files panel — see README.' },
  load: { syntax: "load('name.mat')", desc: 'Read variables from a MAT5 .mat file into the current workspace.' },
  run: { syntax: "run('script.m')", desc: "Execute a script from the Files panel in the caller's workspace. For a function file, calls its function with no inputs." },

  // ---- timing & display ----
  tic: { syntax: 'tic  |  t = tic', desc: 'Start a stopwatch timer (optionally returning its id for toc(t)).' },
  toc: { syntax: 'toc  |  s = toc  |  toc(t)', desc: 'Seconds elapsed since tic (or since the tic that returned t); prints them if no output is requested.' },
  format: { syntax: 'format short  |  format long  |  format', desc: 'Choose how numbers display: 4 decimals (short, the default) or about 16 significant digits (long).' },

  // ---- comparison, sets, operator functions ----
  isequal: { syntax: 'tf = isequal(A, B, ...)', desc: "True if all inputs have the same size and values (numeric class is ignored; NaN ~= NaN). Works on cells and structs too." },
  isequaln: { syntax: 'tf = isequaln(A, B, ...)', desc: 'Like isequal, but NaN values compare equal.' },
  ismember: { syntax: '[tf, loc] = ismember(A, S)', desc: 'Which elements of A occur in S, and the lowest index where each does. Works on numbers and on cell arrays of strings.' },
  xor: { syntax: 'c = xor(a, b)', desc: 'Element-wise exclusive OR.' },
  not: { syntax: 'b = not(a)', desc: 'Element-wise logical NOT (same as ~a).' },
  and: { syntax: 'c = and(a, b)', desc: 'Element-wise logical AND (same as a & b).' },
  or: { syntax: 'c = or(a, b)', desc: 'Element-wise logical OR (same as a | b).' },
  plus: { syntax: 'c = plus(a, b)', desc: 'a + b, as a function (handy as @plus).' },
  minus: { syntax: 'c = minus(a, b)', desc: 'a - b, as a function.' },
  times: { syntax: 'c = times(a, b)', desc: 'a .* b, as a function.' },
  rdivide: { syntax: 'c = rdivide(a, b)', desc: 'a ./ b, as a function.' },
  ldivide: { syntax: 'c = ldivide(a, b)', desc: 'a .\\ b, as a function.' },
  mtimes: { syntax: 'c = mtimes(A, B)', desc: 'A * B (matrix product), as a function.' },
  mrdivide: { syntax: 'X = mrdivide(B, A)', desc: 'B / A, as a function.' },
  mldivide: { syntax: 'X = mldivide(A, B)', desc: 'A \\ B, as a function.' },
  mpower: { syntax: 'C = mpower(A, b)', desc: 'A ^ b (matrix power), as a function.' },
  eq: { syntax: 'tf = eq(a, b)', desc: 'a == b, as a function.' },
  ne: { syntax: 'tf = ne(a, b)', desc: 'a ~= b, as a function.' },
  lt: { syntax: 'tf = lt(a, b)', desc: 'a < b, as a function.' },
  gt: { syntax: 'tf = gt(a, b)', desc: 'a > b, as a function.' },
  le: { syntax: 'tf = le(a, b)', desc: 'a <= b, as a function.' },
  ge: { syntax: 'tf = ge(a, b)', desc: 'a >= b, as a function.' },
  uminus: { syntax: 'b = uminus(a)', desc: '-a, as a function.' },
  uplus: { syntax: 'b = uplus(a)', desc: '+a, as a function.' },
  bsxfun: { syntax: 'C = bsxfun(fh, A, B)', desc: 'Apply a two-input element-wise function with implicit expansion (operators already expand, e.g. A - mean(A)).' },

  // ---- more numerics ----
  magic: { syntax: 'M = magic(n)', desc: 'n-by-n magic square (rows, columns and diagonals have equal sums), same layout as MATLAB.' },
  meshgrid: { syntax: '[X, Y] = meshgrid(x, y)  |  meshgrid(x)', desc: 'Grid coordinates: X repeats x along each row, Y repeats y down each column.' },
  ndgrid: { syntax: '[X, Y] = ndgrid(x, y)', desc: 'Like meshgrid, but X varies down the rows and Y across the columns.' },
  diff: { syntax: 'D = diff(X)  |  diff(X, n)  |  diff(X, n, dim)', desc: 'Differences between adjacent elements (n-th order, along dim).' },
  trapz: { syntax: 'Q = trapz(Y)  |  trapz(X, Y)  |  trapz(..., dim)', desc: 'Trapezoidal-rule integral of Y (unit spacing, spacing X, or points X).' },
  cumtrapz: { syntax: 'Q = cumtrapz(Y)  |  cumtrapz(X, Y)  |  cumtrapz(..., dim)', desc: 'Running trapezoidal-rule integral.' },
  circshift: { syntax: 'B = circshift(A, k)  |  circshift(A, [r c])  |  circshift(A, k, dim)', desc: 'Rotate elements circularly by k positions.' },
  kron: { syntax: 'K = kron(A, B)', desc: 'Kronecker tensor product.' },
  nnz: { syntax: 'n = nnz(X)', desc: 'Number of nonzero elements.' },
  sub2ind: { syntax: 'ind = sub2ind([m n], r, c)', desc: 'Convert row/column subscripts to linear indices.' },
  ind2sub: { syntax: '[r, c] = ind2sub([m n], ind)', desc: 'Convert linear indices to row/column subscripts.' },
  mode: { syntax: '[M, F] = mode(X)  |  mode(X, dim)', desc: 'Most frequent value (smallest on ties; NaNs ignored) and how often it occurs.' },
  factorial: { syntax: 'f = factorial(n)', desc: 'n! element-wise (Inf above 170).' },
  nchoosek: { syntax: 'c = nchoosek(n, k)  |  C = nchoosek(v, k)', desc: 'Binomial coefficient, or all k-element combinations of the vector v (one per row).' },
  primes: { syntax: 'p = primes(n)', desc: 'Row vector of the primes up to n.' },
  isprime: { syntax: 'tf = isprime(X)', desc: 'True for elements that are prime.' },
  gcd: { syntax: 'g = gcd(a, b)', desc: 'Greatest common divisor, element-wise.' },
  lcm: { syntax: 'l = lcm(a, b)', desc: 'Least common multiple, element-wise.' },
  roots: { syntax: 'r = roots(p)', desc: 'Roots of the polynomial with coefficients p (highest power first), via companion-matrix eigenvalues.' },
  conv: { syntax: "w = conv(u, v)  |  conv(u, v, 'same'|'valid')", desc: 'Convolution, which is also polynomial multiplication.' },
  deconv: { syntax: '[q, r] = deconv(y, a)', desc: 'Polynomial division: y = conv(a, q) + r.' },
  filter: { syntax: 'y = filter(b, a, x)  |  filter(b, a, x, [], dim)', desc: 'Apply the digital filter b(z)/a(z) to x (FIR when a = 1).' },

  // ---- more strings ----
  strcat: { syntax: 's = strcat(s1, s2, ...)', desc: 'Concatenate text. Trailing blanks of char inputs are removed; with a cell input the result is a cell array.' },
  strfind: { syntax: 'k = strfind(str, pattern)', desc: 'Start indices of every occurrence of pattern (overlaps included).' },
  contains: { syntax: "tf = contains(str, pattern)  |  contains(..., 'IgnoreCase', true)", desc: 'True if str contains pattern (or any of a cell array of patterns). str may be a cell array.' },
  startsWith: { syntax: "tf = startsWith(str, pattern)  |  startsWith(..., 'IgnoreCase', true)", desc: 'True if str starts with pattern.' },
  endsWith: { syntax: "tf = endsWith(str, pattern)  |  endsWith(..., 'IgnoreCase', true)", desc: 'True if str ends with pattern.' },
  regexp: { syntax: "[tok, mat] = regexp(str, expr, 'tokens', 'match')  |  regexp(..., 'once')", desc: "Regular-expression matching. Outputs: 'start', 'end', 'tokenExtents', 'match', 'tokens', 'names', 'split' (in that order by default, or as selected)." },
  regexpi: { syntax: 'regexpi(str, expr, ...)', desc: 'Case-insensitive regexp.' },
  regexprep: { syntax: "s = regexprep(str, expr, replace)  |  regexprep(..., 'once'|'ignorecase')", desc: 'Replace regular-expression matches; $1, $2, ... insert tokens and $0 the whole match.' },
}));
