function matweb_reference(outfile)
%MATWEB_REFERENCE Record MATLAB's results for MatWeb's test cases.
%   matweb_reference writes matweb_reference.txt in the current folder;
%   matweb_reference(FILE) writes FILE. It takes a minute or two and
%   prints some warnings while it runs; that is expected.
%
%   Generated by tools/matlab/make-reference.mjs in the MatWeb repository;
%   do not edit by hand.
if nargin < 1, outfile = 'matweb_reference.txt'; end
fid = fopen(outfile, 'w');
if fid < 0, error('matweb_reference:open', 'Cannot open %s for writing.', outfile); end
closer = onCleanup(@() fclose(fid));
try, feature('hotlinks', 0); catch, end % plain text from evalc
fprintf(fid, '#MATWEB-REFERENCE 1\n');
fprintf(fid, '#VERSION %s\n', version);
fprintf(fid, '#COMPUTER %s\n', computer);
fprintf(fid, '#DATE %s\n', datestr(now, 31));
% Installed products, so functions from a missing toolbox can be told apart.
try
  products = ver;
  for k = 1:numel(products), fprintf(fid, '#PRODUCT %s %s\n', products(k).Name, products(k).Version); end
catch
end
fprintf('Recording MATLAB results for MatWeb in %s ...\n', outfile);
cases = {
  'contract', 'c1', 'r__ = floor([-1.5 2.5]);', 'r__'
  'contract', 'c2', 'r__ = ceil([-1.5 2.5]);', 'r__'
  'contract', 'c3', 'r__ = fix([-1.5 2.5]);', 'r__'
  'contract', 'c4', 'r__ = round([-2.5 2.5 0.5 -0.5]);', 'r__'
  'contract', 'c5', 'r__ = rem([5 -5], 3);', 'r__'
  'contract', 'c6', 'r__ = mod([5 -5], 3);', 'r__'
  'contract', 'c7', 'r__ = mod(5.5, 2);', 'r__'
  'contract', 'c8', 'r__ = rem(5, 0);', 'r__'
  'contract', 'c9', 'r__ = mod(5, 0);', 'r__'
  'contract', 'c10', 'r__ = hypot([3 5], [4 12]);', 'r__'
  'contract', 'c11', 'r__ = atan2(1, 1);', 'r__'
  'contract', 'c12', 'r__ = atan2(0, -1);', 'r__'
  'contract', 'c13', 'r__ = acos(0.5);', 'r__'
  'contract', 'c14', 'r__ = asin(1);', 'r__'
  'contract', 'c15', 'r__ = cosh(0);', 'r__'
  'contract', 'c16', 'r__ = sinh(1);', 'r__'
  'contract', 'c17', 'r__ = log2(8);', 'r__'
  'contract', 'c18', '[f, e] = log2(8);', 'f'
  'contract', 'c19', '[f, e] = log2(8);', 'e'
  'contract', 'c20', '[f, e] = log2([0.75 -3 0]);', 'f'
  'contract', 'c21', '[f, e] = log2([0.75 -3 0]);', 'e'
  'contract', 'c22', 'r__ = conj(1 + 2i);', 'r__'
  'contract', 'c23', 'r__ = angle(-1);', 'r__'
  'contract', 'c24', 'r__ = angle(1i);', 'r__'
  'contract', 'c25', 'r__ = uplus([1 -2]);', 'r__'
  'contract', 'c26', 'r__ = sign([-2 0 3 NaN]);', 'r__'
  'contract', 'c27', 'r__ = sqrt(-4);', 'r__'
  'contract', 'c28', 'r__ = nthroot(-8, 3);', 'r__'
  'contract', 'c29', 'r__ = log(-1);', 'r__'
  'contract', 'c30', 'r__ = exp(1);', 'r__'
  'contract', 'c31', 'r__ = power(2, [1 2 3]);', 'r__'
  'contract', 'c32', 'r__ = eps;', 'r__'
  'contract', 'c33', 'r__ = eps(1000);', 'r__'
  'contract', 'c34', 'r__ = eps(0);', 'r__'
  'contract', 'c35', 'r__ = Inf(2, 1);', 'r__'
  'contract', 'c36', 'r__ = inf(1, 3);', 'r__'
  'contract', 'c37', 'r__ = NaN(2);', 'r__'
  'contract', 'c38', 'r__ = 5 / 0;', 'r__'
  'contract', 'c39', 'r__ = -5 / 0;', 'r__'
  'contract', 'c40', 'r__ = 0 / 0;', 'r__'
  'contract', 'c41', 'r__ = ''a'' + 1;', 'r__'
  'contract', 'c42', 'r__ = true + true;', 'r__'
  'contract', 'c43', 'r__ = [1 2] == [1 3];', 'r__'
  'contract', 'c44', 'r__ = ~[1 0];', 'r__'
  'contract', 'c45', 'r__ = [65, ''b''];', 'r__'
  'contract', 'c46', 'r__ = [true, 2];', 'r__'
  'contract', 'c47', 'r__ = [''ab''; ''cd''];', 'r__'
  'contract', 'c48', 'r__ = horzcat(''ab'', ''c'');', 'r__'
  'contract', 'c49', 'r__ = cat(1, [1 2], [3 4]);', 'r__'
  'contract', 'c50', 'r__ = repmat(''ab'', 1, 2);', 'r__'
  'contract', 'c51', 'r__ = xor(true, false);', 'r__'
  'contract', 'c52', 'r__ = 1:0;', 'r__'
  'contract', 'c53', 'r__ = 0:0.1:0.3;', 'r__'
  'contract', 'c54', 'r__ = (1:3)'';', 'r__'
  'contract', 'c55', 'r__ = ctranspose([1+2i 3]);', 'r__'
  'contract', 'c56', 'r__ = transpose([1+2i 3]);', 'r__'
  'contract', 'c57', 'r__ = class(''a'');', 'r__'
  'contract', 'c58', 'r__ = class(true);', 'r__'
  'contract', 'c59', 'r__ = class({});', 'r__'
  'contract', 'c60', 'r__ = class(struct());', 'r__'
  'contract', 'c61', 'r__ = class(@sin);', 'r__'
  'contract', 'c62', 'r__ = iscell({});', 'r__'
  'contract', 'c63', 'r__ = iscell(1);', 'r__'
  'contract', 'c64', 'r__ = iscellstr({''a'', ''b''});', 'r__'
  'contract', 'c65', 'r__ = iscellstr({''a'', 1});', 'r__'
  'contract', 'c66', 'r__ = iscellstr({});', 'r__'
  'contract', 'c67', 'r__ = iscolumn([1; 2]);', 'r__'
  'contract', 'c68', 'r__ = iscolumn(5);', 'r__'
  'contract', 'c69', 'r__ = iscolumn(zeros(0, 1));', 'r__'
  'contract', 'c70', 'r__ = iscolumn([]);', 'r__'
  'contract', 'c71', 'r__ = isrow(1:3);', 'r__'
  'contract', 'c72', 'r__ = isrow(zeros(1, 0));', 'r__'
  'contract', 'c73', 'r__ = isrow([]);', 'r__'
  'contract', 'c74', 'r__ = isvector(5);', 'r__'
  'contract', 'c75', 'r__ = isvector([]);', 'r__'
  'contract', 'c76', 'r__ = isvector(zeros(1, 0));', 'r__'
  'contract', 'c77', 'r__ = isvector(ones(2));', 'r__'
  'contract', 'c78', 'r__ = isscalar([]);', 'r__'
  'contract', 'c79', 'r__ = isscalar(''a'');', 'r__'
  'contract', 'c80', 'r__ = ismatrix([]);', 'r__'
  'contract', 'c81', 'r__ = isreal(1i);', 'r__'
  'contract', 'c82', 'r__ = isreal(complex(1, 0));', 'r__'
  'contract', 'c83', 'r__ = isreal(1);', 'r__'
  'contract', 'c84', 'r__ = iscomplex(1i);', 'r__'
  'contract', 'c85', 'r__ = iscomplex(1);', 'r__'
  'contract', 'c86', 'r__ = islogical(true);', 'r__'
  'contract', 'c87', 'r__ = islogical(1);', 'r__'
  'contract', 'c88', 'r__ = isnumeric(1);', 'r__'
  'contract', 'c89', 'r__ = isnumeric(''a'');', 'r__'
  'contract', 'c90', 'r__ = isnumeric(true);', 'r__'
  'contract', 'c91', 'r__ = isa(1, ''double'');', 'r__'
  'contract', 'c92', 'r__ = isa(1, ''numeric'');', 'r__'
  'contract', 'c93', 'r__ = isa(1, ''float'');', 'r__'
  'contract', 'c94', 'r__ = isa(true, ''numeric'');', 'r__'
  'contract', 'c95', 'r__ = isa(@sin, ''function_handle'');', 'r__'
  'contract', 'c96', 'r__ = isempty('''');', 'r__'
  'contract', 'c97', 'r__ = isempty('' '');', 'r__'
  'contract', 'c98', 'r__ = isempty(zeros(0, 3));', 'r__'
  'contract', 'c99', 'r__ = isequal(''a'', 97);', 'r__'
  'contract', 'c100', 'r__ = isequal([1 2], [1 2], [1 2]);', 'r__'
  'contract', 'c101', 'r__ = isequal(NaN, NaN);', 'r__'
  'contract', 'c102', 'r__ = isequaln(NaN, NaN);', 'r__'
  'contract', 'c103', 'r__ = ndims(5);', 'r__'
  'contract', 'c104', 'r__ = ndims([]);', 'r__'
  'contract', 'c105', 'r__ = size([]);', 'r__'
  'contract', 'c106', 'r__ = size(zeros(3, 0), 1);', 'r__'
  'contract', 'c107', '[r, c] = size(ones(2, 5));', 'c'
  'contract', 'c108', 'r__ = numel(''hello'');', 'r__'
  'contract', 'c109', 'r__ = length(zeros(3, 7));', 'r__'
  'contract', 'c110', 'r__ = length([]);', 'r__'
  'contract', 'c111', 'r__ = zeros(2, 0);', 'r__'
  'contract', 'c112', 'r__ = ones(0);', 'r__'
  'contract', 'c113', 'r__ = eye(2, 3);', 'r__'
  'contract', 'c114', 'r__ = reshape(1:6, 2, []);', 'r__'
  'contract', 'c115', 'r__ = reshape(1:6, [], 2);', 'r__'
  'contract', 'c116', 'r__ = linspace(0, 1, 5);', 'r__'
  'contract', 'c117', 'r__ = linspace(1, 1, 3);', 'r__'
  'contract', 'c118', 'r__ = linspace(0, 1, 1);', 'r__'
  'contract', 'c119', 'r__ = linspace(0, 1, 0);', 'r__'
  'contract', 'c120', 'r__ = logspace(0, 2, 3);', 'r__'
  'contract', 'c121', 'r__ = size(logspace(0, 2));', 'r__'
  'contract', 'c122', 'r__ = logspace(0, pi, 3);', 'r__'
  'contract', 'c123', 'r__ = logspace(1, 2, 1);', 'r__'
  'contract', 'c124', 'r__ = magic(3);', 'r__'
  'contract', 'c125', 'r__ = magic(4);', 'r__'
  'contract', 'c126', 'r__ = magic(0);', 'r__'
  'contract', 'c127', 'r__ = diag([1 2]);', 'r__'
  'contract', 'c128', 'r__ = diag([1 2; 3 4]);', 'r__'
  'contract', 'c129', 'r__ = diag([1 2], 1);', 'r__'
  'contract', 'c130', 'r__ = diag([1 2], -1);', 'r__'
  'contract', 'c131', 'r__ = diag([1 2 3; 4 5 6], 1);', 'r__'
  'contract', 'c132', 'r__ = tril(magic(3));', 'r__'
  'contract', 'c133', 'r__ = triu(magic(3), 1);', 'r__'
  'contract', 'c134', 'r__ = tril(ones(2, 3), -1);', 'r__'
  'contract', 'c135', 'r__ = circshift(1:5, 2);', 'r__'
  'contract', 'c136', 'r__ = circshift([1; 2; 3], -1);', 'r__'
  'contract', 'c137', 'r__ = fliplr(''abc'');', 'r__'
  'contract', 'c138', 'r__ = kron([1 2], [1; 1]);', 'r__'
  'contract', 'c139', 'r__ = cross([1 0 0], [0 1 0]);', 'r__'
  'contract', 'c140', 'r__ = cross([1; 0; 0], [0; 1; 0]);', 'r__'
  'contract', 'c141', 'r__ = dot([1 2 3], [4 5 6]);', 'r__'
  'contract', 'c142', 'r__ = sum([]);', 'r__'
  'contract', 'c143', 'r__ = sum(zeros(0, 3));', 'r__'
  'contract', 'c144', 'r__ = sum(zeros(3, 0));', 'r__'
  'contract', 'c145', 'r__ = prod([]);', 'r__'
  'contract', 'c146', 'r__ = mean([]);', 'r__'
  'contract', 'c147', 'r__ = max([]);', 'r__'
  'contract', 'c148', 'r__ = sum(true(1, 3));', 'r__'
  'contract', 'c149', 'r__ = sum(''ab'');', 'r__'
  'contract', 'c150', 'r__ = any([]);', 'r__'
  'contract', 'c151', 'r__ = all([]);', 'r__'
  'contract', 'c152', 'r__ = any([0 0; 0 1]);', 'r__'
  'contract', 'c153', 'r__ = cumsum([1 2; 3 4], 2);', 'r__'
  'contract', 'c154', 'r__ = cumprod([1 2 3]);', 'r__'
  'contract', 'c155', 'r__ = cumprod([1 2; 3 4]);', 'r__'
  'contract', 'c156', 'r__ = mean([1 2; 3 4]);', 'r__'
  'contract', 'c157', 'r__ = mean([1 2; 3 4], 2);', 'r__'
  'contract', 'c158', 'r__ = mean([1 2; 3 4], ''all'');', 'r__'
  'contract', 'c159', 'r__ = mean([1 NaN 3], ''omitnan'');', 'r__'
  'contract', 'c160', 'r__ = median([3 1 4 1 5]);', 'r__'
  'contract', 'c161', 'r__ = median([1 2 3 4]);', 'r__'
  'contract', 'c162', 'r__ = var([1 2 3 4]);', 'r__'
  'contract', 'c163', 'r__ = var([1 2 3 4], 1);', 'r__'
  'contract', 'c164', 'r__ = std([2 4 4 4 5 5 7 9]);', 'r__'
  'contract', 'c165', 'r__ = mode([1 2 2 3 3]);', 'r__'
  'contract', 'c166', 'r__ = max([1 NaN 3]);', 'r__'
  'contract', 'c167', 'r__ = min([NaN NaN]);', 'r__'
  'contract', 'c168', 'r__ = max([1 5; 7 2]);', 'r__'
  'contract', 'c169', '[m, i] = max([1 5; 7 2], [], 2);', 'i'
  'contract', 'c170', 'r__ = max([1 2], 1.5);', 'r__'
  'contract', 'c171', 'r__ = min([4 2 8], [], 2);', 'r__'
  'contract', 'c172', 'r__ = movmin([4 2 6 1 3], 3);', 'r__'
  'contract', 'c173', 'r__ = movprod([1 2 3 4], 2);', 'r__'
  'contract', 'c174', 'r__ = movvar([1 2 3 4 5], 3);', 'r__'
  'contract', 'c175', 'r__ = diff([1 4 9 16]);', 'r__'
  'contract', 'c176', 'r__ = diff([1 4 9 16], 2);', 'r__'
  'contract', 'c177', 'r__ = trapz([1 2 3]);', 'r__'
  'contract', 'c178', 'r__ = cumtrapz([1 2 3]);', 'r__'
  'contract', 'c179', 'r__ = find([0 1 0 1]);', 'r__'
  'contract', 'c180', 'r__ = find([0; 1; 1]);', 'r__'
  'contract', 'c181', 'r__ = find([0 0]);', 'r__'
  'contract', 'c182', 'r__ = find([0; 0]);', 'r__'
  'contract', 'c183', 'r__ = find([]);', 'r__'
  'contract', 'c184', 'r__ = find([1 1 1], 2);', 'r__'
  'contract', 'c185', 'r__ = sort([3 1 2], ''descend'');', 'r__'
  'contract', 'c186', '[s, i] = sort([3 1 2]);', 'i'
  'contract', 'c187', 'r__ = sort([3 NaN 1]);', 'r__'
  'contract', 'c188', 'r__ = sort([3 NaN 1], ''descend'');', 'r__'
  'contract', 'c189', 'r__ = unique([3 1 2 1]);', 'r__'
  'contract', 'c190', 'r__ = unique([3; 1; 1]);', 'r__'
  'contract', 'c191', 'r__ = ismember([1 5], [1 2 3]);', 'r__'
  'contract', 'c192', 'r__ = det(magic(3));', 'r__'
  'contract', 'c193', 'r__ = inv([2 0; 0 4]);', 'r__'
  'contract', 'c194', 'r__ = rank(magic(4));', 'r__'
  'contract', 'c195', 'r__ = trace(magic(3));', 'r__'
  'contract', 'c196', 'r__ = norm([3 4]);', 'r__'
  'contract', 'c197', 'r__ = norm([1 2; 3 4], ''fro'');', 'r__'
  'contract', 'c198', 'r__ = norm([1 2; 3 4], 1);', 'r__'
  'contract', 'c199', 'r__ = norm([1 2; 3 4], Inf);', 'r__'
  'contract', 'c200', 'r__ = svd([3 0; 0 4]);', 'r__'
  'contract', 'c201', 'r__ = pinv([1 2; 2 4]);', 'r__'
  'contract', 'c202', '[L, U, P] = lu([1 2; 3 4]);', 'L'
  'contract', 'c203', '[L, U, P] = lu([1 2; 3 4]);', 'U'
  'contract', 'c204', '[L, U, P] = lu([1 2; 3 4]);', 'P'
  'contract', 'c205', '[V, D] = eig([1 2; 3 4]);', 'V'
  'contract', 'c206', '[V, D] = eig([1 2; 3 4]);', 'D'
  'contract', 'c207', '[V, D] = eig([0 1; -1 0]);', 'V'
  'contract', 'c208', 'r__ = [2 0; 0 4] \ [2; 4];', 'r__'
  'contract', 'c209', 'r__ = [1 2] / [2 4];', 'r__'
  'contract', 'c210', 'r__ = [1 1; 0 1] ^ 3;', 'r__'
  'contract', 'c211', 'r__ = polyfit([1 2 3], [2 4 6], 1);', 'r__'
  'contract', 'c212', 'r__ = polyval([1 0 -1], 3);', 'r__'
  'contract', 'c213', 'r__ = conv([1 1], [1 -1]);', 'r__'
  'contract', 'c214', 'r__ = interp1([1 2 3], [10 20 30], 2.5);', 'r__'
  'contract', 'c215', 'r__ = interp1([1 2], [10 20], 3);', 'r__'
  'contract', 'c216', 'r__ = nchoosek(5, 2);', 'r__'
  'contract', 'c217', 'r__ = factorial(5);', 'r__'
  'contract', 'c218', 'r__ = primes(10);', 'r__'
  'contract', 'c219', 'r__ = isprime(1:5);', 'r__'
  'contract', 'c220', 'r__ = gcd(12, 18);', 'r__'
  'contract', 'c221', 'r__ = lcm(4, 6);', 'r__'
  'contract', 'c222', 'r__ = logical([2 0]);', 'r__'
  'contract', 'c223', 'r__ = double(''A'');', 'r__'
  'contract', 'c224', 'r__ = char(72);', 'r__'
  'contract', 'c225', 'r__ = char({''a'', ''bcd''});', 'r__'
  'contract', 'c226', 'r__ = char(''a'', ''bc'');', 'r__'
  'contract', 'c227', 'r__ = char([72 105]);', 'r__'
  'contract', 'c228', 'r__ = num2str(pi);', 'r__'
  'contract', 'c229', 'r__ = num2str(1e10);', 'r__'
  'contract', 'c230', 'r__ = num2str(-0.5);', 'r__'
  'contract', 'c231', 'r__ = num2str(true);', 'r__'
  'contract', 'c232', 'r__ = int2str(2.5);', 'r__'
  'contract', 'c233', 'r__ = mat2str([1 2; 3 4]);', 'r__'
  'contract', 'c234', 'r__ = mat2str(true);', 'r__'
  'contract', 'c235', 'r__ = mat2str([0.1 NaN Inf]);', 'r__'
  'contract', 'c236', 'r__ = sprintf(''%d'', 3.5);', 'r__'
  'contract', 'c237', 'r__ = sprintf(''%5.2f|'', [1 2]);', 'r__'
  'contract', 'c238', 'r__ = sprintf(''%d,'', [1 2; 3 4]);', 'r__'
  'contract', 'c239', 'r__ = upper(''abC'');', 'r__'
  'contract', 'c240', 'r__ = strtrim(sprintf('' a\t''));', 'r__'
  'contract', 'c241', 'r__ = strrep(''abcb'', ''b'', ''XY'');', 'r__'
  'contract', 'c242', 'r__ = regexprep(''abc'', ''b'', ''X'');', 'r__'
  'contract', 'c243', 'r__ = strjoin({''a'', ''b''}, ''-'');', 'r__'
  'contract', 'c244', 'r__ = strsplit(''a,b,,c'', '','');', 'r__'
  'contract', 'c245', 'r__ = strsplit(''a,b,,c'', '','', ''CollapseDelimiters'', false);', 'r__'
  'contract', 'c246', 'r__ = str2double(''3.5'');', 'r__'
  'contract', 'c247', 'r__ = str2double(''x'');', 'r__'
  'contract', 'c248', 'r__ = str2double({''1'', ''a''});', 'r__'
  'contract', 'c249', 'r__ = str2double(''1,000'');', 'r__'
  'contract', 'c250', 'r__ = str2double(''3abc'');', 'r__'
  'contract', 'c251', 'r__ = str2double(''-Inf'');', 'r__'
  'contract', 'c252', 'r__ = str2double(''1+2i'');', 'r__'
  'contract', 'c253', 'r__ = str2double(5);', 'r__'
  'contract', 'c254', 'r__ = strcmp(''a'', 97);', 'r__'
  'contract', 'c255', 'r__ = strcmpi(''ABC'', ''abc'');', 'r__'
  'contract', 'c256', 'r__ = strcmpi({''a'', ''B''}, ''b'');', 'r__'
  'contract', 'c257', 'r__ = strfind(''abcbc'', ''bc'');', 'r__'
  'contract', 'c258', 'r__ = strfind(''abc'', ''x'');', 'r__'
  'contract', 'c259', 'r__ = num2cell([1 2]);', 'r__'
  'contract', 'c260', 'r__ = cell2mat({1 2; 3 4});', 'r__'
  'contract', 'c261', 'r__ = isfield(struct(''a'', 1), {''a'', ''b''});', 'r__'
  'contract', 'c262', 'r__ = fieldnames(struct(''b'', 1, ''a'', 2));', 'r__'
  'contract', 'c263', 'r__ = struct2cell(struct(''a'', 1, ''b'', ''x''));', 'r__'
  'contract', 'c264', 'r__ = numfields(struct(''a'', 1, ''b'', 2));', 'r__'
  'contract', 'c265', 'r__ = getfield(struct(''a'', 5), ''a'');', 'r__'
  'contract', 'c266', 's = setfield(struct(''a'', 5), ''a'', 6); r = s.a;', 'r'
  'contract', 'c267', 'r__ = cellfun(@numel, {''ab'', ''cde'', ''''});', 'r__'
  'contract', 'c268', 'r__ = cellfun(@isempty, {});', 'r__'
  'contract', 'c269', 'r__ = arrayfun(@(x) x^2, [1 2 3]);', 'r__'
  'contract', 'c270', 'r__ = size(cell(2, 3));', 'r__'
  'error', 'e1', 'x = undefined_thing;', ''
  'error', 'e2', 'y = undefined_fn(3);', ''
  'error', 'e3', 'a = [1 2 3]; a(5);', ''
  'error', 'e4', 'a = [1 2 3]; a(0);', ''
  'error', 'e5', 'a = [1 2 3]; a(1.5);', ''
  'error', 'e6', 'A = magic(3); A(4, 1);', ''
  'error', 'e7', 'q = [1 2 3]; q(:, 4);', ''
  'error', 'e8', '[1 2] + [1 2 3];', ''
  'error', 'e9', '[1 2; 3 4] * [1 2 3];', ''
  'error', 'e10', 'zeros(2) \ [1 2 3]'';', ''
  'error', 'e11', '[1 2, [3; 4]];', ''
  'error', 'e12', '[1 2; 3];', ''
  'error', 'e13', 'x = 1; x{1};', ''
  'error', 'e14', 'c = {1}; c(2);', ''
  'error', 'e15', 's.a = 1; s.b;', ''
  'error', 'e16', 'f = @(x) x; f(1, 2);', ''
  'error', 'e17', 'sin(1, 2);', ''
  'error', 'e18', 'atan2(1);', ''
  'error', 'e19', 'circshift(1:3);', ''
  'error', 'e20', 'sin({1});', ''
  'error', 'e21', 'sum(struct(''a'', 1));', ''
  'error', 'e22', 'logical(NaN);', ''
  'error', 'e23', 'error(''my:id'', ''Custom %d'', 5);', ''
  'error', 'e24', 'error(''plain message'');', ''
  'probe', 'p1', 'r__ = diff(5);', 'r__'
  'probe', 'p2', 'r__ = unique([]);', 'r__'
  'probe', 'p3', 'r__ = find(0);', 'r__'
  'probe', 'p4', 'r__ = find(zeros(0, 3));', 'r__'
  'probe', 'p5', 'r__ = max(zeros(0, 3));', 'r__'
  'probe', 'p6', 'r__ = sort([]);', 'r__'
  'probe', 'p7', 'r__ = sprintf(''%.1f'', 0.25);', 'r__'
  'probe', 'p8', 'r__ = sprintf(''%.0f'', 0.5);', 'r__'
  'probe', 'p9', 'r__ = sprintf(''%.0f'', 2.5);', 'r__'
  'probe', 'p10', 'r__ = sprintf(''%.1f'', 1.25);', 'r__'
  'probe', 'p11', 'r__ = sprintf(''%5.1f'', [1.25 -2.5]);', 'r__'
  'probe', 'p12', 'r__ = sprintf(''%g'', 1e5);', 'r__'
  'probe', 'p13', 'r__ = sprintf(''%g'', 123456);', 'r__'
  'probe', 'p14', 'r__ = sprintf(''%x'', 255);', 'r__'
  'probe', 'p15', 'r__ = sprintf(''%5s|'', ''ab'');', 'r__'
  'probe', 'p16', 'r__ = sprintf(''%-5d|'', 3);', 'r__'
  'probe', 'p17', 'r__ = sprintf(''%+.2e'', -12345.678);', 'r__'
  'probe', 'p18', 'r__ = num2str(123456789);', 'r__'
  'probe', 'p19', 'r__ = num2str(0.1 + 0.2);', 'r__'
  'probe', 'p20', 'r__ = num2str([1 2; 3 4]);', 'r__'
  'probe', 'p21', 'r__ = num2str(-pi, 8);', 'r__'
  'probe', 'p22', 'r__ = num2str(pi, ''%10.5f'');', 'r__'
  'probe', 'p23', 'r__ = num2str(1e-10);', 'r__'
  'probe', 'p24', 'r__ = num2str(1+2i);', 'r__'
  'probe', 'p25', 'r__ = mat2str(pi);', 'r__'
  'probe', 'p26', 'r__ = mat2str(-0.5);', 'r__'
  'probe', 'p27', 'r__ = mat2str([1.5 -2]);', 'r__'
  'probe', 'p28', 'r__ = mat2str(1+2i);', 'r__'
  'probe', 'p29', 'r__ = mat2str(''abc'');', 'r__'
  'probe', 'p30', 'r__ = mat2str(zeros(0, 3));', 'r__'
  'probe', 'p31', 'r__ = int2str([1.5 -2.5]);', 'r__'
  'probe', 'p32', 'r__ = null(magic(4));', 'r__'
  'probe', 'p33', 'r__ = orth([1 1; 1 1]);', 'r__'
  'probe', 'p34', '[Q, R] = qr([1 2; 3 4]);', 'Q'
  'probe', 'p35', '[Q, R] = qr([1 2; 3 4]);', 'R'
  'probe', 'p36', '[V, D] = eig([2 1; 1 2]);', 'V'
  'probe', 'p37', '[V, D] = eig([1 2; 3 4]);', 'V'
  'probe', 'p38', 'r__ = eig([0 1; -1 0]);', 'r__'
  'probe', 'p39', 'r__ = roots([1 0 1]);', 'r__'
  'probe', 'p40', 'r__ = roots(reshape(magic(4), 1, []));', 'r__'
  'probe', 'p41', 'r__ = svd(magic(4));', 'r__'
  'probe', 'p42', '[U, S, V] = svd([1 2; 3 4; 5 6]);', 'U'
  'probe', 'p43', 'r__ = pinv(magic(4));', 'r__'
  'probe', 'p44', 'r__ = expm([0 1; -1 0]);', 'r__'
  'probe', 'p45', 'r__ = sqrtm([4 1; 1 3]);', 'r__'
  'probe', 'p46', 'r__ = sqrtm([1 2; 3 4]);', 'r__'
  'probe', 'p47', 'r__ = cellfun(@isempty, {});', 'r__'
  'probe', 'p48', 'r__ = cellfun(''isempty'', {});', 'r__'
  'probe', 'p49', 'r__ = iscellstr({});', 'r__'
  'probe', 'p50', 'r__ = isvector(zeros(1, 0));', 'r__'
  'probe', 'p51', 'r__ = logspace(0, pi, 3);', 'r__'
  'probe', 'p52', 'r__ = strsplit(''a,b,,c'', '','');', 'r__'
  'probe', 'p53', 'r__ = strjoin({''a'', ''b'', ''c''});', 'r__'
  'probe', 'p54', 'r__ = regexp(''ab12cd'', ''\d+'', ''match'');', 'r__'
  'probe', 'p55', 'r__ = regexprep(''aaa'', ''a'', ''b'', ''once'');', 'r__'
  'probe', 'p56', 'r__ = strtrim(sprintf('' \t a b \n''));', 'r__'
  'probe', 'p57', 'r__ = upper({''ab'', ''c''});', 'r__'
  'probe', 'p58', 'r__ = strrep({''aa'', ''ba''}, ''a'', ''x'');', 'r__'
  'probe', 'p59', 'r__ = fliplr({1, ''a'', 3});', 'r__'
  'probe', 'p60', 'r__ = fftshift({1, 2, 3});', 'r__'
  'probe', 'p61', 'r__ = mean(int8([1 2]));', 'r__'
  'probe', 'p62', 'r__ = class(true + true);', 'r__'
  'probe', 'p63', 'r__ = class([''a'' 66]);', 'r__'
  'probe', 'p64', 'r__ = class([true; 2]);', 'r__'
  'probe', 'p65', 'r__ = class({} == {});', 'r__'
  'probe', 'p66', 'r__ = isequal({1, 2}, {1, 2});', 'r__'
  'probe', 'p67', 'r__ = mod(-1, Inf);', 'r__'
  'probe', 'p68', 'r__ = mod(1, -Inf);', 'r__'
  'probe', 'p69', 'r__ = rem(-1, Inf);', 'r__'
  'probe', 'p70', 'r__ = atan2(-0, -1);', 'r__'
  'probe', 'p71', 'r__ = round(2.5);', 'r__'
  'probe', 'p72', 'r__ = round(-0.5);', 'r__'
  'probe', 'p73', 'r__ = sign(-0);', 'r__'
  'probe', 'p74', 'r__ = 1/-0;', 'r__'
  'probe', 'p75', 'r__ = max(-0, 0);', 'r__'
  'probe', 'p76', 'r__ = min([NaN 1], [], 2);', 'r__'
  'probe', 'p77', 'r__ = cumsum([1 NaN 2]);', 'r__'
  'probe', 'p78', 'r__ = cummax([1 NaN 3 2]);', 'r__'
  'probe', 'p79', 'r__ = median([1 NaN 3]);', 'r__'
  'probe', 'p80', 'r__ = median([1 NaN 3], ''omitnan'');', 'r__'
  'probe', 'p81', 'r__ = mode([]);', 'r__'
  'probe', 'p82', 'r__ = var(5);', 'r__'
  'probe', 'p83', 'r__ = std([]);', 'r__'
  'probe', 'p84', 'r__ = var([1 2; 3 4], [], 2);', 'r__'
  'probe', 'p85', 'r__ = histcounts([1 2 2 3 10]);', 'r__'
  'probe', 'p86', 'r__ = histcounts(randn(0, 1));', 'r__'
  'probe', 'p87', 'r__ = discretize([1 5 10], [0 5 10]);', 'r__'
  'probe', 'p88', 'r__ = accumarray([1; 3], [10; 20]);', 'r__'
  'probe', 'p89', 'r__ = prctile([1 2 3 4], [25 50 75]);', 'r__'
  'probe', 'p90', 'r__ = interp1([1 2 3], [4 5 6], [0 1.5 4], ''linear'', ''extrap'');', 'r__'
  'probe', 'p91', 'r__ = interp1([1 2 3], [4 5 6], 2.5, ''nearest'');', 'r__'
  'probe', 'p92', 'r__ = spline([0 1 2 3], [0 1 8 27], 1.5);', 'r__'
  'probe', 'p93', 'r__ = pchip([0 1 2 3], [0 1 8 27], 1.5);', 'r__'
  'probe', 'p94', 'r__ = polyfit([1 2 3 4], [1 4 9 16], 2);', 'r__'
  'probe', 'p95', 'r__ = polyval([1 2 3], [1 2; 3 4]);', 'r__'
  'probe', 'p96', 'r__ = conv([1 2 3], [1 1], ''same'');', 'r__'
  'probe', 'p97', 'r__ = filter(1, [1 -0.5], [1 1 1]);', 'r__'
  'probe', 'p98', 'r__ = deconv([1 3 3 1], [1 1]);', 'r__'
  'probe', 'p99', 'r__ = trapz([1 2; 3 4]);', 'r__'
  'probe', 'p100', 'r__ = cumtrapz([1 2; 3 4], 2);', 'r__'
  'probe', 'p101', 'r__ = nchoosek(1:4, 3);', 'r__'
  'probe', 'p102', 'r__ = perms([1 2 3]);', 'r__'
  'probe', 'p103', 'r__ = factor(360);', 'r__'
  'probe', 'p104', 'r__ = primes(1);', 'r__'
  'probe', 'p105', 'r__ = isprime(0:3);', 'r__'
  'probe', 'p106', '[n, d] = rat(0.75);', 'd'
  'probe', 'p107', 'r__ = rat(pi);', 'r__'
  'probe', 'p108', 'r__ = rats(0.75);', 'r__'
  'probe', 'p109', 'r__ = gcd([12 18], 8);', 'r__'
  'probe', 'p110', 'r__ = lcm(int8(4), 6);', 'r__'
  'probe', 'p111', 'r__ = erf(0.5);', 'r__'
  'probe', 'p112', 'r__ = gamma(0.5);', 'r__'
  'probe', 'p113', 'r__ = gamma(-1);', 'r__'
  'probe', 'p114', 'r__ = gammaln(0.5);', 'r__'
  'probe', 'p115', 'r__ = psi(1);', 'r__'
  'probe', 'p116', 'r__ = beta(2, 3);', 'r__'
  'probe', 'p117', 'r__ = betainc(0.5, 2, 3);', 'r__'
  'probe', 'p118', 'r__ = gammainc(1, 2);', 'r__'
  'probe', 'p119', 'r__ = erfinv(0.5);', 'r__'
  'probe', 'p120', 'r__ = fft([1 2 3]);', 'r__'
  'probe', 'p121', 'r__ = ifft([1 2 3]);', 'r__'
  'probe', 'p122', 'r__ = fft([1 0 0 0]);', 'r__'
  'probe', 'p123', 'r__ = fft2([1 2; 3 4]);', 'r__'
  'probe', 'p124', 'r__ = fftshift([1 2 3 4 5]);', 'r__'
  'probe', 'p125', 'r__ = ifftshift([1 2 3 4 5]);', 'r__'
  'probe', 'p126', 'r__ = intersect([3 1 2], [2 3 4]);', 'r__'
  'probe', 'p127', 'r__ = union({''b'', ''a''}, {''c'', ''a''});', 'r__'
  'probe', 'p128', 'r__ = setdiff([5 1 3 1], 1);', 'r__'
  'probe', 'p129', 'r__ = unique({''b'', ''a'', ''b''});', 'r__'
  'probe', 'p130', 'r__ = sortrows([3 1; 1 2; 3 0]);', 'r__'
  'probe', 'p131', 'r__ = issorted([1 2 2 3]);', 'r__'
  'probe', 'p132', 'r__ = movmean(1:5, 2);', 'r__'
  'probe', 'p133', 'r__ = movmedian([4 1 3 2], 3);', 'r__'
  'probe', 'p134', 'r__ = normalize([1 2 3]);', 'r__'
  'probe', 'p135', 'r__ = rescale([1 2 3]);', 'r__'
  'probe', 'p136', 'r__ = bounds([3 1 2]);', 'r__'
  'probe', 'p137', 'r__ = vecnorm([3 4; 6 8]);', 'r__'
  'probe', 'p138', 'r__ = cov([1 2 3; 4 6 5]);', 'r__'
  'probe', 'p139', 'r__ = corrcoef([1 2 3], [2 4 7]);', 'r__'
  'probe', 'p140', 'r__ = quantile([1 2 3 4], 0.5);', 'r__'
  'probe', 'p141', 'r__ = zeros(2, 0) * zeros(0, 3);', 'r__'
  'probe', 'p142', 'r__ = ones(0, 3) * ones(3, 2);', 'r__'
  'probe', 'p143', 'r__ = sum(zeros(2, 0), 2);', 'r__'
  'probe', 'p144', 'r__ = [] + 1;', 'r__'
  'probe', 'p145', 'r__ = [] == [];', 'r__'
  'probe', 'p146', 'r__ = isempty([] + []);', 'r__'
  'probe', 'p147', 'r__ = [''abc''] == ''abc'';', 'r__'
  'probe', 'p148', 'r__ = ''abc'' < ''b'';', 'r__'
  'probe', 'p149', 'r__ = ~[];', 'r__'
  'probe', 'p150', 'r__ = any(zeros(0, 3));', 'r__'
  'probe', 'p151', 'r__ = all(zeros(0, 3));', 'r__'
  'probe', 'p152', 'r__ = xor([1 0], [1 1]);', 'r__'
  'lang', 'l1', 'A = magic(4); r = A(2, 3);', 'r'
  'lang', 'l2', 'A = magic(4); r = A(7);', 'r'
  'lang', 'l3', 'A = magic(4); r = A(end, 1);', 'r'
  'lang', 'l4', 'A = magic(4); r = A(end);', 'r'
  'lang', 'l5', 'A = magic(4); r = A([1 3], [2 4]);', 'r'
  'lang', 'l6', 'A = magic(4); r = A(:, 2);', 'r'
  'lang', 'l7', 'A = magic(4); r = A(2, :);', 'r'
  'lang', 'l8', 'A = magic(4); r = A(:);', 'r'
  'lang', 'l9', 'A = magic(4); r = A(:)'';', 'r'
  'lang', 'l10', 'A = magic(4); r = A(A > 10);', 'r'
  'lang', 'l11', 'A = magic(4); r = A(logical([1 0 1 0]), :);', 'r'
  'lang', 'l12', 'A = magic(4); r = A([]);', 'r'
  'lang', 'l13', 'A = magic(4); r = A([], 1);', 'r'
  'lang', 'l14', 'A = magic(4); r = A(:, []);', 'r'
  'lang', 'l15', 'v = 1:5; r = v([true false true]);', 'r'
  'lang', 'l16', 'v = (1:5)''; r = v([2 4]);', 'r'
  'lang', 'l17', 'v = 1:5; r = v([2; 4]);', 'r'
  'lang', 'l18', 'v = (1:5)''; r = v([2 4; 1 3]);', 'r'
  'lang', 'l19', 'A = magic(3); r = A([1 2; 3 4]);', 'r'
  'lang', 'l20', 'A = magic(3); r = A(end:-1:1, :);', 'r'
  'lang', 'l21', 'A = magic(3); r = A(end, end);', 'r'
  'lang', 'l22', 'v = 1:5; r = v(end-1:end);', 'r'
  'lang', 'l23', 'v = 1:5; r = v(logical([0 0 0 0 0]));', 'r'
  'lang', 'l24', 'x = 5; r = x(1, 1, 1);', 'r'
  'lang', 'l25', 's = ''hello''; r = s([1 end]);', 'r'
  'lang', 'l26', 's = ''hello''; r = s(end:-1:1);', 'r'
  'lang', 'l27', 'c = {1, ''a'', [2 3]}; r = c(2);', 'r'
  'lang', 'l28', 'c = {1, ''a'', [2 3]}; r = c{3}(2);', 'r'
  'lang', 'l29', 'x = []; x(3) = 5;', 'x'
  'lang', 'l30', 'x = 1:3; x(6) = 9;', 'x'
  'lang', 'l31', 'x = (1:3)''; x(5) = 9;', 'x'
  'lang', 'l32', 'A = eye(2); A(3, 3) = 7;', 'A'
  'lang', 'l33', 'A = magic(3); A(2, :) = [];', 'A'
  'lang', 'l34', 'A = magic(3); A(:, [1 3]) = [];', 'A'
  'lang', 'l35', 'v = 1:5; v([2 4]) = [];', 'v'
  'lang', 'l36', 'v = (1:5)''; v(2) = [];', 'v'
  'lang', 'l37', 'A = magic(3); A(5) = [];', 'A'
  'lang', 'l38', 'A = zeros(2); A(:) = 1:4;', 'A'
  'lang', 'l39', 'A = zeros(2, 3); A(2, :) = 7;', 'A'
  'lang', 'l40', 'A = magic(3); A(A > 5) = 0;', 'A'
  'lang', 'l41', 's = ''abc''; s(5) = ''e''; r = double(s);', 'r'
  'lang', 'l42', 's = ''abc''; s(2) = [];', 's'
  'lang', 'l43', 'c = {}; c{3} = 1;', 'c'
  'lang', 'l44', 'c = {1, 2}; c(2) = [];', 'c'
  'lang', 'l45', 'x = 1; x(2, 3) = 4;', 'x'
  'lang', 'l46', 'A = 1:3; A(:, end+1) = 4;', 'A'
  'lang', 'l47', 'A = [1 2; 3 4]; A(end+1, :) = [5 6];', 'A'
  'lang', 'l48', 'v = []; v(end+1) = 3; v(end+1) = 4;', 'v'
  'lang', 'l49', 'x = true(1, 2); x(4) = true;', 'x'
  'lang', 'l50', 'x = true(1, 2); x(2) = 5;', 'x'
  'lang', 'l51', 'x = ''ab''; x(1) = 66;', 'x'
  'lang', 'l52', 'x = 1:3; x(2) = true;', 'x'
  'lang', 'l53', 's.a = 1; s.b.c = ''x''; r = s.b.c;', 'r'
  'lang', 'l54', 's(2).a = 5; r = size(s);', 'r'
  'lang', 'l55', 's(2).a = 5; r = s(1).a;', 'r'
  'lang', 'l56', 's = struct(''a'', {1, 2, 3}); r = [s.a];', 'r'
  'lang', 'l57', 's = struct(''a'', {1, 2, 3}); r = {s.a};', 'r'
  'lang', 'l58', 's = struct(''a'', {}); r = size(s);', 'r'
  'lang', 'l59', 's = struct(''a'', {{1, 2}}); r = s.a;', 'r'
  'lang', 'l60', 's.x = 1; f = ''x''; r = s.(f);', 'r'
  'lang', 'l61', 'c = {1, 2; 3, 4}; r = [c{:, 1}];', 'r'
  'lang', 'l62', 'c = {1, ''ab''}; r = class(c{2});', 'r'
  'lang', 'l63', 'c = cell(2, 3); r = size(c{1});', 'r'
  'lang', 'l64', 'c = num2cell(magic(2)); r = c{2, 1};', 'r'
  'lang', 'l65', 's = struct(); r = isempty(fieldnames(s));', 'r'
  'lang', 'l66', 's = struct(''a'', 1, ''b'', 2); s = rmfield(s, ''a''); r = fieldnames(s);', 'r'
  'lang', 'l67', 's = struct(''b'', 1, ''a'', 2); r = fieldnames(orderfields(s));', 'r'
  'lang', 'l68', 'x = struct(''a'', 1); y = x; y.a = 2; r = x.a;', 'r'
  'lang', 'l69', 'c = {1}; d = c; d{1} = 2; r = c{1};', 'r'
  'lang', 'l70', 'A = 1:3; B = A; B(1) = 9; r = A;', 'r'
  'lang', 'l71', 'r__ = -2^2;', 'r__'
  'lang', 'l72', 'r__ = 2^-1;', 'r__'
  'lang', 'l73', 'r__ = -2^-2;', 'r__'
  'lang', 'l74', 'r__ = 2^3^2;', 'r__'
  'lang', 'l75', 'r__ = ~1 == 0;', 'r__'
  'lang', 'l76', 'r__ = 1:3 + 1;', 'r__'
  'lang', 'l77', 'r__ = (1:3)'';', 'r__'
  'lang', 'l78', 'r__ = [1 2 3]'' * [1 2];', 'r__'
  'lang', 'l79', 'r__ = [1+2i 3]'';', 'r__'
  'lang', 'l80', 'r__ = [1+2i 3].'';', 'r__'
  'lang', 'l81', 'r__ = 1:0.5:3;', 'r__'
  'lang', 'l82', 'r__ = 3:-1:1;', 'r__'
  'lang', 'l83', 'r__ = 1:-1:3;', 'r__'
  'lang', 'l84', 'r__ = 0:0.1:0.5;', 'r__'
  'lang', 'l85', 'r__ = -1:1;', 'r__'
  'lang', 'l86', 'r__ = 5:5;', 'r__'
  'lang', 'l87', 'r__ = 1.5:3;', 'r__'
  'lang', 'l88', 'r__ = size(1:0);', 'r__'
  'lang', 'l89', 'r__ = size(zeros(1, 0) + 1);', 'r__'
  'lang', 'l90', 'r__ = ''a'' + ''b'';', 'r__'
  'lang', 'l91', 'r__ = ''abc'' == ''abc'';', 'r__'
  'lang', 'l92', 'r__ = ''abc'' == ''a'';', 'r__'
  'lang', 'l93', 'r__ = true + true;', 'r__'
  'lang', 'l94', 'r__ = true * 3;', 'r__'
  'lang', 'l95', 'r__ = class(true & true);', 'r__'
  'lang', 'l96', 'r__ = class(1 & 2);', 'r__'
  'lang', 'l97', 'r__ = class(''a'' == ''a'');', 'r__'
  'lang', 'l98', 'r__ = xor(true, [true false]);', 'r__'
  'lang', 'l99', 'r__ = ~[1 0 2];', 'r__'
  'lang', 'l100', 'r__ = 3 > 2 > 1;', 'r__'
  'lang', 'l101', 'r__ = 1 < 2 < 3;', 'r__'
  'lang', 'l102', 'r__ = [] == [];', 'r__'
  'lang', 'l103', 'r__ = isempty([] == 1);', 'r__'
  'lang', 'l104', 'r__ = 1 / 0 - 1 / 0;', 'r__'
  'lang', 'l105', 'r__ = 0 * Inf;', 'r__'
  'lang', 'l106', 'r__ = Inf - Inf;', 'r__'
  'lang', 'l107', 'r__ = mod(-7, 3);', 'r__'
  'lang', 'l108', 'r__ = rem(-7, 3);', 'r__'
  'lang', 'l109', 'r__ = mod(7, -3);', 'r__'
  'lang', 'l110', 'r__ = rem(7, -3);', 'r__'
  'lang', 'l111', 'r__ = mod(5.5, -2);', 'r__'
  'lang', 'l112', 'r__ = mod(-1, 1);', 'r__'
  'lang', 'l113', 'r__ = fix(-7 / 2);', 'r__'
  'lang', 'l114', 'r__ = round(-7 / 2);', 'r__'
  'lang', 'l115', 'r__ = [1 2; 3 4] * [5; 6];', 'r__'
  'lang', 'l116', 'r__ = [1 2; 3 4] .* [5 6; 7 8];', 'r__'
  'lang', 'l117', 'r__ = [1 2; 3 4] ^ 2;', 'r__'
  'lang', 'l118', 'r__ = [1 2; 3 4] .^ 2;', 'r__'
  'lang', 'l119', 'r__ = 2 .^ [1 2; 3 4];', 'r__'
  'lang', 'l120', 'r__ = [1 2; 3 4] \ [5; 6];', 'r__'
  'lang', 'l121', 'r__ = [5 6] / [1 2; 3 4];', 'r__'
  'lang', 'l122', 'r__ = [1 2; 3 4] ^ -1;', 'r__'
  'lang', 'l123', 'r__ = [4 1; 1 3] ^ 0.5;', 'r__'
  'lang', 'l124', 'r__ = 2 ^ [1 2; 3 4];', 'r__'
  'lang', 'l125', 'r__ = (-8) ^ (1/3);', 'r__'
  'lang', 'l126', 'r__ = [1 2 3] * 2;', 'r__'
  'lang', 'l127', 'r__ = [1 2 3] / 2;', 'r__'
  'lang', 'l128', 'r__ = 2 ./ [1 2 4];', 'r__'
  'lang', 'l129', 'r__ = [2 4] .\ [8 8];', 'r__'
  'lang', 'l130', 'r__ = true | false;', 'r__'
  'lang', 'l131', 'r__ = [1 0 1] & [1 1 0];', 'r__'
  'lang', 'l132', 'r__ = any([0 0 1]);', 'r__'
  'lang', 'l133', 'r__ = all([1 1 0]);', 'r__'
  'lang', 'l134', 'r__ = 1e308 * 10;', 'r__'
  'lang', 'l135', 'r__ = -1e308 * 10;', 'r__'
  'lang', 'l136', 'r__ = realmax;', 'r__'
  'lang', 'l137', 'r__ = realmin;', 'r__'
  'lang', 'l138', '[m, i] = max([3 7 7 1]);', 'i'
  'lang', 'l139', '[m, i] = min([4 2 2 9]);', 'i'
  'lang', 'l140', '[m, i] = max([1 NaN 3]);', 'i'
  'lang', 'l141', '[m, i] = max([NaN NaN]);', 'i'
  'lang', 'l142', '[m, i] = max(magic(3));', 'i'
  'lang', 'l143', '[m, i] = max(magic(3), [], 2);', 'i'
  'lang', 'l144', '[s, i] = sort([3 1 2; 9 7 8], 2);', 'i'
  'lang', 'l145', '[s, i] = sort([2 1 2 1]);', 'i'
  'lang', 'l146', '[s, i] = sort([2 1 2 1], ''descend'');', 'i'
  'lang', 'l147', '[u, i, j] = unique([3 1 3 2]);', 'i'
  'lang', 'l148', '[u, i, j] = unique([3 1 3 2]);', 'j'
  'lang', 'l149', '[u, i, j] = unique([3 1 3 2], ''stable'');', 'u'
  'lang', 'l150', '[u, i] = unique([3 1 3 2], ''last'');', 'i'
  'lang', 'l151', '[u, i, j] = unique([1 2; 1 2; 3 4], ''rows'');', 'u'
  'lang', 'l152', '[tf, loc] = ismember([1 5 3], [3 1 1]);', 'loc'
  'lang', 'l153', '[tf, loc] = ismember({''a'', ''z''}, {''z'', ''a''});', 'loc'
  'lang', 'l154', '[r, c] = find([0 1; 1 0]);', 'c'
  'lang', 'l155', '[r, c, v] = find([0 2; 3 0]);', 'v'
  'lang', 'l156', '[q, r] = deconv([1 5 6], [1 2]);', 'r'
  'lang', 'l157', '[n, x] = hist([1 2 2 3 3 3]);', 'x'
  'lang', 'l158', '[n, x] = hist([1 2 2 3 3 3], 3);', 'n'
  'lang', 'l159', '[r, c] = size(ones(2, 3, 1));', 'c'
  'lang', 'l160', '[a, b, c] = size(ones(2, 3));', 'c'
  'lang', 'l161', 'r__ = n = size(ones(2, 3), 3);', 'r__'
  'lang', 'l162', '[q, r] = qr([1 2; 3 4], 0);', 'q'
  'lang', 'l163', '[f, e] = log2([1 0.5 10]);', 'e'
  'lang', 'l164', '[n, d] = rat([0.5 0.333]);', 'd'
  'lang', 'l165', '[c, ia, ib] = intersect([1 2 3], [3 1]);', 'ib'
  'lang', 'l166', '[c, ia] = setdiff([5 4 3], 4);', 'ia'
  'lang', 'l167', 'r__ = sort([3 1 2], 2, ''descend'');', 'r__'
  'lang', 'l168', 'r__ = sort({''b'', ''a'', ''C''});', 'r__'
  'lang', 'l169', 'r__ = sort(''hello'');', 'r__'
  'lang', 'l170', 'r__ = unique({''b'', ''a'', ''b''});', 'r__'
  'lang', 'l171', 'r__ = unique([1 NaN NaN]);', 'r__'
  'lang', 'l172', 'r__ = max([1 2; 3 4], [], 1);', 'r__'
  'lang', 'l173', 'r__ = sum([1 2; 3 4], 2);', 'r__'
  'lang', 'l174', 'r__ = cumsum([1 2 3], 2);', 'r__'
  'lang', 'l175', 'r__ = mean([1 2; 3 4], 1);', 'r__'
  'lang', 'l176', 'r__ = any([0 0; 0 1], 2);', 'r__'
  'lang', 'l177', 'r__ = prod([1 2; 3 4], 2);', 'r__'
  'lang', 'l178', 'r__ = strsplit(''a b  c'');', 'r__'
  'lang', 'l179', 'r__ = strsplit(''a-b_c'', {''-'', ''_''});', 'r__'
  'lang', 'l180', 'r__ = strjoin({''a'', ''b''});', 'r__'
  'lang', 'l181', 'r__ = regexp(''abc123def'', ''\d+'', ''match'');', 'r__'
  'lang', 'l182', 'r__ = regexp(''abc123'', ''(\w)(\d)'', ''tokens'');', 'r__'
  'lang', 'l183', 'r__ = regexp(''key=val'', ''(?<k>\w+)=(?<v>\w+)'', ''names'');', 'r__'
  'lang', 'l184', 'r__ = regexp(''a1b2'', ''\d'', ''split'');', 'r__'
  'lang', 'l185', 'r__ = regexp(''aaa'', ''a'', ''once'');', 'r__'
  'lang', 'l186', 'r__ = regexprep(''hello world'', ''(\w+) (\w+)'', ''$2 $1'');', 'r__'
  'lang', 'l187', 'r__ = regexprep(''abc'', ''(.)'', ''$1$1'');', 'r__'
  'lang', 'l188', 'r__ = regexpi(''ABC'', ''b'', ''match'');', 'r__'
  'lang', 'l189', 'r__ = strtrim({'' a '', ''b ''});', 'r__'
  'lang', 'l190', 'r__ = upper(''mixed Case 1'');', 'r__'
  'lang', 'l191', 'r__ = fliplr(''abc'');', 'r__'
  'lang', 'l192', 'r__ = strcat(''a '', ''b '');', 'r__'
  'lang', 'l193', 'r__ = strcat({''a ''}, ''b '');', 'r__'
  'lang', 'l194', 'r__ = [''a '', ''b ''];', 'r__'
  'lang', 'l195', 'r__ = char(''a'', '''', ''bcd'');', 'r__'
  'lang', 'l196', 'r__ = num2str([1.5 2; 3 4.25]);', 'r__'
  'lang', 'l197', 'r__ = num2str(-0.000123);', 'r__'
  'lang', 'l198', 'r__ = num2str(123456.789);', 'r__'
  'lang', 'l199', 'r__ = num2str(1e15);', 'r__'
  'lang', 'l200', 'r__ = num2str(1e16);', 'r__'
  'lang', 'l201', 'r__ = num2str(0.1);', 'r__'
  'lang', 'l202', 'r__ = num2str([0.1 0.22 0.333]);', 'r__'
  'lang', 'l203', 'r__ = num2str(pi, 10);', 'r__'
  'lang', 'l204', 'r__ = num2str(true);', 'r__'
  'lang', 'l205', 'r__ = num2str([1 2 3]'');', 'r__'
  'lang', 'l206', 'r__ = mat2str([1 -2.5; NaN Inf]);', 'r__'
  'lang', 'l207', 'r__ = mat2str(pi, 4);', 'r__'
  'lang', 'l208', 'r__ = mat2str([true false]);', 'r__'
  'lang', 'l209', 'r__ = mat2str(''it''''s'');', 'r__'
  'lang', 'l210', 'r__ = mat2str(magic(3) > 4);', 'r__'
  'lang', 'l211', 'r__ = int2str(-0.5);', 'r__'
  'lang', 'l212', 'r__ = int2str(0.5);', 'r__'
  'lang', 'l213', 'r__ = int2str(1.5);', 'r__'
  'lang', 'l214', 'r__ = sprintf(''%d'', [1 2 3]);', 'r__'
  'lang', 'l215', 'r__ = sprintf(''%d-%d\n'', [1 2; 3 4]);', 'r__'
  'lang', 'l216', 'r__ = sprintf(''%5.2f|'', pi);', 'r__'
  'lang', 'l217', 'r__ = sprintf(''%-8s|'', ''ab'');', 'r__'
  'lang', 'l218', 'r__ = sprintf(''%08.3f'', -pi);', 'r__'
  'lang', 'l219', 'r__ = sprintf(''%+d %+d'', 5, -5);', 'r__'
  'lang', 'l220', 'r__ = sprintf(''%e'', 12345.6789);', 'r__'
  'lang', 'l221', 'r__ = sprintf(''%E'', 0.000123);', 'r__'
  'lang', 'l222', 'r__ = sprintf(''%g %g %g'', 1e-5, 1e5, 123456789);', 'r__'
  'lang', 'l223', 'r__ = sprintf(''%G'', 1e-10);', 'r__'
  'lang', 'l224', 'r__ = sprintf(''%x %X %o'', 255, 255, 8);', 'r__'
  'lang', 'l225', 'r__ = sprintf(''%c%c%c'', 72, 105, 33);', 'r__'
  'lang', 'l226', 'r__ = sprintf(''%s'', ''abc'', ''def'');', 'r__'
  'lang', 'l227', 'r__ = sprintf(''%s=%d '', ''a'', 1, ''b'', 2);', 'r__'
  'lang', 'l228', 'r__ = sprintf(''%d %s'', 1, ''x'', 2);', 'r__'
  'lang', 'l229', 'r__ = sprintf(''%5s|%-5s|'', ''a'', ''b'');', 'r__'
  'lang', 'l230', 'r__ = sprintf(''%.3s'', ''abcdef'');', 'r__'
  'lang', 'l231', 'r__ = sprintf(''%d'', 1.5);', 'r__'
  'lang', 'l232', 'r__ = sprintf(''%i'', -3);', 'r__'
  'lang', 'l233', 'r__ = sprintf(''%u'', 7);', 'r__'
  'lang', 'l234', 'r__ = sprintf(''%f'', NaN);', 'r__'
  'lang', 'l235', 'r__ = sprintf(''%d'', Inf);', 'r__'
  'lang', 'l236', 'r__ = sprintf(''%5.1f'', -Inf);', 'r__'
  'lang', 'l237', 'r__ = sprintf(''%d %%'', 50);', 'r__'
  'lang', 'l238', 'r__ = sprintf(''a\tb'');', 'r__'
  'lang', 'l239', 'r__ = sprintf(''%*d'', 5, 3);', 'r__'
  'lang', 'l240', 'r__ = sprintf(''%.*f'', 2, pi);', 'r__'
  'lang', 'l241', 'r__ = sprintf(''%#o %#x'', 8, 255);', 'r__'
  'lang', 'l242', 'r__ = sprintf(''% d'', 5);', 'r__'
  'lang', 'l243', 'r__ = sprintf(''%s'', 65);', 'r__'
  'lang', 'l244', 'r__ = sprintf(''%d'', ''a'');', 'r__'
  'lang', 'l245', 'r__ = sprintf(''%f'', true);', 'r__'
  'lang', 'l246', 'r__ = sprintf('''');', 'r__'
  'lang', 'l247', 'r__ = sprintf(''%d'', []);', 'r__'
  'lang', 'l248', 'r__ = sprintf(''%.0f %.0f %.0f'', 0.5, 1.5, 2.5);', 'r__'
  'lang', 'l249', 'r__ = sprintf(''%.2f'', 2.675);', 'r__'
  'lang', 'l250', 'r__ = sprintf(''%.1f'', 0.05);', 'r__'
  'lang', 'l251', 'r__ = sprintf(''%10.4e'', 1);', 'r__'
  'lang', 'l252', 'r__ = sprintf(''%g'', 100000);', 'r__'
  'lang', 'l253', 'r__ = sprintf(''%g'', 1000000);', 'r__'
  'lang', 'l254', 'r__ = sprintf(''%g'', 0.0001);', 'r__'
  'lang', 'l255', 'r__ = sprintf(''%g'', 0.00001);', 'r__'
  'lang', 'l256', 'r__ = str2num(''[1 2; 3 4]'');', 'r__'
  'lang', 'l257', 'r__ = str2num(''3+4'');', 'r__'
  'lang', 'l258', 'r__ = str2double(''1e-3'');', 'r__'
  'lang', 'l259', 'r__ = str2double('' 42 '');', 'r__'
  'lang', 'l260', 'r__ = str2double(''1 2'');', 'r__'
  'lang', 'l261', 'r__ = str2double(''.5'');', 'r__'
  'lang', 'l262', 'r__ = str2double(''-.5e2'');', 'r__'
  'lang', 'l263', 'r__ = num2str(str2double(''7''));', 'r__'
  'lang', 'l264', 'r__ = strcmp({''a'', ''b''}, {''a'', ''c''});', 'r__'
  'lang', 'l265', 'r__ = strncmp(''abcdef'', ''abcxyz'', 3);', 'r__'
  'lang', 'l266', 'r__ = strncmpi(''ABCdef'', ''abcxyz'', 3);', 'r__'
  'lang', 'l267', 'r__ = isspace(''a b'');', 'r__'
  'lang', 'l268', 'r__ = isletter(''a1B'');', 'r__'
  'lang', 'l269', 'r__ = isstrprop(''a1 '', ''digit'');', 'r__'
  'lang', 'l270', 'r__ = lower({''AB'', ''Cd''});', 'r__'
  'lang', 'l271', 'r__ = blanks(3);', 'r__'
  'lang', 'l272', 'r__ = deblank(''ab   '');', 'r__'
  'lang', 'l273', 'r__ = fliplr('''');', 'r__'
  'lang', 'l274', 'r__ = double(''é'');', 'r__'
  'lang', 'l275', 'r__ = char(233);', 'r__'
  'lang', 'l276', 'r__ = dec2bin(10);', 'r__'
  'lang', 'l277', 'r__ = bin2dec(''1010'');', 'r__'
  'lang', 'l278', 'r__ = dec2hex(255);', 'r__'
  'lang', 'l279', 'r__ = hex2dec(''FF'');', 'r__'
  'lang', 'l280', 'r__ = floor(-0.5);', 'r__'
  'lang', 'l281', 'r__ = round(0.49999999999999994);', 'r__'
  'lang', 'l282', 'r__ = round(-2.5);', 'r__'
  'lang', 'l283', 'r__ = fix(-2.5);', 'r__'
  'lang', 'l284', 'r__ = abs(-0);', 'r__'
  'lang', 'l285', 'r__ = sign(-0);', 'r__'
  'lang', 'l286', 'r__ = 1 / -0;', 'r__'
  'lang', 'l287', 'r__ = atan2(0, -0);', 'r__'
  'lang', 'l288', 'r__ = sqrt(-0);', 'r__'
  'lang', 'l289', 'r__ = max(NaN, 1);', 'r__'
  'lang', 'l290', 'r__ = min([NaN 1 NaN]);', 'r__'
  'lang', 'l291', 'r__ = sum([]);', 'r__'
  'lang', 'l292', 'r__ = sum([], 1);', 'r__'
  'lang', 'l293', 'r__ = sum([], 2);', 'r__'
  'lang', 'l294', 'r__ = sum(zeros(0, 3), 2);', 'r__'
  'lang', 'l295', 'r__ = prod(zeros(0, 3));', 'r__'
  'lang', 'l296', 'r__ = mean(zeros(0, 3));', 'r__'
  'lang', 'l297', 'r__ = max(zeros(0, 3), [], 2);', 'r__'
  'lang', 'l298', 'r__ = cumsum(zeros(2, 0));', 'r__'
  'lang', 'l299', 'r__ = any(zeros(0, 3));', 'r__'
  'lang', 'l300', 'r__ = eps(1e10);', 'r__'
  'lang', 'l301', 'r__ = eps(-1);', 'r__'
  'lang', 'l302', 'r__ = eps(Inf);', 'r__'
  'lang', 'l303', 'r__ = eps(NaN);', 'r__'
  'lang', 'l304', 'r__ = nextpow2(1000);', 'r__'
  'lang', 'l305', 'r__ = nextpow2(0);', 'r__'
  'lang', 'l306', 'r__ = factorial(171);', 'r__'
  'lang', 'l307', 'r__ = factorial(170);', 'r__'
  'lang', 'l308', 'r__ = nchoosek(30, 15);', 'r__'
  'lang', 'l309', 'r__ = gamma(171.5);', 'r__'
  'lang', 'l310', 'r__ = exp(710);', 'r__'
  'lang', 'l311', 'r__ = log(0);', 'r__'
  'lang', 'l312', 'r__ = log(-0);', 'r__'
  'lang', 'l313', 'r__ = log10(-10);', 'r__'
  'lang', 'l314', 'r__ = sqrt(-4) * 1i;', 'r__'
  'lang', 'l315', 'r__ = (1+2i) * (3-4i);', 'r__'
  'lang', 'l316', 'r__ = (1+2i) / (3-4i);', 'r__'
  'lang', 'l317', 'r__ = abs(3+4i);', 'r__'
  'lang', 'l318', 'r__ = angle(-1-0i);', 'r__'
  'lang', 'l319', 'r__ = conj([1+2i 3]);', 'r__'
  'lang', 'l320', 'r__ = real(''a'');', 'r__'
  'lang', 'l321', 'r__ = imag(5);', 'r__'
  'lang', 'l322', 'r__ = complex(1, 0) == 1;', 'r__'
  'lang', 'l323', 'r__ = isreal(complex(1, 0) + 0);', 'r__'
  'lang', 'l324', 'r__ = isreal([1+0i 2]);', 'r__'
  'lang', 'l325', 'r__ = isreal(sqrt(-1) * 0);', 'r__'
  'lang', 'l326', 'r__ = 1i^2;', 'r__'
  'lang', 'l327', 'r__ = exp(1i * pi);', 'r__'
  'lang', 'l328', 'r__ = linspace(0, 1, 3)'';', 'r__'
  'lang', 'l329', 'r__ = linspace(1, 0, 3);', 'r__'
  'lang', 'l330', 'r__ = colon(1, 3);', 'r__'
  'lang', 'l331', 'r__ = det([1 2; 3 4]);', 'r__'
  'lang', 'l332', 'r__ = inv([1 2; 3 4]);', 'r__'
  'lang', 'l333', 'r__ = rank([1 2; 2 4]);', 'r__'
  'lang', 'l334', 'r__ = trace([1 2; 3 4]);', 'r__'
  'lang', 'l335', 'r__ = norm([1 2; 3 4]);', 'r__'
  'lang', 'l336', 'r__ = norm([1 2 3], 1);', 'r__'
  'lang', 'l337', 'r__ = norm([1 2 3], Inf);', 'r__'
  'lang', 'l338', 'r__ = norm([1 2 3], -Inf);', 'r__'
  'lang', 'l339', 'r__ = cond([1 2; 3 4]);', 'r__'
  'lang', 'l340', 'r__ = kron(eye(2), [1 2]);', 'r__'
  'lang', 'l341', 'r__ = cross([1 2 3], [4 5 6]);', 'r__'
  'lang', 'l342', 'r__ = dot([1 2; 3 4], [1 2; 3 4]);', 'r__'
  'lang', 'l343', 'r__ = triu(magic(4), -1);', 'r__'
  'lang', 'l344', 'r__ = tril(magic(4), 1);', 'r__'
  'lang', 'l345', 'r__ = diag(magic(3), -1);', 'r__'
  'lang', 'l346', 'r__ = trace(magic(4));', 'r__'
  'lang', 'l347', 'r__ = expm(zeros(2));', 'r__'
  'lang', 'l348', 'r__ = polyfit(1:5, [2 4 6 8 10], 1);', 'r__'
  'lang', 'l349', 'r__ = polyval([1 2 3], 2);', 'r__'
  'lang', 'l350', 'r__ = roots([1 -3 2]);', 'r__'
  'lang', 'l351', 'r__ = conv([1 2], [1 3]);', 'r__'
  'lang', 'l352', 'r__ = filter([1 1], 1, [1 2 3]);', 'r__'
  'lang', 'l353', 'r__ = filter(1, [1 -0.5], [1 0 0]);', 'r__'
  'lang', 'l354', 'r__ = interp1([1 2 3], [4 5 6], 1.5);', 'r__'
  'lang', 'l355', 'r__ = cumprod([1 2 3 4]);', 'r__'
  'lang', 'l356', 'r__ = diff([1 4 9], 1, 2);', 'r__'
  'lang', 'l357', 'r__ = trapz([0 1 2], [0 1 4]);', 'r__'
  'lang', 'l358', 'r__ = histc([1 2 2 3 5], 1:5);', 'r__'
  'lang', 'l359', 'r__ = accumarray([1; 2; 1], [10; 20; 30]);', 'r__'
  'lang', 'l360', 'r__ = median([3 1 2; 6 5 4]);', 'r__'
  'lang', 'l361', 'r__ = mode([1 1 2 2]);', 'r__'
  'lang', 'l362', 'r__ = var([1 2 3 4], 1);', 'r__'
  'lang', 'l363', 'r__ = std([1 2; 3 4]);', 'r__'
  'lang', 'l364', 'r__ = var([2 4 4 4 5 5 7 9], [], 2);', 'r__'
  'lang', 'l365', 'r__ = cov([1 2 3], [1 2 4]);', 'r__'
  'lang', 'l366', 'r__ = corrcoef([1 2 3], [3 2 1]);', 'r__'
  'lang', 'l367', 'r__ = primes(30);', 'r__'
  'lang', 'l368', 'r__ = isprime([2 4 97]);', 'r__'
  'lang', 'l369', 'r__ = factor(84);', 'r__'
  'lang', 'l370', 'r__ = gcd([12 15], 9);', 'r__'
  'langerr', 'le1', 'x = [1 2 3]; x(1.5) = 1;', ''
  'langerr', 'le2', 'x = [1 2 3]; x(-1);', ''
  'langerr', 'le3', 'x = [1 2 3]; x(0) = 1;', ''
  'langerr', 'le4', 'A = magic(3); A(:, 4);', ''
  'langerr', 'le5', 'A = magic(3); A(4, :);', ''
  'langerr', 'le6', 'A = magic(3); A(1, 2, 3);', ''
  'langerr', 'le7', 'A = magic(3); A([1 2], :) = [1 2 3];', ''
  'langerr', 'le8', 'x = 1:3; x(5) = [];', ''
  'langerr', 'le9', 'A = magic(3); A(2, 2) = [];', ''
  'langerr', 'le10', 'c = {1}; c{2};', ''
  'langerr', 'le11', 'c = {1, 2}; x = c{:};', ''
  'langerr', 'le12', 's.a = 1; s(3).b;', ''
  'langerr', 'le13', 's = struct(''a'', {1, 2}); s.a;', ''
  'langerr', 'le14', 's = 5; s.a = 1;', ''
  'langerr', 'le15', 'x = ''abc''; x.y;', ''
  'langerr', 'le16', 'f = @(x) x; f.a;', ''
  'langerr', 'le17', 'x = {1} + 1;', ''
  'langerr', 'le18', 'x = struct(''a'', 1) + 1;', ''
  'langerr', 'le19', 'x = @sin + 1;', ''
  'langerr', 'le20', '[1 2 3] * [4 5 6];', ''
  'langerr', 'le21', '[1 2] + [1 2 3]'';', ''
  'langerr', 'le22', 'ones(2, 3) \ ones(3, 1);', ''
  'langerr', 'le23', '[1 2; 3 4] ^ [1 2];', ''
  'langerr', 'le24', 'x = [1, 2; 3];', ''
  'langerr', 'le25', 'x = [[1 2]; [3 4 5]];', ''
  'langerr', 'le26', 'x = {1, 2; 3};', ''
  'langerr', 'le27', 'undefined_thing + 1;', ''
  'langerr', 'le28', 'sin;', ''
  'langerr', 'le29', 'sin();', ''
  'langerr', 'le30', 'sin(1, 2, 3);', ''
  'langerr', 'le31', 'zeros(-1);', ''
  'langerr', 'le32', 'ones(2, ''foo'');', ''
  'langerr', 'le33', 'cell(''a'');', ''
  'langerr', 'le34', 'magic(''a'', 2);', ''
  'langerr', 'le35', 'str2func(5);', ''
  'langerr', 'le36', 'feval(''nonexistent_fn'');', ''
  'langerr', 'le37', 'error(''Custom message'');', ''
  'langerr', 'le38', 'error(''a:b'', ''With id %d'', 3);', ''
  'langerr', 'le39', 'error(''%s'', ''percent'');', ''
  'langerr', 'le40', 'error(struct(''message'', ''from struct'', ''identifier'', ''x:y''));', ''
  'langerr', 'le41', 'assert(false);', ''
  'langerr', 'le42', 'assert(false, ''fail %d'', 2);', ''
  'langerr', 'le43', 'x = 1; x{1} = 2;', ''
  'langerr', 'le44', 'x = [1 2 3]; x(4);', ''
  'langerr', 'le45', 'x = 5; x(2, 2);', ''
  'langerr', 'le46', 'q = zeros(2); q(5);', ''
  'langerr', 'le47', 'n = numel(1, 2, 3, 4);', ''
  'langerr', 'le48', 'strcat(1, {2});', ''
  'langerr', 'le49', 'cell2mat({1, ''a''});', ''
  'langerr', 'le50', 'fieldnames(5);', ''
  'langerr', 'le51', 'if [1 0], end;', ''
  'langerr', 'le52', 'while [], end, x = 1;', ''
  'langerr', 'le53', 'switch {1}, case 1, end;', ''
  'langerr', 'le54', 'for k = {1, 2}, end, x = k;', ''
  'langerr', 'le55', 'x = 1; x(:, :, 2);', ''
};
for k = 1:size(cases, 1)
  writeCase(fid, cases{k, 1}, cases{k, 2}, cases{k, 3}, cases{k, 4});
end
% The library sweep: each function with no arguments, each single
% argument and (when it takes two) each pair.
sweep = {
  'abs', false
  'accumarray', true
  'acos', false
  'acosd', false
  'acosh', false
  'acot', false
  'acotd', false
  'acoth', false
  'acsc', false
  'acscd', false
  'acsch', false
  'all', true
  'allfinite', true
  'and', true
  'angle', false
  'any', true
  'anynan', true
  'arrayfun', true
  'asec', false
  'asecd', false
  'asech', false
  'asin', false
  'asind', false
  'asinh', false
  'atan', false
  'atan2', true
  'atan2d', true
  'atand', false
  'atanh', false
  'base2dec', true
  'beta', true
  'betainc', true
  'betaln', true
  'bin2dec', true
  'bounds', true
  'bsxfun', true
  'cat', true
  'ceil', false
  'cell', true
  'cell2mat', false
  'cellfun', true
  'cellstr', false
  'char', true
  'chol', true
  'circshift', true
  'class', false
  'colon', true
  'complex', true
  'cond', true
  'conj', false
  'contains', true
  'conv', true
  'conv2', true
  'corrcoef', true
  'cos', false
  'cosd', false
  'cosh', false
  'cot', false
  'cotd', false
  'coth', false
  'cov', true
  'cross', true
  'csc', false
  'cscd', false
  'csch', false
  'ctranspose', false
  'cummax', true
  'cummin', true
  'cumprod', true
  'cumsum', true
  'cumtrapz', true
  'dec2base', true
  'dec2bin', true
  'dec2hex', true
  'deconv', true
  'deg2rad', false
  'det', false
  'diag', true
  'diff', true
  'discretize', true
  'dot', true
  'double', false
  'eig', true
  'endsWith', true
  'eq', true
  'erf', false
  'erfc', false
  'erfcinv', false
  'erfcx', false
  'erfinv', false
  'exp', false
  'expm', false
  'expm1', false
  'eye', true
  'factor', false
  'factorial', false
  'fft', true
  'fft2', true
  'fftshift', true
  'fieldnames', true
  'fillmissing', true
  'filter', true
  'filter2', true
  'find', true
  'fix', false
  'flip', true
  'fliplr', false
  'flipud', false
  'floor', false
  'func2str', true
  'gamma', false
  'gammainc', true
  'gammaln', false
  'gcd', true
  'ge', true
  'getfield', true
  'gt', true
  'hex2dec', true
  'histc', true
  'histcounts', true
  'horzcat', true
  'hypot', true
  'ifft', true
  'ifft2', true
  'ifftshift', true
  'imag', false
  'ind2sub', true
  'int2str', false
  'interp1', true
  'interp2', true
  'intersect', true
  'inv', false
  'ipermute', true
  'isa', true
  'iscell', false
  'iscellstr', false
  'ischar', false
  'iscolumn', false
  'iscomplex', true
  'isempty', false
  'isequal', true
  'isequaln', true
  'isfield', true
  'isfinite', false
  'isinf', false
  'islogical', false
  'ismatrix', false
  'ismember', true
  'ismissing', true
  'isnan', false
  'isnumeric', false
  'isprime', false
  'isreal', false
  'isrow', false
  'isscalar', false
  'issorted', true
  'isstruct', false
  'isvector', false
  'kron', true
  'lcm', true
  'ldivide', true
  'le', true
  'length', false
  'linspace', true
  'log', false
  'log10', false
  'log1p', false
  'log2', false
  'logical', false
  'logspace', true
  'lower', false
  'lt', true
  'lu', true
  'magic', false
  'mat2str', true
  'max', true
  'mean', true
  'median', true
  'meshgrid', true
  'min', true
  'minus', true
  'mkpp', true
  'mldivide', true
  'mod', true
  'mode', true
  'movmax', true
  'movmean', true
  'movmedian', true
  'movmin', true
  'movprod', true
  'movstd', true
  'movsum', true
  'movvar', true
  'mpower', true
  'mrdivide', true
  'mtimes', true
  'nchoosek', true
  'ndgrid', true
  'ndims', false
  'ne', true
  'nextpow2', false
  'nnz', false
  'norm', true
  'normalize', true
  'not', false
  'nthroot', true
  'null', true
  'num2cell', true
  'num2str', true
  'numel', true
  'numfields', true
  'ones', true
  'or', true
  'orderfields', true
  'orth', true
  'pchip', true
  'perms', false
  'permute', true
  'pinv', true
  'plus', true
  'polyder', true
  'polyfit', true
  'polyint', true
  'polyval', true
  'pow2', true
  'power', true
  'ppval', true
  'prctile', true
  'primes', false
  'prod', true
  'psi', true
  'qr', true
  'quantile', true
  'rad2deg', false
  'range', true
  'rank', true
  'rat', true
  'rats', true
  'rdivide', true
  'real', false
  'reallog', false
  'realpow', true
  'realsqrt', false
  'regexp', true
  'regexpi', true
  'regexprep', true
  'rem', true
  'repmat', true
  'rescale', true
  'reshape', true
  'rmfield', true
  'rmmissing', true
  'roots', false
  'rot90', true
  'round', false
  'sec', false
  'secd', false
  'sech', false
  'setdiff', true
  'setfield', true
  'setxor', true
  'sign', false
  'sin', false
  'sind', false
  'sinh', false
  'size', true
  'sort', true
  'sortrows', true
  'spline', true
  'sprintf', true
  'sqrt', false
  'sqrtm', false
  'squeeze', false
  'standardizeMissing', true
  'startsWith', true
  'std', true
  'str2double', false
  'strcat', true
  'strcmp', true
  'strcmpi', true
  'strfind', true
  'strjoin', true
  'strrep', true
  'strsplit', true
  'strtrim', false
  'struct', true
  'struct2cell', true
  'sub2ind', true
  'sum', true
  'svd', true
  'tan', false
  'tand', false
  'tanh', false
  'times', true
  'trace', false
  'transpose', false
  'trapz', true
  'tril', true
  'triu', true
  'uminus', false
  'union', true
  'unique', true
  'unmkpp', false
  'uplus', false
  'upper', false
  'var', true
  'vecnorm', true
  'vertcat', true
  'xor', true
  'zeros', true
};
singles = {
  '[]'
  'zeros(1, 0)'
  'zeros(0, 3)'
  'NaN'
  'Inf'
  '-2'
  '0'
  '3'
  '2.5'
  '[1 NaN 3]'
  '1:5'
  '(1:5)'''
  '[4 -2; 1 3]'
  'magic(4)'
  '[1+2i 3-1i]'
  '1i'
  '''ab'''
  ''''''
  '[''ab''; ''cd'']'
  'true'
  '[true false]'
  '{1, ''a''}'
  '{''ab'', ''c''}'
  '{}'
  'struct(''a'', 1)'
  'struct([])'
  '@sin'
  '@(x) x + 1'
};
pairs = {
  '[4 -2; 1 3]', '[]'
  '[4 -2; 1 3]', '1'
  '[4 -2; 1 3]', '2'
  '[4 -2; 1 3]', '0'
  '[4 -2; 1 3]', '-1'
  '[4 -2; 1 3]', '0.5'
  '[4 -2; 1 3]', 'NaN'
  '[4 -2; 1 3]', '''all'''
  '[4 -2; 1 3]', '''ab'''
  '[4 -2; 1 3]', '{1}'
  '1:5', '[]'
  '1:5', '1'
  '1:5', '2'
  '1:5', '0'
  '1:5', '-1'
  '1:5', '0.5'
  '1:5', 'NaN'
  '1:5', '''all'''
  '1:5', '''ab'''
  '1:5', '{1}'
  '[]', '[]'
  '[]', '1'
  '[]', '2'
  '[]', '0'
  '[]', '-1'
  '[]', '0.5'
  '[]', 'NaN'
  '[]', '''all'''
  '[]', '''ab'''
  '[]', '{1}'
  '''ab''', '[]'
  '''ab''', '1'
  '''ab''', '2'
  '''ab''', '0'
  '''ab''', '-1'
  '''ab''', '0.5'
  '''ab''', 'NaN'
  '''ab''', '''all'''
  '''ab''', '''ab'''
  '''ab''', '{1}'
  '{''ab'', ''c''}', '[]'
  '{''ab'', ''c''}', '1'
  '{''ab'', ''c''}', '2'
  '{''ab'', ''c''}', '0'
  '{''ab'', ''c''}', '-1'
  '{''ab'', ''c''}', '0.5'
  '{''ab'', ''c''}', 'NaN'
  '{''ab'', ''c''}', '''all'''
  '{''ab'', ''c''}', '''ab'''
  '{''ab'', ''c''}', '{1}'
  '[1+2i 3-1i]', '[]'
  '[1+2i 3-1i]', '1'
  '[1+2i 3-1i]', '2'
  '[1+2i 3-1i]', '0'
  '[1+2i 3-1i]', '-1'
  '[1+2i 3-1i]', '0.5'
  '[1+2i 3-1i]', 'NaN'
  '[1+2i 3-1i]', '''all'''
  '[1+2i 3-1i]', '''ab'''
  '[1+2i 3-1i]', '{1}'
  'NaN', '[]'
  'NaN', '1'
  'NaN', '2'
  'NaN', '0'
  'NaN', '-1'
  'NaN', '0.5'
  'NaN', 'NaN'
  'NaN', '''all'''
  'NaN', '''ab'''
  'NaN', '{1}'
};
state = warning;
warning('off', 'all');
s = 0;
for f = 1:size(sweep, 1)
  arglists = [{''}; singles];
  if sweep{f, 2}, arglists = [arglists; strcat(pairs(:, 1), {', '}, pairs(:, 2))]; end
  for a = 1:numel(arglists)
    s = s + 1;
    writeCase(fid, 'sweep', sprintf('s%d', s), sprintf('r__ = %s(%s);', sweep{f, 1}, arglists{a}), 'r__');
  end
  if mod(f, 25) == 0, fprintf('  swept %d of %d functions\n', f, size(sweep, 1)); end
end
warning(state);
writeDisplay(fid, 'containers.m', {
  'c = {1, ''two''; [1 2 3], {4}}'
  's.name = ''Ada'';'
  's.age = 36;'
  's.scores = [90 85];'
  's'
  't = struct(''a'', {1, 2})'
  'f = @(x) x.^2 + 1'
  'g = @sin'
  'e = struct()'
});
writeDisplay(fid, 'containers2.m', {
  's.a = 1;'
  's.b = ''text'';'
  's.c = [1 2 3];'
  's.d = {1, ''two''};'
  's.e.inner = 5;'
  's'
  't = struct(''x'', {1, 2})'
  't(2)'
  'u = struct(''m'', magic(3))'
  'v = struct(''e'', {})'
  'w.f = @(x) x + 1;'
  'w'
});
writeDisplay(fid, 'empties.m', {
  'e = []'
  'z3 = zeros(0, 3)'
  'r = zeros(1, 0)'
  'c = zeros(0, 1)'
  'es = '''''
  'l = true(0, 2)'
  'ce = {}'
  'disp([])'
});
writeDisplay(fid, 'formats.m', {
  'format long'
  'p = pi'
  'v = [1/3 2/3]'
  'format short'
  'p = pi'
  '3 + 4'
  'ans * 2'
});
writeDisplay(fid, 'formats2.m', {
  'format long'
  'a = [pi; exp(1)]'
  'b = 1e-5'
  'c = [1 1e6]'
  'format short g'
  'e = [pi 1e6 1e-6]'
  'f = 123456789'
  'format long g'
  'g = pi'
  'h = [1/3 1e10]'
  'format short e'
  'k = pi'
  'format short'
});
writeDisplay(fid, 'numeric.m', {
  'x = 5'
  'y = -3.5'
  'z = pi'
  'b = 1e10'
  's = 1e-5'
  'n = NaN'
  'v = [1 2 3]'
  'w = [1.5 2.25 -3]'
  'q = [1 NaN Inf -Inf]'
  'big = [1 1e5]'
  'mix = [1 1000.5]'
  'tiny = [0.001 0.002]'
  'M = magic(3)'
  'M4 = magic(4)'
  'F = [1.5 2; 3 4]'
  'E = eye(2)*1e6'
  'neg = [-1 -2.5]'
  'col = [1; -2; 3]'
  'wide = 1:25'
  'c1 = 1 + 2i'
  'c2 = [1+2i 3-4.5i]'
  'c3 = sqrt(-2)'
});
writeDisplay(fid, 'numeric2.m', {
  'a = -5'
  'b = [1 -1]'
  'c = [100 2]'
  'd = [1000 2]'
  'e = [99999 1]'
  'f = 123456789'
  'g = 1e9'
  'h = [1 2.5 NaN]'
  'k = [1e-5 1]'
  'm = [1e5 1.5]'
  'n = -0.5'
  'p = [0.001 -0.002]'
  'q = 1e-10'
  'r = [1;2.5;-3]'
  's = [1e10 1]'
  't = [-1e5 2.5]'
  'u = 0.1 + 0.2'
  'v = [NaN NaN]'
  'w = [Inf -Inf]'
  'x = -Inf'
  'y = 1/3'
  'z = [1/3 2/3; 1 4/3]'
});
writeDisplay(fid, 'text.m', {
  't = true'
  'tf = [true false; false true]'
  'str = ''hello'''
  'cm = [''abc''; ''def'']'
  'disp(''plain text'')'
  'disp([1 2 3])'
  'disp(pi)'
  'fprintf(''%d apples, %.2f pears\n'', 3, 2.5)'
  'fprintf(''%s|'', ''a'', ''bc''); fprintf(''\n'')'
  'x = sprintf(''%5.1f'', [1.25 -2.5])'
});
writeDisplay(fid, 'text2.m', {
  'a = ''a'''
  'b = [''ab''; ''cd'']'
  'c = '''''''''
  'd = {''ab'', 1; [], {}}'
  'e = {[1 2 3], ''long text here''; true, @sin}'
  'f = true(2)'
  'g = [true; false]'
  'h = ''tab	in'''
  'k = {}'
  'm = cell(2, 1)'
  'n = {''''}'
  'p = num2str(pi)'
  'q = repmat(''-'', 1, 10)'
});
format short
format loose
fprintf(fid, '#END\n');
fprintf('Done: %d cases written to %s\n', size(cases, 1) + s, outfile);
end

function writeCase(fid, kind, id, code, name)
fprintf(fid, '@@ %s %s\n', kind, id);
fprintf(fid, 'code: %s\n', code);
lastwarn('');
try
  if isempty(name)
    runCode(code);
    fprintf(fid, 'noerror\n');
  else
    v = runCode(code, name);
    writeValue(fid, v, 0);
  end
catch err
  fprintf(fid, 'error: %s\n', oneLine(err.identifier));
  fprintf(fid, 'message: %s\n', oneLine(err.message));
end
[msg, wid] = lastwarn;
if ~isempty(msg), fprintf(fid, 'warning: %s | %s\n', wid, oneLine(msg)); end
end

function value__ = runCode(code__, name__)
eval(code__);
if nargin > 1, value__ = eval(name__); end
end

function writeValue(fid, v, depth)
pad = repmat(' ', 1, 2 * depth);
fprintf(fid, '%sclass: %s\n', pad, class(v));
fprintf(fid, '%ssize:%s\n', pad, sprintf(' %d', size(v)));
if isnumeric(v) || islogical(v) || ischar(v)
  x = double(v(:)).';
  n = min(numel(x), 60);
  fprintf(fid, '%sre:%s\n', pad, sprintf(' %.17g', real(x(1:n))));
  if ~isreal(v), fprintf(fid, '%sim:%s\n', pad, sprintf(' %.17g', imag(x(1:n)))); end
  if numel(x) > n, fprintf(fid, '%struncated: %d\n', pad, numel(x)); end
elseif iscell(v) && depth < 2
  for k = 1:min(numel(v), 20)
    fprintf(fid, '%scell %d\n', pad, k);
    writeValue(fid, v{k}, depth + 1);
  end
elseif isstruct(v)
  f = fieldnames(v);
  fprintf(fid, '%sfields:%s\n', pad, sprintf(' %s', f{:}));
elseif isa(v, 'function_handle')
  fprintf(fid, '%sfunc: %s\n', pad, func2str(v));
end
end

function writeDisplay(mw_fid, mw_file, mw_lines)
% Runs a display script line by line in one workspace, recording
% exactly what each line prints (format compact, as MatWeb shows).
format short
format compact
for mw_k = 1:numel(mw_lines)
  fprintf(mw_fid, '@@ display %s %d\n', mw_file, mw_k);
  fprintf(mw_fid, '>> %s\n', mw_lines{mw_k});
  try
    mw_out = evalc(mw_lines{mw_k});
  catch mw_err
    mw_out = sprintf('Error: %s\n', mw_err.message);
  end
  fprintf(mw_fid, '%s', mw_out);
  fprintf(mw_fid, '@@ enddisplay\n');
end
end

function s = oneLine(s)
s = strrep(strrep(s, char(13), ''), char(10), '\n');
end
