function matweb_reference(outfile)
%MATWEB_REFERENCE Record MATLAB's results for MatWeb's test cases.
%   matweb_reference writes matweb_reference.txt in the current folder;
%   matweb_reference(FILE) writes FILE. It takes a minute or two and
%   prints some warnings while it runs; that is expected.
%
%   Generated by tools/matlab/make-reference.mjs in the MatWeb repository;
%   do not edit by hand.
if nargin < 1, outfile = 'matweb_reference.txt'; end
fid = fopen(outfile, 'w');
if fid < 0, error('matweb_reference:open', 'Cannot open %s for writing.', outfile); end
closer = onCleanup(@() fclose(fid));
try, feature('hotlinks', 0); catch, end % plain text from evalc
fprintf(fid, '#MATWEB-REFERENCE 1\n');
fprintf(fid, '#VERSION %s\n', version);
fprintf(fid, '#COMPUTER %s\n', computer);
fprintf(fid, '#DATE %s\n', datestr(now, 31));
% Installed products, so functions from a missing toolbox can be told apart.
try
  products = ver;
  for k = 1:numel(products), fprintf(fid, '#PRODUCT %s %s\n', products(k).Name, products(k).Version); end
catch
end
fprintf('Recording MATLAB results for MatWeb in %s ...\n', outfile);
cases = {
  'contract', 'c1', 'r__ = floor([-1.5 2.5]);', 'r__'
  'contract', 'c2', 'r__ = ceil([-1.5 2.5]);', 'r__'
  'contract', 'c3', 'r__ = fix([-1.5 2.5]);', 'r__'
  'contract', 'c4', 'r__ = round([-2.5 2.5 0.5 -0.5]);', 'r__'
  'contract', 'c5', 'r__ = rem([5 -5], 3);', 'r__'
  'contract', 'c6', 'r__ = mod([5 -5], 3);', 'r__'
  'contract', 'c7', 'r__ = mod(5.5, 2);', 'r__'
  'contract', 'c8', 'r__ = rem(5, 0);', 'r__'
  'contract', 'c9', 'r__ = mod(5, 0);', 'r__'
  'contract', 'c10', 'r__ = hypot([3 5], [4 12]);', 'r__'
  'contract', 'c11', 'r__ = atan2(1, 1);', 'r__'
  'contract', 'c12', 'r__ = atan2(0, -1);', 'r__'
  'contract', 'c13', 'r__ = acos(0.5);', 'r__'
  'contract', 'c14', 'r__ = asin(1);', 'r__'
  'contract', 'c15', 'r__ = cosh(0);', 'r__'
  'contract', 'c16', 'r__ = sinh(1);', 'r__'
  'contract', 'c17', 'r__ = log2(8);', 'r__'
  'contract', 'c18', '[f, e] = log2(8);', 'f'
  'contract', 'c19', '[f, e] = log2(8);', 'e'
  'contract', 'c20', '[f, e] = log2([0.75 -3 0]);', 'f'
  'contract', 'c21', '[f, e] = log2([0.75 -3 0]);', 'e'
  'contract', 'c22', 'r__ = conj(1 + 2i);', 'r__'
  'contract', 'c23', 'r__ = angle(-1);', 'r__'
  'contract', 'c24', 'r__ = angle(1i);', 'r__'
  'contract', 'c25', 'r__ = uplus([1 -2]);', 'r__'
  'contract', 'c26', 'r__ = sign([-2 0 3 NaN]);', 'r__'
  'contract', 'c27', 'r__ = sqrt(-4);', 'r__'
  'contract', 'c28', 'r__ = nthroot(-8, 3);', 'r__'
  'contract', 'c29', 'r__ = log(-1);', 'r__'
  'contract', 'c30', 'r__ = exp(1);', 'r__'
  'contract', 'c31', 'r__ = power(2, [1 2 3]);', 'r__'
  'contract', 'c32', 'r__ = eps;', 'r__'
  'contract', 'c33', 'r__ = eps(1000);', 'r__'
  'contract', 'c34', 'r__ = eps(0);', 'r__'
  'contract', 'c35', 'r__ = Inf(2, 1);', 'r__'
  'contract', 'c36', 'r__ = inf(1, 3);', 'r__'
  'contract', 'c37', 'r__ = NaN(2);', 'r__'
  'contract', 'c38', 'r__ = 5 / 0;', 'r__'
  'contract', 'c39', 'r__ = -5 / 0;', 'r__'
  'contract', 'c40', 'r__ = 0 / 0;', 'r__'
  'contract', 'c41', 'r__ = ''a'' + 1;', 'r__'
  'contract', 'c42', 'r__ = true + true;', 'r__'
  'contract', 'c43', 'r__ = [1 2] == [1 3];', 'r__'
  'contract', 'c44', 'r__ = ~[1 0];', 'r__'
  'contract', 'c45', 'r__ = [65, ''b''];', 'r__'
  'contract', 'c46', 'r__ = [true, 2];', 'r__'
  'contract', 'c47', 'r__ = [''ab''; ''cd''];', 'r__'
  'contract', 'c48', 'r__ = horzcat(''ab'', ''c'');', 'r__'
  'contract', 'c49', 'r__ = cat(1, [1 2], [3 4]);', 'r__'
  'contract', 'c50', 'r__ = repmat(''ab'', 1, 2);', 'r__'
  'contract', 'c51', 'r__ = xor(true, false);', 'r__'
  'contract', 'c52', 'r__ = 1:0;', 'r__'
  'contract', 'c53', 'r__ = 0:0.1:0.3;', 'r__'
  'contract', 'c54', 'r__ = (1:3)'';', 'r__'
  'contract', 'c55', 'r__ = ctranspose([1+2i 3]);', 'r__'
  'contract', 'c56', 'r__ = transpose([1+2i 3]);', 'r__'
  'contract', 'c57', 'r__ = class(''a'');', 'r__'
  'contract', 'c58', 'r__ = class(true);', 'r__'
  'contract', 'c59', 'r__ = class({});', 'r__'
  'contract', 'c60', 'r__ = class(struct());', 'r__'
  'contract', 'c61', 'r__ = class(@sin);', 'r__'
  'contract', 'c62', 'r__ = iscell({});', 'r__'
  'contract', 'c63', 'r__ = iscell(1);', 'r__'
  'contract', 'c64', 'r__ = iscellstr({''a'', ''b''});', 'r__'
  'contract', 'c65', 'r__ = iscellstr({''a'', 1});', 'r__'
  'contract', 'c66', 'r__ = iscellstr({});', 'r__'
  'contract', 'c67', 'r__ = iscolumn([1; 2]);', 'r__'
  'contract', 'c68', 'r__ = iscolumn(5);', 'r__'
  'contract', 'c69', 'r__ = iscolumn(zeros(0, 1));', 'r__'
  'contract', 'c70', 'r__ = iscolumn([]);', 'r__'
  'contract', 'c71', 'r__ = isrow(1:3);', 'r__'
  'contract', 'c72', 'r__ = isrow(zeros(1, 0));', 'r__'
  'contract', 'c73', 'r__ = isrow([]);', 'r__'
  'contract', 'c74', 'r__ = isvector(5);', 'r__'
  'contract', 'c75', 'r__ = isvector([]);', 'r__'
  'contract', 'c76', 'r__ = isvector(zeros(1, 0));', 'r__'
  'contract', 'c77', 'r__ = isvector(ones(2));', 'r__'
  'contract', 'c78', 'r__ = isscalar([]);', 'r__'
  'contract', 'c79', 'r__ = isscalar(''a'');', 'r__'
  'contract', 'c80', 'r__ = ismatrix([]);', 'r__'
  'contract', 'c81', 'r__ = iscomplex(1i);', 'r__'
  'contract', 'c82', 'r__ = iscomplex(complex(1, 0));', 'r__'
  'contract', 'c83', 'r__ = iscomplex(1);', 'r__'
  'contract', 'c84', 'r__ = islogical(true);', 'r__'
  'contract', 'c85', 'r__ = islogical(1);', 'r__'
  'contract', 'c86', 'r__ = isnumeric(1);', 'r__'
  'contract', 'c87', 'r__ = isnumeric(''a'');', 'r__'
  'contract', 'c88', 'r__ = isnumeric(true);', 'r__'
  'contract', 'c89', 'r__ = isa(1, ''double'');', 'r__'
  'contract', 'c90', 'r__ = isa(1, ''numeric'');', 'r__'
  'contract', 'c91', 'r__ = isa(1, ''float'');', 'r__'
  'contract', 'c92', 'r__ = isa(true, ''numeric'');', 'r__'
  'contract', 'c93', 'r__ = isa(@sin, ''function_handle'');', 'r__'
  'contract', 'c94', 'r__ = isempty('''');', 'r__'
  'contract', 'c95', 'r__ = isempty('' '');', 'r__'
  'contract', 'c96', 'r__ = isempty(zeros(0, 3));', 'r__'
  'contract', 'c97', 'r__ = isequal(''a'', 97);', 'r__'
  'contract', 'c98', 'r__ = isequal([1 2], [1 2], [1 2]);', 'r__'
  'contract', 'c99', 'r__ = isequal(NaN, NaN);', 'r__'
  'contract', 'c100', 'r__ = isequaln(NaN, NaN);', 'r__'
  'contract', 'c101', 'r__ = ndims(5);', 'r__'
  'contract', 'c102', 'r__ = ndims([]);', 'r__'
  'contract', 'c103', 'r__ = size([]);', 'r__'
  'contract', 'c104', 'r__ = size(zeros(3, 0), 1);', 'r__'
  'contract', 'c105', '[r, c] = size(ones(2, 5));', 'c'
  'contract', 'c106', 'r__ = numel(''hello'');', 'r__'
  'contract', 'c107', 'r__ = length(zeros(3, 7));', 'r__'
  'contract', 'c108', 'r__ = length([]);', 'r__'
  'contract', 'c109', 'r__ = zeros(2, 0);', 'r__'
  'contract', 'c110', 'r__ = ones(0);', 'r__'
  'contract', 'c111', 'r__ = eye(2, 3);', 'r__'
  'contract', 'c112', 'r__ = reshape(1:6, 2, []);', 'r__'
  'contract', 'c113', 'r__ = reshape(1:6, [], 2);', 'r__'
  'contract', 'c114', 'r__ = linspace(0, 1, 5);', 'r__'
  'contract', 'c115', 'r__ = linspace(1, 1, 3);', 'r__'
  'contract', 'c116', 'r__ = linspace(0, 1, 1);', 'r__'
  'contract', 'c117', 'r__ = linspace(0, 1, 0);', 'r__'
  'contract', 'c118', 'r__ = logspace(0, 2, 3);', 'r__'
  'contract', 'c119', 'r__ = size(logspace(0, 2));', 'r__'
  'contract', 'c120', 'r__ = logspace(0, pi, 3);', 'r__'
  'contract', 'c121', 'r__ = logspace(1, 2, 1);', 'r__'
  'contract', 'c122', 'r__ = magic(3);', 'r__'
  'contract', 'c123', 'r__ = magic(4);', 'r__'
  'contract', 'c124', 'r__ = magic(0);', 'r__'
  'contract', 'c125', 'r__ = diag([1 2]);', 'r__'
  'contract', 'c126', 'r__ = diag([1 2; 3 4]);', 'r__'
  'contract', 'c127', 'r__ = diag([1 2], 1);', 'r__'
  'contract', 'c128', 'r__ = diag([1 2], -1);', 'r__'
  'contract', 'c129', 'r__ = diag([1 2 3; 4 5 6], 1);', 'r__'
  'contract', 'c130', 'r__ = tril(magic(3));', 'r__'
  'contract', 'c131', 'r__ = triu(magic(3), 1);', 'r__'
  'contract', 'c132', 'r__ = tril(ones(2, 3), -1);', 'r__'
  'contract', 'c133', 'r__ = circshift(1:5, 2);', 'r__'
  'contract', 'c134', 'r__ = circshift([1; 2; 3], -1);', 'r__'
  'contract', 'c135', 'r__ = fliplr(''abc'');', 'r__'
  'contract', 'c136', 'r__ = kron([1 2], [1; 1]);', 'r__'
  'contract', 'c137', 'r__ = cross([1 0 0], [0 1 0]);', 'r__'
  'contract', 'c138', 'r__ = cross([1; 0; 0], [0; 1; 0]);', 'r__'
  'contract', 'c139', 'r__ = dot([1 2 3], [4 5 6]);', 'r__'
  'contract', 'c140', 'r__ = sum([]);', 'r__'
  'contract', 'c141', 'r__ = sum(zeros(0, 3));', 'r__'
  'contract', 'c142', 'r__ = sum(zeros(3, 0));', 'r__'
  'contract', 'c143', 'r__ = prod([]);', 'r__'
  'contract', 'c144', 'r__ = mean([]);', 'r__'
  'contract', 'c145', 'r__ = max([]);', 'r__'
  'contract', 'c146', 'r__ = sum(true(1, 3));', 'r__'
  'contract', 'c147', 'r__ = sum(''ab'');', 'r__'
  'contract', 'c148', 'r__ = any([]);', 'r__'
  'contract', 'c149', 'r__ = all([]);', 'r__'
  'contract', 'c150', 'r__ = any([0 0; 0 1]);', 'r__'
  'contract', 'c151', 'r__ = cumsum([1 2; 3 4], 2);', 'r__'
  'contract', 'c152', 'r__ = cumprod([1 2 3]);', 'r__'
  'contract', 'c153', 'r__ = cumprod([1 2; 3 4]);', 'r__'
  'contract', 'c154', 'r__ = mean([1 2; 3 4]);', 'r__'
  'contract', 'c155', 'r__ = mean([1 2; 3 4], 2);', 'r__'
  'contract', 'c156', 'r__ = mean([1 2; 3 4], ''all'');', 'r__'
  'contract', 'c157', 'r__ = mean([1 NaN 3], ''omitnan'');', 'r__'
  'contract', 'c158', 'r__ = median([3 1 4 1 5]);', 'r__'
  'contract', 'c159', 'r__ = median([1 2 3 4]);', 'r__'
  'contract', 'c160', 'r__ = var([1 2 3 4]);', 'r__'
  'contract', 'c161', 'r__ = var([1 2 3 4], 1);', 'r__'
  'contract', 'c162', 'r__ = std([2 4 4 4 5 5 7 9]);', 'r__'
  'contract', 'c163', 'r__ = mode([1 2 2 3 3]);', 'r__'
  'contract', 'c164', 'r__ = max([1 NaN 3]);', 'r__'
  'contract', 'c165', 'r__ = min([NaN NaN]);', 'r__'
  'contract', 'c166', 'r__ = max([1 5; 7 2]);', 'r__'
  'contract', 'c167', '[m, i] = max([1 5; 7 2], [], 2);', 'i'
  'contract', 'c168', 'r__ = max([1 2], 1.5);', 'r__'
  'contract', 'c169', 'r__ = min([4 2 8], [], 2);', 'r__'
  'contract', 'c170', 'r__ = movmin([4 2 6 1 3], 3);', 'r__'
  'contract', 'c171', 'r__ = movprod([1 2 3 4], 2);', 'r__'
  'contract', 'c172', 'r__ = movvar([1 2 3 4 5], 3);', 'r__'
  'contract', 'c173', 'r__ = diff([1 4 9 16]);', 'r__'
  'contract', 'c174', 'r__ = diff([1 4 9 16], 2);', 'r__'
  'contract', 'c175', 'r__ = trapz([1 2 3]);', 'r__'
  'contract', 'c176', 'r__ = cumtrapz([1 2 3]);', 'r__'
  'contract', 'c177', 'r__ = find([0 1 0 1]);', 'r__'
  'contract', 'c178', 'r__ = find([0; 1; 1]);', 'r__'
  'contract', 'c179', 'r__ = find([0 0]);', 'r__'
  'contract', 'c180', 'r__ = find([0; 0]);', 'r__'
  'contract', 'c181', 'r__ = find([]);', 'r__'
  'contract', 'c182', 'r__ = find([1 1 1], 2);', 'r__'
  'contract', 'c183', 'r__ = sort([3 1 2], ''descend'');', 'r__'
  'contract', 'c184', '[s, i] = sort([3 1 2]);', 'i'
  'contract', 'c185', 'r__ = sort([3 NaN 1]);', 'r__'
  'contract', 'c186', 'r__ = sort([3 NaN 1], ''descend'');', 'r__'
  'contract', 'c187', 'r__ = unique([3 1 2 1]);', 'r__'
  'contract', 'c188', 'r__ = unique([3; 1; 1]);', 'r__'
  'contract', 'c189', 'r__ = ismember([1 5], [1 2 3]);', 'r__'
  'contract', 'c190', 'r__ = det(magic(3));', 'r__'
  'contract', 'c191', 'r__ = inv([2 0; 0 4]);', 'r__'
  'contract', 'c192', 'r__ = rank(magic(4));', 'r__'
  'contract', 'c193', 'r__ = trace(magic(3));', 'r__'
  'contract', 'c194', 'r__ = norm([3 4]);', 'r__'
  'contract', 'c195', 'r__ = norm([1 2; 3 4], ''fro'');', 'r__'
  'contract', 'c196', 'r__ = norm([1 2; 3 4], 1);', 'r__'
  'contract', 'c197', 'r__ = norm([1 2; 3 4], Inf);', 'r__'
  'contract', 'c198', 'r__ = svd([3 0; 0 4]);', 'r__'
  'contract', 'c199', 'r__ = pinv([1 2; 2 4]);', 'r__'
  'contract', 'c200', '[L, U, P] = lu([1 2; 3 4]);', 'L'
  'contract', 'c201', '[L, U, P] = lu([1 2; 3 4]);', 'U'
  'contract', 'c202', '[L, U, P] = lu([1 2; 3 4]);', 'P'
  'contract', 'c203', '[V, D] = eig([1 2; 3 4]);', 'V'
  'contract', 'c204', '[V, D] = eig([1 2; 3 4]);', 'D'
  'contract', 'c205', '[V, D] = eig([0 1; -1 0]);', 'V'
  'contract', 'c206', 'r__ = [2 0; 0 4] \ [2; 4];', 'r__'
  'contract', 'c207', 'r__ = [1 2] / [2 4];', 'r__'
  'contract', 'c208', 'r__ = [1 1; 0 1] ^ 3;', 'r__'
  'contract', 'c209', 'r__ = polyfit([1 2 3], [2 4 6], 1);', 'r__'
  'contract', 'c210', 'r__ = polyval([1 0 -1], 3);', 'r__'
  'contract', 'c211', 'r__ = conv([1 1], [1 -1]);', 'r__'
  'contract', 'c212', 'r__ = interp1([1 2 3], [10 20 30], 2.5);', 'r__'
  'contract', 'c213', 'r__ = interp1([1 2], [10 20], 3);', 'r__'
  'contract', 'c214', 'r__ = nchoosek(5, 2);', 'r__'
  'contract', 'c215', 'r__ = factorial(5);', 'r__'
  'contract', 'c216', 'r__ = primes(10);', 'r__'
  'contract', 'c217', 'r__ = isprime(1:5);', 'r__'
  'contract', 'c218', 'r__ = gcd(12, 18);', 'r__'
  'contract', 'c219', 'r__ = lcm(4, 6);', 'r__'
  'contract', 'c220', 'r__ = logical([2 0]);', 'r__'
  'contract', 'c221', 'r__ = double(''A'');', 'r__'
  'contract', 'c222', 'r__ = char(72);', 'r__'
  'contract', 'c223', 'r__ = char({''a'', ''bcd''});', 'r__'
  'contract', 'c224', 'r__ = char(''a'', ''bc'');', 'r__'
  'contract', 'c225', 'r__ = char([72 105]);', 'r__'
  'contract', 'c226', 'r__ = num2str(pi);', 'r__'
  'contract', 'c227', 'r__ = num2str(1e10);', 'r__'
  'contract', 'c228', 'r__ = num2str(-0.5);', 'r__'
  'contract', 'c229', 'r__ = num2str(true);', 'r__'
  'contract', 'c230', 'r__ = int2str(2.5);', 'r__'
  'contract', 'c231', 'r__ = mat2str([1 2; 3 4]);', 'r__'
  'contract', 'c232', 'r__ = mat2str(true);', 'r__'
  'contract', 'c233', 'r__ = mat2str([0.1 NaN Inf]);', 'r__'
  'contract', 'c234', 'r__ = sprintf(''%d'', 3.5);', 'r__'
  'contract', 'c235', 'r__ = sprintf(''%5.2f|'', [1 2]);', 'r__'
  'contract', 'c236', 'r__ = sprintf(''%d,'', [1 2; 3 4]);', 'r__'
  'contract', 'c237', 'r__ = upper(''abC'');', 'r__'
  'contract', 'c238', 'r__ = strtrim(sprintf('' a\t''));', 'r__'
  'contract', 'c239', 'r__ = strrep(''abcb'', ''b'', ''XY'');', 'r__'
  'contract', 'c240', 'r__ = regexprep(''abc'', ''b'', ''X'');', 'r__'
  'contract', 'c241', 'r__ = strjoin({''a'', ''b''}, ''-'');', 'r__'
  'contract', 'c242', 'r__ = strsplit(''a,b,,c'', '','');', 'r__'
  'contract', 'c243', 'r__ = strsplit(''a,b,,c'', '','', ''CollapseDelimiters'', false);', 'r__'
  'contract', 'c244', 'r__ = str2double(''3.5'');', 'r__'
  'contract', 'c245', 'r__ = str2double(''x'');', 'r__'
  'contract', 'c246', 'r__ = str2double({''1'', ''a''});', 'r__'
  'contract', 'c247', 'r__ = str2double(''1,000'');', 'r__'
  'contract', 'c248', 'r__ = str2double(''3abc'');', 'r__'
  'contract', 'c249', 'r__ = str2double(''-Inf'');', 'r__'
  'contract', 'c250', 'r__ = str2double(''1+2i'');', 'r__'
  'contract', 'c251', 'r__ = str2double(5);', 'r__'
  'contract', 'c252', 'r__ = strcmp(''a'', 97);', 'r__'
  'contract', 'c253', 'r__ = strcmpi(''ABC'', ''abc'');', 'r__'
  'contract', 'c254', 'r__ = strcmpi({''a'', ''B''}, ''b'');', 'r__'
  'contract', 'c255', 'r__ = strfind(''abcbc'', ''bc'');', 'r__'
  'contract', 'c256', 'r__ = strfind(''abc'', ''x'');', 'r__'
  'contract', 'c257', 'r__ = num2cell([1 2]);', 'r__'
  'contract', 'c258', 'r__ = cell2mat({1 2; 3 4});', 'r__'
  'contract', 'c259', 'r__ = isfield(struct(''a'', 1), {''a'', ''b''});', 'r__'
  'contract', 'c260', 'r__ = fieldnames(struct(''b'', 1, ''a'', 2));', 'r__'
  'contract', 'c261', 'r__ = struct2cell(struct(''a'', 1, ''b'', ''x''));', 'r__'
  'contract', 'c262', 'r__ = numfields(struct(''a'', 1, ''b'', 2));', 'r__'
  'contract', 'c263', 'r__ = getfield(struct(''a'', 5), ''a'');', 'r__'
  'contract', 'c264', 's = setfield(struct(''a'', 5), ''a'', 6); r = s.a;', 'r'
  'contract', 'c265', 'r__ = cellfun(@numel, {''ab'', ''cde'', ''''});', 'r__'
  'contract', 'c266', 'r__ = cellfun(@isempty, {});', 'r__'
  'contract', 'c267', 'r__ = arrayfun(@(x) x^2, [1 2 3]);', 'r__'
  'contract', 'c268', 'r__ = size(cell(2, 3));', 'r__'
  'error', 'e1', 'x = undefined_thing;', ''
  'error', 'e2', 'y = undefined_fn(3);', ''
  'error', 'e3', 'a = [1 2 3]; a(5);', ''
  'error', 'e4', 'a = [1 2 3]; a(0);', ''
  'error', 'e5', 'a = [1 2 3]; a(1.5);', ''
  'error', 'e6', 'A = magic(3); A(4, 1);', ''
  'error', 'e7', 'q = [1 2 3]; q(:, 4);', ''
  'error', 'e8', '[1 2] + [1 2 3];', ''
  'error', 'e9', '[1 2; 3 4] * [1 2 3];', ''
  'error', 'e10', 'zeros(2) \ [1 2 3]'';', ''
  'error', 'e11', '[1 2, [3; 4]];', ''
  'error', 'e12', '[1 2; 3];', ''
  'error', 'e13', 'x = 1; x{1};', ''
  'error', 'e14', 'c = {1}; c(2);', ''
  'error', 'e15', 's.a = 1; s.b;', ''
  'error', 'e16', 'f = @(x) x; f(1, 2);', ''
  'error', 'e17', 'sin(1, 2);', ''
  'error', 'e18', 'atan2(1);', ''
  'error', 'e19', 'circshift(1:3);', ''
  'error', 'e20', 'sin({1});', ''
  'error', 'e21', 'sum(struct(''a'', 1));', ''
  'error', 'e22', 'logical(NaN);', ''
  'error', 'e23', 'error(''my:id'', ''Custom %d'', 5);', ''
  'error', 'e24', 'error(''plain message'');', ''
  'probe', 'p1', 'r__ = diff(5);', 'r__'
  'probe', 'p2', 'r__ = unique([]);', 'r__'
  'probe', 'p3', 'r__ = find(0);', 'r__'
  'probe', 'p4', 'r__ = find(zeros(0, 3));', 'r__'
  'probe', 'p5', 'r__ = max(zeros(0, 3));', 'r__'
  'probe', 'p6', 'r__ = sort([]);', 'r__'
  'probe', 'p7', 'r__ = sprintf(''%.1f'', 0.25);', 'r__'
  'probe', 'p8', 'r__ = sprintf(''%.0f'', 0.5);', 'r__'
  'probe', 'p9', 'r__ = sprintf(''%.0f'', 2.5);', 'r__'
  'probe', 'p10', 'r__ = sprintf(''%.1f'', 1.25);', 'r__'
  'probe', 'p11', 'r__ = sprintf(''%5.1f'', [1.25 -2.5]);', 'r__'
  'probe', 'p12', 'r__ = sprintf(''%g'', 1e5);', 'r__'
  'probe', 'p13', 'r__ = sprintf(''%g'', 123456);', 'r__'
  'probe', 'p14', 'r__ = sprintf(''%x'', 255);', 'r__'
  'probe', 'p15', 'r__ = sprintf(''%5s|'', ''ab'');', 'r__'
  'probe', 'p16', 'r__ = sprintf(''%-5d|'', 3);', 'r__'
  'probe', 'p17', 'r__ = sprintf(''%+.2e'', -12345.678);', 'r__'
  'probe', 'p18', 'r__ = num2str(123456789);', 'r__'
  'probe', 'p19', 'r__ = num2str(0.1 + 0.2);', 'r__'
  'probe', 'p20', 'r__ = num2str([1 2; 3 4]);', 'r__'
  'probe', 'p21', 'r__ = num2str(-pi, 8);', 'r__'
  'probe', 'p22', 'r__ = num2str(pi, ''%10.5f'');', 'r__'
  'probe', 'p23', 'r__ = num2str(1e-10);', 'r__'
  'probe', 'p24', 'r__ = num2str(1+2i);', 'r__'
  'probe', 'p25', 'r__ = mat2str(pi);', 'r__'
  'probe', 'p26', 'r__ = mat2str(-0.5);', 'r__'
  'probe', 'p27', 'r__ = mat2str([1.5 -2]);', 'r__'
  'probe', 'p28', 'r__ = mat2str(1+2i);', 'r__'
  'probe', 'p29', 'r__ = mat2str(''abc'');', 'r__'
  'probe', 'p30', 'r__ = mat2str(zeros(0, 3));', 'r__'
  'probe', 'p31', 'r__ = int2str([1.5 -2.5]);', 'r__'
  'probe', 'p32', 'r__ = null(magic(4));', 'r__'
  'probe', 'p33', 'r__ = orth([1 1; 1 1]);', 'r__'
  'probe', 'p34', '[Q, R] = qr([1 2; 3 4]);', 'Q'
  'probe', 'p35', '[Q, R] = qr([1 2; 3 4]);', 'R'
  'probe', 'p36', '[V, D] = eig([2 1; 1 2]);', 'V'
  'probe', 'p37', '[V, D] = eig([1 2; 3 4]);', 'V'
  'probe', 'p38', 'r__ = eig([0 1; -1 0]);', 'r__'
  'probe', 'p39', 'r__ = roots([1 0 1]);', 'r__'
  'probe', 'p40', 'r__ = roots(reshape(magic(4), 1, []));', 'r__'
  'probe', 'p41', 'r__ = svd(magic(4));', 'r__'
  'probe', 'p42', '[U, S, V] = svd([1 2; 3 4; 5 6]);', 'U'
  'probe', 'p43', 'r__ = pinv(magic(4));', 'r__'
  'probe', 'p44', 'r__ = expm([0 1; -1 0]);', 'r__'
  'probe', 'p45', 'r__ = sqrtm([4 1; 1 3]);', 'r__'
  'probe', 'p46', 'r__ = sqrtm([1 2; 3 4]);', 'r__'
  'probe', 'p47', 'r__ = cellfun(@isempty, {});', 'r__'
  'probe', 'p48', 'r__ = cellfun(''isempty'', {});', 'r__'
  'probe', 'p49', 'r__ = iscellstr({});', 'r__'
  'probe', 'p50', 'r__ = isvector(zeros(1, 0));', 'r__'
  'probe', 'p51', 'r__ = logspace(0, pi, 3);', 'r__'
  'probe', 'p52', 'r__ = strsplit(''a,b,,c'', '','');', 'r__'
  'probe', 'p53', 'r__ = strjoin({''a'', ''b'', ''c''});', 'r__'
  'probe', 'p54', 'r__ = regexp(''ab12cd'', ''\d+'', ''match'');', 'r__'
  'probe', 'p55', 'r__ = regexprep(''aaa'', ''a'', ''b'', ''once'');', 'r__'
  'probe', 'p56', 'r__ = strtrim(sprintf('' \t a b \n''));', 'r__'
  'probe', 'p57', 'r__ = upper({''ab'', ''c''});', 'r__'
  'probe', 'p58', 'r__ = strrep({''aa'', ''ba''}, ''a'', ''x'');', 'r__'
  'probe', 'p59', 'r__ = fliplr({1, ''a'', 3});', 'r__'
  'probe', 'p60', 'r__ = fftshift({1, 2, 3});', 'r__'
  'probe', 'p61', 'r__ = mean(int8([1 2]));', 'r__'
  'probe', 'p62', 'r__ = class(true + true);', 'r__'
  'probe', 'p63', 'r__ = class([''a'' 66]);', 'r__'
  'probe', 'p64', 'r__ = class([true; 2]);', 'r__'
  'probe', 'p65', 'r__ = class({} == {});', 'r__'
  'probe', 'p66', 'r__ = isequal({1, 2}, {1, 2});', 'r__'
  'probe', 'p67', 'r__ = mod(-1, Inf);', 'r__'
  'probe', 'p68', 'r__ = mod(1, -Inf);', 'r__'
  'probe', 'p69', 'r__ = rem(-1, Inf);', 'r__'
  'probe', 'p70', 'r__ = atan2(-0, -1);', 'r__'
  'probe', 'p71', 'r__ = round(2.5);', 'r__'
  'probe', 'p72', 'r__ = round(-0.5);', 'r__'
  'probe', 'p73', 'r__ = sign(-0);', 'r__'
  'probe', 'p74', 'r__ = 1/-0;', 'r__'
  'probe', 'p75', 'r__ = max(-0, 0);', 'r__'
  'probe', 'p76', 'r__ = min([NaN 1], [], 2);', 'r__'
  'probe', 'p77', 'r__ = cumsum([1 NaN 2]);', 'r__'
  'probe', 'p78', 'r__ = cummax([1 NaN 3 2]);', 'r__'
  'probe', 'p79', 'r__ = median([1 NaN 3]);', 'r__'
  'probe', 'p80', 'r__ = median([1 NaN 3], ''omitnan'');', 'r__'
  'probe', 'p81', 'r__ = mode([]);', 'r__'
  'probe', 'p82', 'r__ = var(5);', 'r__'
  'probe', 'p83', 'r__ = std([]);', 'r__'
  'probe', 'p84', 'r__ = var([1 2; 3 4], [], 2);', 'r__'
  'probe', 'p85', 'r__ = histcounts([1 2 2 3 10]);', 'r__'
  'probe', 'p86', 'r__ = histcounts(randn(0, 1));', 'r__'
  'probe', 'p87', 'r__ = discretize([1 5 10], [0 5 10]);', 'r__'
  'probe', 'p88', 'r__ = accumarray([1; 3], [10; 20]);', 'r__'
  'probe', 'p89', 'r__ = prctile([1 2 3 4], [25 50 75]);', 'r__'
  'probe', 'p90', 'r__ = interp1([1 2 3], [4 5 6], [0 1.5 4], ''linear'', ''extrap'');', 'r__'
  'probe', 'p91', 'r__ = interp1([1 2 3], [4 5 6], 2.5, ''nearest'');', 'r__'
  'probe', 'p92', 'r__ = spline([0 1 2 3], [0 1 8 27], 1.5);', 'r__'
  'probe', 'p93', 'r__ = pchip([0 1 2 3], [0 1 8 27], 1.5);', 'r__'
  'probe', 'p94', 'r__ = polyfit([1 2 3 4], [1 4 9 16], 2);', 'r__'
  'probe', 'p95', 'r__ = polyval([1 2 3], [1 2; 3 4]);', 'r__'
  'probe', 'p96', 'r__ = conv([1 2 3], [1 1], ''same'');', 'r__'
  'probe', 'p97', 'r__ = filter(1, [1 -0.5], [1 1 1]);', 'r__'
  'probe', 'p98', 'r__ = deconv([1 3 3 1], [1 1]);', 'r__'
  'probe', 'p99', 'r__ = trapz([1 2; 3 4]);', 'r__'
  'probe', 'p100', 'r__ = cumtrapz([1 2; 3 4], 2);', 'r__'
  'probe', 'p101', 'r__ = nchoosek(1:4, 3);', 'r__'
  'probe', 'p102', 'r__ = perms([1 2 3]);', 'r__'
  'probe', 'p103', 'r__ = factor(360);', 'r__'
  'probe', 'p104', 'r__ = primes(1);', 'r__'
  'probe', 'p105', 'r__ = isprime(0:3);', 'r__'
  'probe', 'p106', '[n, d] = rat(0.75);', 'd'
  'probe', 'p107', 'r__ = rat(pi);', 'r__'
  'probe', 'p108', 'r__ = rats(0.75);', 'r__'
  'probe', 'p109', 'r__ = gcd([12 18], 8);', 'r__'
  'probe', 'p110', 'r__ = lcm(int8(4), 6);', 'r__'
  'probe', 'p111', 'r__ = erf(0.5);', 'r__'
  'probe', 'p112', 'r__ = gamma(0.5);', 'r__'
  'probe', 'p113', 'r__ = gamma(-1);', 'r__'
  'probe', 'p114', 'r__ = gammaln(0.5);', 'r__'
  'probe', 'p115', 'r__ = psi(1);', 'r__'
  'probe', 'p116', 'r__ = beta(2, 3);', 'r__'
  'probe', 'p117', 'r__ = betainc(0.5, 2, 3);', 'r__'
  'probe', 'p118', 'r__ = gammainc(1, 2);', 'r__'
  'probe', 'p119', 'r__ = erfinv(0.5);', 'r__'
  'probe', 'p120', 'r__ = fft([1 2 3]);', 'r__'
  'probe', 'p121', 'r__ = ifft([1 2 3]);', 'r__'
  'probe', 'p122', 'r__ = fft([1 0 0 0]);', 'r__'
  'probe', 'p123', 'r__ = fft2([1 2; 3 4]);', 'r__'
  'probe', 'p124', 'r__ = fftshift([1 2 3 4 5]);', 'r__'
  'probe', 'p125', 'r__ = ifftshift([1 2 3 4 5]);', 'r__'
  'probe', 'p126', 'r__ = intersect([3 1 2], [2 3 4]);', 'r__'
  'probe', 'p127', 'r__ = union({''b'', ''a''}, {''c'', ''a''});', 'r__'
  'probe', 'p128', 'r__ = setdiff([5 1 3 1], 1);', 'r__'
  'probe', 'p129', 'r__ = unique({''b'', ''a'', ''b''});', 'r__'
  'probe', 'p130', 'r__ = sortrows([3 1; 1 2; 3 0]);', 'r__'
  'probe', 'p131', 'r__ = issorted([1 2 2 3]);', 'r__'
  'probe', 'p132', 'r__ = movmean(1:5, 2);', 'r__'
  'probe', 'p133', 'r__ = movmedian([4 1 3 2], 3);', 'r__'
  'probe', 'p134', 'r__ = normalize([1 2 3]);', 'r__'
  'probe', 'p135', 'r__ = rescale([1 2 3]);', 'r__'
  'probe', 'p136', 'r__ = bounds([3 1 2]);', 'r__'
  'probe', 'p137', 'r__ = vecnorm([3 4; 6 8]);', 'r__'
  'probe', 'p138', 'r__ = cov([1 2 3; 4 6 5]);', 'r__'
  'probe', 'p139', 'r__ = corrcoef([1 2 3], [2 4 7]);', 'r__'
  'probe', 'p140', 'r__ = quantile([1 2 3 4], 0.5);', 'r__'
  'probe', 'p141', 'r__ = zeros(2, 0) * zeros(0, 3);', 'r__'
  'probe', 'p142', 'r__ = ones(0, 3) * ones(3, 2);', 'r__'
  'probe', 'p143', 'r__ = sum(zeros(2, 0), 2);', 'r__'
  'probe', 'p144', 'r__ = [] + 1;', 'r__'
  'probe', 'p145', 'r__ = [] == [];', 'r__'
  'probe', 'p146', 'r__ = isempty([] + []);', 'r__'
  'probe', 'p147', 'r__ = [''abc''] == ''abc'';', 'r__'
  'probe', 'p148', 'r__ = ''abc'' < ''b'';', 'r__'
  'probe', 'p149', 'r__ = ~[];', 'r__'
  'probe', 'p150', 'r__ = any(zeros(0, 3));', 'r__'
  'probe', 'p151', 'r__ = all(zeros(0, 3));', 'r__'
  'probe', 'p152', 'r__ = xor([1 0], [1 1]);', 'r__'
};
for k = 1:size(cases, 1)
  writeCase(fid, cases{k, 1}, cases{k, 2}, cases{k, 3}, cases{k, 4});
end
% The library sweep: each function with no arguments, each single
% argument and (when it takes two) each pair.
sweep = {
  'abs', false
  'accumarray', true
  'acos', false
  'acosd', false
  'acosh', false
  'acot', false
  'acotd', false
  'acoth', false
  'acsc', false
  'acscd', false
  'acsch', false
  'all', true
  'allfinite', true
  'and', true
  'angle', false
  'any', true
  'anynan', true
  'arg', false
  'arrayfun', true
  'asec', false
  'asecd', false
  'asech', false
  'asin', false
  'asind', false
  'asinh', false
  'atan', false
  'atan2', true
  'atan2d', true
  'atand', false
  'atanh', false
  'beta', true
  'betainc', true
  'betaln', true
  'bounds', true
  'bsxfun', true
  'cat', true
  'ceil', false
  'cell', true
  'cell2mat', true
  'cellfun', true
  'cellstr', true
  'char', true
  'chol', true
  'circshift', true
  'class', true
  'colon', true
  'complex', true
  'cond', true
  'conj', false
  'contains', true
  'conv', true
  'conv2', true
  'corrcoef', true
  'cos', false
  'cosd', false
  'cosh', false
  'cot', false
  'cotd', false
  'coth', false
  'cov', true
  'cross', true
  'csc', false
  'cscd', false
  'csch', false
  'ctranspose', true
  'cummax', true
  'cummin', true
  'cumprod', true
  'cumsum', true
  'cumtrapz', true
  'deconv', true
  'deg2rad', false
  'det', true
  'diag', true
  'diff', true
  'discretize', true
  'dot', true
  'double', true
  'eig', true
  'endsWith', true
  'eq', true
  'erf', true
  'erfc', true
  'erfcinv', true
  'erfcx', true
  'erfinv', true
  'exp', false
  'expm', true
  'expm1', false
  'eye', true
  'factor', true
  'factorial', true
  'fft', true
  'fft2', true
  'fftshift', true
  'fieldnames', true
  'fillmissing', true
  'filter', true
  'filter2', true
  'find', true
  'fix', false
  'flip', true
  'fliplr', true
  'flipud', true
  'floor', false
  'func2str', true
  'gamma', true
  'gammainc', true
  'gammaln', true
  'gcd', true
  'ge', true
  'getfield', true
  'gt', true
  'histc', true
  'histcounts', true
  'horzcat', true
  'hypot', true
  'ifft', true
  'ifft2', true
  'ifftshift', true
  'imag', false
  'ind2sub', true
  'int2str', true
  'interp1', true
  'interp2', true
  'intersect', true
  'inv', true
  'ipermute', true
  'isa', true
  'iscell', true
  'iscellstr', true
  'ischar', true
  'iscolumn', true
  'iscomplex', true
  'isempty', true
  'isequal', true
  'isequaln', true
  'isfield', true
  'isfinite', true
  'isinf', true
  'islogical', true
  'ismatrix', true
  'ismember', true
  'ismissing', true
  'isnan', true
  'isnumeric', true
  'isprime', true
  'isreal', true
  'isrow', true
  'isscalar', true
  'issorted', true
  'isstruct', true
  'isvector', true
  'kron', true
  'lcm', true
  'ldivide', true
  'le', true
  'length', true
  'linspace', true
  'log', false
  'log10', false
  'log1p', false
  'log2', false
  'logical', true
  'logspace', true
  'lower', true
  'lt', true
  'lu', true
  'magic', true
  'mat2str', true
  'max', true
  'mean', true
  'median', true
  'meshgrid', true
  'min', true
  'minus', true
  'mkpp', true
  'mldivide', true
  'mod', true
  'mode', true
  'movmax', true
  'movmean', true
  'movmedian', true
  'movmin', true
  'movprod', true
  'movstd', true
  'movsum', true
  'movvar', true
  'mpower', true
  'mrdivide', true
  'mtimes', true
  'nchoosek', true
  'ndgrid', true
  'ndims', true
  'ne', true
  'nextpow2', true
  'nnz', true
  'norm', true
  'normalize', true
  'not', true
  'nthroot', true
  'null', true
  'num2cell', true
  'num2str', true
  'numel', true
  'numfields', true
  'ones', true
  'or', true
  'orth', true
  'pchip', true
  'perms', true
  'permute', true
  'pinv', true
  'plus', true
  'polyder', true
  'polyfit', true
  'polyint', true
  'polyval', true
  'pow2', true
  'power', true
  'ppval', true
  'prctile', true
  'primes', true
  'prod', true
  'psi', true
  'qr', true
  'quantile', true
  'rad2deg', false
  'range', true
  'rank', true
  'rat', true
  'rats', true
  'rdivide', true
  'real', false
  'reallog', true
  'realpow', true
  'realsqrt', true
  'regexp', true
  'regexpi', true
  'regexprep', true
  'rem', true
  'repmat', true
  'rescale', true
  'reshape', true
  'rmfield', true
  'rmmissing', true
  'roots', true
  'rot90', true
  'round', false
  'sec', false
  'secd', false
  'sech', false
  'setdiff', true
  'setfield', true
  'setxor', true
  'sign', false
  'sin', false
  'sind', false
  'sinh', false
  'size', true
  'sort', true
  'sortrows', true
  'spline', true
  'sprintf', true
  'sqrt', false
  'sqrtm', true
  'squeeze', true
  'standardizeMissing', true
  'startsWith', true
  'std', true
  'str2double', true
  'strcat', true
  'strcmp', true
  'strcmpi', true
  'strfind', true
  'strjoin', true
  'strrep', true
  'strsplit', true
  'strtrim', true
  'struct', true
  'struct2cell', true
  'sub2ind', true
  'sum', true
  'svd', true
  'tan', false
  'tand', false
  'tanh', false
  'times', true
  'trace', true
  'transpose', true
  'trapz', true
  'tril', true
  'triu', true
  'uminus', true
  'union', true
  'unique', true
  'unmkpp', true
  'uplus', true
  'upper', true
  'var', true
  'vecnorm', true
  'vertcat', true
  'xor', true
  'zeros', true
};
singles = {
  '[]'
  'zeros(1, 0)'
  'zeros(0, 3)'
  'NaN'
  'Inf'
  '-2'
  '0'
  '3'
  '2.5'
  '[1 NaN 3]'
  '1:5'
  '(1:5)'''
  '[4 -2; 1 3]'
  'magic(4)'
  '[1+2i 3-1i]'
  '1i'
  '''ab'''
  ''''''
  '[''ab''; ''cd'']'
  'true'
  '[true false]'
  '{1, ''a''}'
  '{''ab'', ''c''}'
  '{}'
  'struct(''a'', 1)'
  'struct([])'
  '@sin'
  '@(x) x + 1'
};
pairs = {
  '[4 -2; 1 3]', '[]'
  '[4 -2; 1 3]', '1'
  '[4 -2; 1 3]', '2'
  '[4 -2; 1 3]', '0'
  '[4 -2; 1 3]', '-1'
  '[4 -2; 1 3]', '0.5'
  '[4 -2; 1 3]', 'NaN'
  '[4 -2; 1 3]', '''all'''
  '[4 -2; 1 3]', '''ab'''
  '[4 -2; 1 3]', '{1}'
  '1:5', '[]'
  '1:5', '1'
  '1:5', '2'
  '1:5', '0'
  '1:5', '-1'
  '1:5', '0.5'
  '1:5', 'NaN'
  '1:5', '''all'''
  '1:5', '''ab'''
  '1:5', '{1}'
  '[]', '[]'
  '[]', '1'
  '[]', '2'
  '[]', '0'
  '[]', '-1'
  '[]', '0.5'
  '[]', 'NaN'
  '[]', '''all'''
  '[]', '''ab'''
  '[]', '{1}'
  '''ab''', '[]'
  '''ab''', '1'
  '''ab''', '2'
  '''ab''', '0'
  '''ab''', '-1'
  '''ab''', '0.5'
  '''ab''', 'NaN'
  '''ab''', '''all'''
  '''ab''', '''ab'''
  '''ab''', '{1}'
  '{''ab'', ''c''}', '[]'
  '{''ab'', ''c''}', '1'
  '{''ab'', ''c''}', '2'
  '{''ab'', ''c''}', '0'
  '{''ab'', ''c''}', '-1'
  '{''ab'', ''c''}', '0.5'
  '{''ab'', ''c''}', 'NaN'
  '{''ab'', ''c''}', '''all'''
  '{''ab'', ''c''}', '''ab'''
  '{''ab'', ''c''}', '{1}'
  '[1+2i 3-1i]', '[]'
  '[1+2i 3-1i]', '1'
  '[1+2i 3-1i]', '2'
  '[1+2i 3-1i]', '0'
  '[1+2i 3-1i]', '-1'
  '[1+2i 3-1i]', '0.5'
  '[1+2i 3-1i]', 'NaN'
  '[1+2i 3-1i]', '''all'''
  '[1+2i 3-1i]', '''ab'''
  '[1+2i 3-1i]', '{1}'
  'NaN', '[]'
  'NaN', '1'
  'NaN', '2'
  'NaN', '0'
  'NaN', '-1'
  'NaN', '0.5'
  'NaN', 'NaN'
  'NaN', '''all'''
  'NaN', '''ab'''
  'NaN', '{1}'
};
state = warning;
warning('off', 'all');
s = 0;
for f = 1:size(sweep, 1)
  arglists = [{''}; singles];
  if sweep{f, 2}, arglists = [arglists; strcat(pairs(:, 1), {', '}, pairs(:, 2))]; end
  for a = 1:numel(arglists)
    s = s + 1;
    writeCase(fid, 'sweep', sprintf('s%d', s), sprintf('r__ = %s(%s);', sweep{f, 1}, arglists{a}), 'r__');
  end
  if mod(f, 25) == 0, fprintf('  swept %d of %d functions\n', f, size(sweep, 1)); end
end
warning(state);
writeDisplay(fid, 'containers.m', {
  'c = {1, ''two''; [1 2 3], {4}}'
  's.name = ''Ada'';'
  's.age = 36;'
  's.scores = [90 85];'
  's'
  't = struct(''a'', {1, 2})'
  'f = @(x) x.^2 + 1'
  'g = @sin'
  'e = struct()'
});
writeDisplay(fid, 'empties.m', {
  'e = []'
  'z3 = zeros(0, 3)'
  'r = zeros(1, 0)'
  'c = zeros(0, 1)'
  'es = '''''
  'l = true(0, 2)'
  'ce = {}'
  'disp([])'
});
writeDisplay(fid, 'formats.m', {
  'format long'
  'p = pi'
  'v = [1/3 2/3]'
  'format short'
  'p = pi'
  '3 + 4'
  'ans * 2'
});
writeDisplay(fid, 'numeric.m', {
  'x = 5'
  'y = -3.5'
  'z = pi'
  'b = 1e10'
  's = 1e-5'
  'n = NaN'
  'v = [1 2 3]'
  'w = [1.5 2.25 -3]'
  'q = [1 NaN Inf -Inf]'
  'big = [1 1e5]'
  'mix = [1 1000.5]'
  'tiny = [0.001 0.002]'
  'M = magic(3)'
  'M4 = magic(4)'
  'F = [1.5 2; 3 4]'
  'E = eye(2)*1e6'
  'neg = [-1 -2.5]'
  'col = [1; -2; 3]'
  'wide = 1:25'
  'c1 = 1 + 2i'
  'c2 = [1+2i 3-4.5i]'
  'c3 = sqrt(-2)'
});
writeDisplay(fid, 'text.m', {
  't = true'
  'tf = [true false; false true]'
  'str = ''hello'''
  'cm = [''abc''; ''def'']'
  'disp(''plain text'')'
  'disp([1 2 3])'
  'disp(pi)'
  'fprintf(''%d apples, %.2f pears\n'', 3, 2.5)'
  'fprintf(''%s|'', ''a'', ''bc''); fprintf(''\n'')'
  'x = sprintf(''%5.1f'', [1.25 -2.5])'
});
format short
format loose
fprintf(fid, '#END\n');
fprintf('Done: %d cases written to %s\n', size(cases, 1) + s, outfile);
end

function writeCase(fid, kind, id, code, name)
fprintf(fid, '@@ %s %s\n', kind, id);
fprintf(fid, 'code: %s\n', code);
lastwarn('');
try
  if isempty(name)
    runCode(code);
    fprintf(fid, 'noerror\n');
  else
    v = runCode(code, name);
    writeValue(fid, v, 0);
  end
catch err
  fprintf(fid, 'error: %s\n', oneLine(err.identifier));
  fprintf(fid, 'message: %s\n', oneLine(err.message));
end
[msg, wid] = lastwarn;
if ~isempty(msg), fprintf(fid, 'warning: %s | %s\n', wid, oneLine(msg)); end
end

function value__ = runCode(code__, name__)
eval(code__);
if nargin > 1, value__ = eval(name__); end
end

function writeValue(fid, v, depth)
pad = repmat(' ', 1, 2 * depth);
fprintf(fid, '%sclass: %s\n', pad, class(v));
fprintf(fid, '%ssize:%s\n', pad, sprintf(' %d', size(v)));
if isnumeric(v) || islogical(v) || ischar(v)
  x = double(v(:)).';
  n = min(numel(x), 60);
  fprintf(fid, '%sre:%s\n', pad, sprintf(' %.17g', real(x(1:n))));
  if ~isreal(v), fprintf(fid, '%sim:%s\n', pad, sprintf(' %.17g', imag(x(1:n)))); end
  if numel(x) > n, fprintf(fid, '%struncated: %d\n', pad, numel(x)); end
elseif iscell(v) && depth < 2
  for k = 1:min(numel(v), 20)
    fprintf(fid, '%scell %d\n', pad, k);
    writeValue(fid, v{k}, depth + 1);
  end
elseif isstruct(v)
  f = fieldnames(v);
  fprintf(fid, '%sfields:%s\n', pad, sprintf(' %s', f{:}));
elseif isa(v, 'function_handle')
  fprintf(fid, '%sfunc: %s\n', pad, func2str(v));
end
end

function writeDisplay(mw_fid, mw_file, mw_lines)
% Runs a display script line by line in one workspace, recording
% exactly what each line prints (format compact, as MatWeb shows).
format short
format compact
for mw_k = 1:numel(mw_lines)
  fprintf(mw_fid, '@@ display %s %d\n', mw_file, mw_k);
  fprintf(mw_fid, '>> %s\n', mw_lines{mw_k});
  try
    mw_out = evalc(mw_lines{mw_k});
  catch mw_err
    mw_out = sprintf('Error: %s\n', mw_err.message);
  end
  fprintf(mw_fid, '%s', mw_out);
  fprintf(mw_fid, '@@ enddisplay\n');
end
end

function s = oneLine(s)
s = strrep(strrep(s, char(13), ''), char(10), '\n');
end
